# -*- coding: utf-8 -*-
# At-a-glance quick-answer rows per slug, rendered after section 1 by build_new_page.
# Authored 2026-07-24 by a 30-page author+adversarial-verify workflow; every value is
# traceable to the page body - no new claims, prices or dates. Edit freely.
AT_A_GLANCE = {
 'broadband-down': [
  ('Kit or the line?', 'Cable a laptop straight into the router &mdash; if wired fails and the broadband light is off, the fault is on the line.'),
  ('Keep rebooting the router?', 'No &mdash; restart it once only; repeated reboots can leave the line slower long after the fault is fixed.'),
  ('How long to fix?', 'On standard care the target is the end of the second working day, excluding weekends and bank holidays.'),
  ('Compensation due?', 'Often automatic &mdash; around &pound;9&ndash;&pound;10 a day once a total loss passes two full working days, if your provider is in Ofcom&rsquo;s scheme.'),
  ('Card payments still work?', 'Usually &mdash; most modern card readers fall back to a mobile network by themselves, so check yours first.'),
  ('When to call us', 'If mobile coverage is poor, the outage runs into days or you need real bandwidth, our van brings a connection to you.'),
 ],
 'btinternet-email-wont-add-to-new-outlook': [
  ('Most common cause', 'The new Outlook auto-detects the wrong settings &mdash; adding the account manually as IMAP usually fixes it.'),
  ('Settings to use', 'mail.btinternet.com for both servers &mdash; port 993 incoming, 465 outgoing, SSL/TLS on.'),
  ('Which password?', 'Your normal BT email password &mdash; unless two-step verification is on, when BT has you generate an app-specific one.'),
  ('Left BT broadband?', 'Your mailbox may have dropped to Basic (webmail only); BT&rsquo;s Premium Mail, around &pound;7.50 a month, restores app access.'),
  ('Will I lose my emails?', 'No &mdash; IMAP keeps your mail on BT&rsquo;s servers, so re-adding the account deletes nothing.'),
  ('Can it be fixed remotely?', 'Yes &mdash; most BT email setups are done remotely, usually the same day, and it&rsquo;s no fix, no fee.'),
 ],
 'business-email-down-domain-expired': [
  ('Most common cause', 'The renewal reminder went to an email address on the expired domain itself &mdash; so it bounced and nobody saw it.'),
  ('DIY first step', 'Run a WHOIS or domain expiry check to confirm the domain has lapsed, then log in to your registrar and renew straight away.'),
  ('How long to fix?', 'Once the domain is renewed, email usually returns as DNS propagates &mdash; typically within a few hours, occasionally up to a day.'),
  ('Will I lose my emails?', 'Renew in time and your mailbox contents and settings are untouched; some mail sent while you were down is retried for a day or two, but hard-bounced messages are gone.'),
  ('How long can I leave it?', '.co.uk and .uk domains renew at the standard price for up to 90 days after expiry; .com, .net and .org have roughly 30 days before redemption fees apply.'),
  ('Can it be fixed remotely?', 'Yes &mdash; remote help across the UK, usually same-day and no-fix-no-fee, Mon&ndash;Fri 9am&ndash;5pm on 01202 775566.'),
 ],
 'cant-open-attachments-in-outlook': [
  ('Most common cause', 'Outlook deliberately blocking a risky file type such as a .exe to protect your computer.'),
  ('If nothing opens at all', 'Usually a full temporary Outlook files folder, no default app for that file type, or Protected View.'),
  ('DIY first step', 'Right-click the attachment, Save As to your Desktop, then double-click it there &mdash; it works nine times out of ten.'),
  ('Can it be fixed remotely?', 'Yes &mdash; we fix it remotely while you watch, usually in minutes, and access ends when it&rsquo;s done.'),
  ('Blocked .exe attachments', 'Ask the sender to share the file via a OneDrive link or zip instead of forcing Outlook to unblock it.'),
  ('When to call us', 'If the registry step worries you or it still won&rsquo;t open &mdash; 01202 775566, Mon&ndash;Fri 9am&ndash;5pm, same-day help.'),
 ],
 'cant-send-btinternet-email-new-outlook': [
  ('Most common cause', 'Wrong outgoing (SMTP) server settings &mdash; usually authentication switched off, or the port and encryption don&rsquo;t match.'),
  ('Correct SMTP settings', 'mail.btinternet.com, port 465 with SSL, authentication on, and your full email address as the username.'),
  ('DIY first step', 'Remove the BT account and re-add it using advanced IMAP setup &mdash; new Outlook usually won&rsquo;t let you edit an existing account.'),
  ('If port 465 fails', 'Re-add the account using port 587 with STARTTLS instead &mdash; never mix the port and encryption pairings.'),
  ('Left BT broadband?', 'Free Basic email is webmail-only and can&rsquo;t send or receive in Outlook at all &mdash; no settings change will fix that.'),
  ('Can it be fixed remotely?', 'Yes &mdash; most are sorted in one short remote session while you watch, and it&rsquo;s no fix, no fee.'),
 ],
 'dell-this-pc-cant-run-windows-11': [
  ('Most common cause', 'TPM 2.0, Secure Boot or UEFI mode switched off in the BIOS &mdash; on most Dell business machines just settings, not a hardware fault.'),
  ('DIY first step', 'Restart, tap F2 at the Dell logo, then look under Security for TPM 2.0/Intel PTT and Secure Boot.'),
  ('How long does it take?', 'A quick BIOS check often takes minutes &mdash; and there&rsquo;s no call-out fee.'),
  ('Will I lose my data?', 'We back up first if any disk conversion is involved, and it&rsquo;s done carefully so nothing is lost.'),
  ('When it can&rsquo;t be fixed', 'If the processor is older than roughly Intel 8th generation (pre-2017) &mdash; and forcing Windows 11 past it isn&rsquo;t recommended.'),
  ('If it&rsquo;s too old', 'A Windows-11-ready refurbished Dell from &pound;510, with your files and settings transferred across.'),
 ],
 'emails-on-computer-but-not-phone': [
  ('Most common cause', 'Usually POP on the computer removing mail from the server, or a password change the phone missed.'),
  ('DIY first step', 'Sign in to webmail in a browser &mdash; if the missing emails aren&rsquo;t there either, the computer&rsquo;s POP is taking them.'),
  ('Fixable remotely?', 'Yes &mdash; we connect securely by remote support and set the account up properly on every device.'),
  ('Will I lose emails?', 'With IMAP or Exchange, no &mdash; the one real risk is POP mail already pulled onto a single computer.'),
  ('Often the quickest fix', 'Installing the provider&rsquo;s free official app &mdash; Gmail or Outlook &mdash; is frequently the five-minute fix.'),
  ('When to call us', 'If the three checks and matching fixes don&rsquo;t get the phone syncing &mdash; no fix, no fee, on 01202 775566.'),
 ],
 'new-outlook-emails-stuck-in-drafts': [
  ('Most common cause', 'New Outlook has no Outbox for many account types, so a failed send slips silently back into Drafts.'),
  ('Will I lose the email?', 'No &mdash; a message parked in Drafts is saved, not lost; it just hasn&rsquo;t been sent.'),
  ('DIY first step', 'Check Sent and webmail to confirm it really didn&rsquo;t go, then open the draft and press Send again.'),
  ('Can it be fixed remotely?', 'Yes &mdash; most problems on this page are fixed in one short remote session, no fix, no fee.'),
  ('Back to classic Outlook?', 'Yes, and many people prefer it &mdash; but it needs a Microsoft 365 or Office licence that includes it.'),
  ('When to call us', 'If the account won&rsquo;t re-add, or mail fails everywhere including webmail &mdash; call 01202 775566, often same-day.'),
 ],
 'new-outlook-only-showing-recent-emails': [
  ('Are my old emails deleted?', 'Almost certainly not &mdash; they&rsquo;re still in your mailbox on the server; the app is only showing a recent slice.'),
  ('DIY first step', 'Sign in to your provider&rsquo;s webmail in a browser &mdash; it proves in about two minutes that the old mail still exists.'),
  ('The setting to change', 'Lengthen the sync window ("download email for") to the longest option &mdash; new Outlook currently goes up to 180 days.'),
  ('The one real exception', 'Mail in old PST archive files was never on the server &mdash; Classic Outlook opens those natively; new Outlook can&rsquo;t reliably.'),
  ('Can it be fixed remotely?', 'Yes &mdash; most problems on this page are fixed in one short remote session, no-fix-no-fee.'),
  ('When to call us', 'If webmail shows the mail but the app still won&rsquo;t, or years of email sit in PST archives &mdash; 01202 775566, Mon-Fri 9am-5pm.'),
 ],
 'office-wifi-keeps-dropping-out': [
  ('Whole office drops at once?', 'The fault is shared infrastructure &mdash; router, switch, airwaves or broadband line &mdash; not the individual laptops.'),
  ('DIY first check', 'The moment a drop hits, check a wired computer &mdash; if it loses internet too, the WiFi is innocent and the line or router is failing.'),
  ('Brief random cut-outs', 'A classic sign of a 5 GHz radar (DFS) event &mdash; genuinely plausible near the Dorset coast and Bournemouth Airport.'),
  ('Will mesh WiFi help?', 'Often not in offices &mdash; mesh can&rsquo;t fix a full address pool, a failing switch or a dropping broadband line.'),
  ('What will it cost?', 'Sometimes just a settings change; there&rsquo;s no fixed price list because buildings differ, and the free survey report says which end of the scale you&rsquo;re on.'),
  ('When to call us', 'Book the free room-by-room survey, run during a normal working day, for a written plain-English report &mdash; call 01202 775566.'),
 ],
 'onedrive-files-disappeared': [
  ('Are my files really deleted?', 'Rarely &mdash; nine times out of ten they&rsquo;ve been moved, paused or signed out, not deleted.'),
  ('Most common cause', 'Windows Backup quietly moved your Desktop, Documents and Pictures into OneDrive.'),
  ('DIY first step', 'Open File Explorer, click OneDrive in the sidebar and look for your folders there.'),
  ('Deleted-file safety net', 'OneDrive&rsquo;s online Recycle Bin keeps deleted files for 30 days (93 for most work accounts).'),
  ('Can it be fixed remotely?', 'Yes &mdash; same-day via Splashtop SOS, usually sorted within minutes, with no fix, no fee.'),
  ('What to avoid', 'Don&rsquo;t reinstall Windows, run unknown recovery tools or delete the local OneDrive folder.'),
 ],
 'onedrive-keeps-asking-to-sign-in': [
  ('Most common cause', 'A stale cached credential &mdash; Windows keeps re-serving an old sign-in that Microsoft&rsquo;s servers no longer accept.'),
  ('DIY first step', 'Quit OneDrive, remove the &ldquo;OneDrive Cached Credential&rdquo; entries in Credential Manager, restart and sign in once.'),
  ('Will I lose my files?', 'No &mdash; unlinking or resetting only breaks the sync link; just don&rsquo;t delete the local OneDrive folder.'),
  ('Work account keeps signing out?', 'Often deliberate &mdash; organisation security policies expire work sessions on a schedule, so it isn&rsquo;t a fault on your PC.'),
  ('When to call us', 'If the loop survives clearing credentials, unlinking and relinking, a reset and a second-account check.'),
  ('Can it be fixed remotely?', 'Yes &mdash; we connect, watch the loop happen and fix the real cause, no fix, no fee.'),
 ],
 'outlook-shared-mailbox-not-showing': [
  ('Most common cause', 'Timing &mdash; automapping adds the mailbox automatically but can take up to an hour and needs a full Outlook restart.'),
  ('DIY first step', 'Close Outlook completely (on Windows check Task Manager), wait a little, then reopen it.'),
  ('How long to appear?', 'Usually a few minutes to about an hour after Full Access is granted.'),
  ('Can send but not see it?', 'You&rsquo;ve likely got Send As only &mdash; the mailbox needs Full Access to show in your folder list.'),
  ('Can it be fixed remotely?', 'Yes &mdash; we add it remotely while you watch, usually in minutes, and access ends when it&rsquo;s done.'),
  ('When to call us', 'If it still won&rsquo;t show after an hour, restarts and a manual add &mdash; we&rsquo;ll check Full Access was really granted.'),
 ],
 'plusnet-email-wont-add-to-new-outlook': [
  ('Most common cause', 'New Outlook auto-detects the wrong mail servers, then shows a misleading app-password error &mdash; Plusnet doesn&rsquo;t use app passwords.'),
  ('DIY first step', 'Add the mailbox by hand as IMAP: incoming imap.plus.net, port 993, SSL/TLS; outgoing relay.plus.net, port 587, STARTTLS.'),
  ('Which password to use', 'Your ordinary Plusnet mailbox password &mdash; the one for webmail &mdash; not your Microsoft account password.'),
  ('If it still fails', 'Switch back to classic Outlook and add the account there with manual IMAP setup &mdash; it handles Plusnet without complaint.'),
  ('Does Greenby break it?', 'No &mdash; your address and the server names keep working, but the mailbox becomes chargeable (around &pound;15 a year) once any free period ends.'),
  ('Can it be fixed remotely?', 'Yes &mdash; most Plusnet-in-Outlook jobs take a few minutes over a remote session, no-fix-no-fee, usually same day, Monday to Friday.'),
 ],
 'printer-disappeared-after-windows-update': [
  ('Is the printer really gone?', 'Almost never &mdash; the update breaks the software link, and the printer is usually still installed.'),
  ('Most common cause', 'The update replaced or removed the printer&rsquo;s driver, or left the Print Spooler service stopped.'),
  ('DIY first step', 'Restart the Print Spooler (services.msc) &mdash; a 30-second fix that clears a large share of cases.'),
  ('Can it be fixed remotely?', 'Yes &mdash; most printer-after-update problems are fixed in one short remote session, often the same day.'),
  ('Will I lose my files?', 'No &mdash; clearing the print queue or reinstalling a driver doesn&rsquo;t touch your documents; only a full System Restore needs a backup first.'),
  ('When to call us', 'If the spooler restart and re-adding haven&rsquo;t worked &mdash; call 01202 775566; no fix, no fee.'),
 ],
 'printer-prints-but-wont-scan-after-new-router': [
  ('Most common cause', 'Router settings blocking the printer from finding your computer &mdash; AP isolation, guest WiFi or Windows marking the new network Public &mdash; not a failing printer.'),
  ('DIY first step', 'Print the printer&rsquo;s network configuration report and check its address matches your computer&rsquo;s &mdash; after a router swap they often don&rsquo;t.'),
  ('The reliable fix', 'Remove the printer, then reinstall the manufacturer&rsquo;s full software package rather than just the basic driver &mdash; about ten minutes.'),
  ('Fixable remotely?', 'Yes &mdash; we can be looking at your screen within minutes, and most faults on this page are fixed in one short remote session, no fix no fee.'),
  ('Need a new printer?', 'Almost certainly not &mdash; this is configuration, not a dying printer, and it&rsquo;s usually fixable in under an hour.'),
  ('Router-proof alternative', 'Scan to email, set up on the printer itself, survives router swaps &mdash; use a provider-independent address such as Gmail or Outlook.com.'),
 ],
 'printer-says-wifi-password-incorrect': [
  ('Is the password really wrong?', 'Usually not &mdash; most printers use it as a catch-all error for any failure to join the network.'),
  ('The usual real culprits', 'A 2.4GHz-only printer on a merged-band network, WPA3-only security, a UK router on channel 12 or 13, or stale settings saved from an old router.'),
  ('DIY first step', 'Restart both printer and router, then retype the password once, slowly, minding upper and lower case.'),
  ('The UK-specific catch', 'UK routers can auto-pick channel 12 or 13, which US-firmware printers can&rsquo;t see &mdash; set the 2.4GHz channel to 11 or below.'),
  ('Can it be fixed remotely?', 'Usually &mdash; call 01202 775566 (Mon&ndash;Fri 9am&ndash;5pm) and we can be looking at your screen within minutes; most problems on this page are fixed in one short remote session.'),
  ('Cost if we can&rsquo;t fix it', 'Nothing &mdash; printer support is no fix, no fee.'),
 ],
 'printer-stopped-working-after-changing-wifi-password': [
  ('Most common cause', 'The printer is still trying the old password &mdash; printers save it once at setup and never prompt when it changes.'),
  ('DIY first step', 'Re-run the printer&rsquo;s Wireless Setup Wizard and type the new password slowly &mdash; it&rsquo;s case-sensitive and 1, l and I are easy to confuse.'),
  ('No screen on the printer?', 'Use the WPS buttons on router then printer, or connect a USB cable temporarily and run the maker&rsquo;s free setup app.'),
  ('Printing works, scanning doesn&rsquo;t', 'Scanning is registered separately and may point at the printer&rsquo;s old address &mdash; remove and re-add the printer or re-run the scan setup.'),
  ('Can it be fixed remotely?', 'Yes &mdash; most problems on this page are fixed in one short remote session, no fix, no fee (Mon&ndash;Fri 9am&ndash;5pm).'),
  ('When to call us', 'If the wizard, WPS and USB routes all fail it&rsquo;s usually a router settings mismatch, not a broken printer &mdash; call 01202 775566.'),
 ],
 'printer-wont-connect-after-changing-broadband': [
  ('Most common cause', 'The new router broadcasts a brand-new Wi-Fi network and the printer is still looking for the old one.'),
  ('Is the printer broken?', 'Almost never &mdash; the network changed underneath it, so don&rsquo;t let anyone talk you into a new printer.'),
  ('DIY first step', 'Run the printer&rsquo;s wireless setup, join the new network, then remove and re-add the printer on your computers.'),
  ('Connected but not printing?', 'Usually a fixed IP address from the old router&rsquo;s range &mdash; set it back to automatic (DHCP) and re-add the printer.'),
  ('Handy shortcut', 'Give the new router the same Wi-Fi name and password as the old one and the printer usually rejoins by itself.'),
  ('Can it be fixed remotely?', 'Yes &mdash; most of these are fixed in one short remote session, no fix no fee (Mon&ndash;Fri, 9am&ndash;5pm).'),
 ],
 'printer-wont-connect-after-moving-house': [
  ('Most common cause', 'The printer still remembers your old home&rsquo;s Wi-Fi name and password &mdash; nothing is broken.'),
  ('DIY first step', 'Run the wireless setup wizard on the printer itself and pick your new network name.'),
  ('Can it be fixed remotely?', 'Yes &mdash; it&rsquo;s all settings, so we can nearly always fix it remotely, no-fix-no-fee.'),
  ('How long does it take?', 'Usually one short remote session, most often the same day &mdash; many manage the DIY steps in ten minutes.'),
  ('Will I lose settings?', 'No &mdash; reconnecting the Wi-Fi doesn&rsquo;t wipe the printer, and you don&rsquo;t need the original disc.'),
  ('When to call us', 'If the wizard keeps failing or the printer won&rsquo;t hold the connection, call 01202 775566.'),
 ],
 'printer-wont-connect-to-bt-smart-hub': [
  ('Most common cause', 'Most home printers are 2.4GHz-only, but the Smart Hub broadcasts 2.4GHz and 5GHz under one name, so the printer gets caught on the wrong band.'),
  ('DIY first step', 'Move the printer and your phone close to the Hub, restart the printer and re-enter the wifi details from the Hub&rsquo;s card &mdash; a new Hub means a new name and password.'),
  ('The Hub Manager trick', 'Sign in at 192.168.1.254, temporarily switch off the 5GHz band while the printer joins, then switch it back on afterwards.'),
  ('Can it be fixed remotely?', 'Yes &mdash; we sort the Hub and printer together while you watch, on a no fix, no fee basis.'),
  ('How long does it take?', 'Most problems on this page are fixed in one short remote session, usually the same day.'),
  ('When to call us', 'If you&rsquo;d rather not poke around in router settings, ring 01202 775566 (Monday to Friday, 9 to 5).'),
 ],
 'printer-wont-connect-to-ee-smart-hub': [
  ('Most common cause', 'After the BT-to-EE switch your printer is still trying to join the old BT wifi that no longer exists &mdash; plus band steering and WPA3 on newer EE hubs.'),
  ('The reliable fix', 'Switch on the hub&rsquo;s Compatible WiFi &mdash; a separate 2.4GHz network using WPA2 &mdash; and re-run the printer&rsquo;s wireless setup against it.'),
  ('DIY first step', 'Open the EE app, or type 192.168.1.254 (or eehub) into a browser and sign in with the admin password on the card on the back of the hub.'),
  ('&lsquo;MAC filter&rsquo; warning', 'Usually a false alarm &mdash; EE&rsquo;s current hubs don&rsquo;t use MAC filtering on the main network, so the real cause is almost always the wrong band or WPA3 security.'),
  ('Can it be fixed remotely?', 'Yes &mdash; most EE-hub printer jobs are fixed remotely, usually the same day, in one short session while you watch.'),
  ('When to call us', 'If you&rsquo;d rather not poke around in hub settings, or it still won&rsquo;t connect after these steps &mdash; 01202 775566, Mon&ndash;Fri 9am&ndash;5pm, no-fix-no-fee.'),
 ],
 'printer-wont-connect-to-mesh-wifi': [
  ('Can it be fixed remotely?', 'Yes &mdash; most problems on this page are fixed in one short remote session, no fix, no fee.'),
  ('Most common cause', 'Most home printers only have a 2.4GHz radio, and mesh band steering can trip them up when both bands share one network name.'),
  ('DIY first step', 'Look in your mesh app for a separate 2.4GHz or IoT network and join the printer to that.'),
  ('Keeps going offline?', 'Most often its IP address keeps changing &mdash; set a DHCP reservation, then add the printer on each computer by that IP.'),
  ('Simplest permanent fix', 'A cable &mdash; most mesh nodes have a spare Ethernet port, which removes every mesh-specific fault in one go.'),
  ('When to call us', 'If you&rsquo;ve tried the lot &mdash; call 01202 775566 and we can be looking at your screen within minutes (Mon&ndash;Fri, 9am&ndash;5pm).'),
 ],
 'printer-wont-connect-to-sky-router': [
  ('Most common cause', 'A band mismatch &mdash; most home printers are 2.4GHz-only, while Sky hubs put both bands under one name and pick the band for you.'),
  ('Black Sky Broadband Hub fix', 'Split the bands at 192.168.0.1 (untick &lsquo;Synchronise 2.4GHz and 5GHz settings&rsquo;), then join the printer to the 2.4GHz name.'),
  ('White Sky Max Hub fix', 'You can&rsquo;t split the bands &mdash; drop the security from WPA3 to WPA2 in the My Sky app, or temporarily turn off 5GHz.'),
  ('Just had Sky installed?', 'Nothing is broken &mdash; the printer still has the old wifi details, so re-enter the new name and password from the hub&rsquo;s sticker.'),
  ('Can it be fixed remotely?', 'Yes &mdash; usually the same day, and most problems on this page are fixed in one short remote session while you watch.'),
  ('When to call us', 'If you&rsquo;d rather not touch hub settings, or the printer has a hardware fault &mdash; it&rsquo;s no fix, no fee on 01202 775566.'),
 ],
 'room-by-room-wifi-test': [
  ('Does it cost anything?', 'No &mdash; the room-by-room WiFi test tool is free, with no sign-up.'),
  ('How long does it take?', 'One pass of the whole house in 10 to 15 minutes, using the same device in every room.'),
  ('Most common cause', 'Solid brick walls, chimney breasts and foil-backed insulation soaking up the signal in UK homes.'),
  ('DIY first step', 'Take a wired baseline at the router, then test standing where you actually use each room.'),
  ('One bad room?', 'Try free fixes first &mdash; move the router off the floor, out of the cupboard and away from the TV, then re-run the survey.'),
  ('When to call us', 'If the map&rsquo;s still ugly, send us the survey PDF and call 01202 775566 &mdash; remote-first, no-fix-no-fee.'),
 ],
 'sage-50-wont-email-invoices-outlook': [
  ('Most common cause', 'The &lsquo;new Outlook&rsquo; taking over from classic Outlook &mdash; it lacks the MAPI component Sage uses to hand over invoices.'),
  ('DIY first step', 'Switch off the New Outlook toggle (top-right in Outlook) so it reopens as classic Outlook, then set classic Outlook as your Windows default email app.'),
  ('Will I lose my emails?', 'No &mdash; classic and new Outlook share the same mailbox, so your emails, calendar and contacts all stay put.'),
  ('Can it be fixed remotely?', 'Yes &mdash; a short remote session from our Bournemouth team, usually the same day, no fix, no fee.'),
  ('Fix without Outlook?', 'Yes &mdash; set Sage&rsquo;s Email Defaults to Webmail (SMTP) so invoices send directly, with no dependence on Outlook.'),
  ('Is the fix permanent?', 'It works today, but Microsoft plans to retire classic Outlook eventually &mdash; webmail (SMTP) is the more durable route.'),
 ],
 'shared-folders-not-working-after-windows-11-24h2-update': [
  ('Most common cause', 'Windows 11 24H2 now requires SMB signing and blocks unauthenticated guest access, so older shares and NAS boxes are refused.'),
  ('Are my files lost?', 'No &mdash; nothing is broken and your files are safe; Windows is simply rejecting the connection.'),
  ('DIY first step', 'Set up a real username and password on the PC or NAS hosting the folder, then reconnect in File Explorer with those details and tick Remember my credentials.'),
  ('Is the quick bodge safe?', 'Re-enabling guest logons or relaxing signing gets you working but reopens credential-theft and relay attacks &mdash; treat it as a short-term patch only.'),
  ('Will Microsoft reverse it?', 'No &mdash; it&rsquo;s a deliberate security change, not a bug, so waiting for a rollback just prolongs the downtime.'),
  ('Can it be fixed remotely?', 'Almost always &mdash; usually same-day, and no fix means no fee.'),
 ],
 'sky-email-wont-add-to-new-outlook': [
  ('Most common cause', 'Sky mail runs on Yahoo, which rejects your normal Sky password &mdash; you need a 16-character app password instead.'),
  ('DIY first step', 'Sign in on Sky&rsquo;s website with your Sky iD, generate an app password and copy it straight away &mdash; it&rsquo;s only shown once.'),
  ('Yahoo or IMAP?', 'Always pick IMAP (or Other); choosing Yahoo starts a web sign-in that often loops or errors with Sky addresses.'),
  ('Sky server settings', 'Incoming imap.mail.yahoo.com port 993 SSL; outgoing smtp.mail.yahoo.com port 465 (or 587) SSL with authentication on.'),
  ('Can it be fixed remotely?', 'Yes &mdash; with your permission we set it up while you watch, usually same-day, on a no-fix-no-fee basis.'),
  ('Left Sky broadband?', 'You keep your @sky.com address free &mdash; just sign in on Sky&rsquo;s website now and again so the mailbox stays active.'),
 ],
 'will-i-lose-files-upgrading-to-windows-11': [
  ('Files at risk?', 'No &mdash; the standard in-place upgrade keeps your files, apps and settings, and keeping everything is the default.'),
  ('Only ways to lose data', 'Choosing &lsquo;Nothing&rsquo; during a manual install, or forcing Windows 11 onto an unsupported PC.'),
  ('Do programs survive?', 'Most carry over intact; a few very old apps, antivirus or disk utilities may need reinstalling afterwards.'),
  ('DIY first step', 'Copy anything irreplaceable to OneDrive or an external drive, then plug the laptop into mains power before upgrading.'),
  ('Changed your mind?', 'You can go back to Windows 10 within 10 days of upgrading, with files and programs intact.'),
  ('Want us to do it?', 'We back up first, upgrade and check everything &mdash; mostly remotely across the UK, no-fix-no-fee.'),
 ],
 'windows-11-upgrade-service': [
  ('Can it be done remotely?', 'Yes &mdash; most upgrades are handled remotely so you never unplug a thing; clean installs get free local collection.'),
  ('Will I lose my files?', 'No &mdash; a full backup is taken first, and an in-place upgrade keeps your files, apps and settings intact.'),
  ('What does it cost?', 'The compatibility check is free; the upgrade is a fixed price quoted before any work begins, no-fix-no-fee.'),
  ('PC says incompatible?', 'Often not final &mdash; TPM 2.0 and Secure Boot are frequently just switched off in the BIOS and can be enabled.'),
  ('If it can&rsquo;t run 11', 'Stay on Windows 10 with ESU security patches until 12 October 2027, or move to a refurbished Dell from &pound;510.'),
  ('Why upgrade now?', 'Windows 10&rsquo;s free security updates ended on 14 October 2025, so it gets steadily riskier the longer it goes unpatched.'),
 ],
}
