# Choice tiles for the local town pages' first screen (26 Sep 2026), templated per page type by
# scratchpad audit2/local_tiles.py: (colour, icon, title, line, tag, href). Hooked in build_pages.add().
LOCAL_HERO_TILES = {
 'business-it-support-subscriptions': [
  ('hp-c-fix', 'briefcase', 'Business plans', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
  ('hp-c-care', 'gauge', 'Your own dashboard', 'See your IT at a glance', 'YOUR DASHBOARD', '#dashboard'),
  ('hp-c-biz', 'gauge', 'Which plan suits us?', 'A few questions, a clear answer', 'QUICK QUESTIONS', '/plan-finder/'),
  ('hp-c-buy', 'phone', 'Book a chat', 'Tell us how you work; we suggest the setup', 'NO OBLIGATION', '/contact/'),
 ],
 'computer-repair-beaminster': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
 ],
 'computer-repair-blandford-forum': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-blandford-forum/'),
 ],
 'computer-repair-boscombe': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
 ],
 'computer-repair-bournemouth': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-bournemouth/'),
 ],
 'computer-repair-bridport': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-bridport/'),
 ],
 'computer-repair-canford-heath': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
 ],
 'computer-repair-christchurch': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-christchurch/'),
 ],
 'computer-repair-corfe-mullen': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-corfe-mullen/'),
 ],
 'computer-repair-dorchester': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-dorchester/'),
 ],
 'computer-repair-ferndown': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-ferndown/'),
 ],
 'computer-repair-gillingham': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-gillingham/'),
 ],
 'computer-repair-lyme-regis': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-lyme-regis/'),
 ],
 'computer-repair-poole': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-poole/'),
 ],
 'computer-repair-portland': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-portland/'),
 ],
 'computer-repair-shaftesbury': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-shaftesbury/'),
 ],
 'computer-repair-sherborne': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-sherborne/'),
 ],
 'computer-repair-st-ives': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
 ],
 'computer-repair-sturminster-newton': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-sturminster-newton/'),
 ],
 'computer-repair-swanage': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-swanage/'),
 ],
 'computer-repair-upton': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-upton/'),
 ],
 'computer-repair-verwood': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-verwood/'),
 ],
 'computer-repair-wareham': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-wareham/'),
 ],
 'computer-repair-west-moors': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-west-moors/'),
 ],
 'computer-repair-west-parley': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
 ],
 'computer-repair-weymouth': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-weymouth/'),
 ],
 'computer-repair-wimborne': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/it-support-wimborne/'),
 ],
 'computer-repair-wool': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
 ],
 'computer-repair-wyke-regis': [
  ('hp-c-fix', 'laptop', 'Book a collection', 'We collect it, find the fault, quote first', 'QUOTE BEFORE WORK', '/book-a-collection/'),
  ('hp-c-care', 'wrench', 'Slow or full of pop-ups?', 'Often fixed remotely, no collection needed', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'star', 'Or a refurbished Dell', 'Business-grade laptops from &pound;510', 'READY TO USE', '/refurbished-laptops-dorset/'),
  ('hp-c-buy', 'calendar', 'Stop it happening again', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
 ],
 'it-support-blandford-forum': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-blandford-forum/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-bournemouth': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-bournemouth/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-bridport': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-bridport/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-broadstone': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repairs/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-brockenhurst': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repairs/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-by-industry': [
  ('hp-c-fix', 'briefcase', 'Accountants and bookkeepers', 'Sage, Xero and deadlines kept running', 'ACCOUNTANTS', '/it-support-for-accountants-dorset/'),
  ('hp-c-care', 'wrench', 'Builders and trades', 'Quotes, jobs and email that work on site', 'TRADES', '/it-support-for-construction/'),
  ('hp-c-biz', 'home', 'Care homes', 'Reliable IT for staff and residents', 'CARE', '/it-support-for-care-homes/'),
  ('hp-c-buy', 'calendar', 'Business plans', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-christchurch': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-christchurch/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Local business IT support, near you', 'FROM &pound;24.38', '/business-it-support-christchurch/'),
 ],
 'it-support-corfe-mullen': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-corfe-mullen/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-cost-guide': [
  ('hp-c-fix', 'book', 'What should it cost?', 'Questions people ask before a quote', 'PLAIN ENGLISH', '#faq'),
  ('hp-c-care', 'calendar', 'Our prices', 'Home &pound;18.25 a PC, business from &pound;24.38', 'PRICES UP FRONT', '/pricing/'),
  ('hp-c-biz', 'gauge', 'Which plan suits us?', 'A few questions, a clear answer', 'QUICK QUESTIONS', '/plan-finder/'),
  ('hp-c-buy', 'phone', 'Get a quote', 'Tell us your setup; we&rsquo;ll price it', 'NO OBLIGATION', '/quick-quote/'),
 ],
 'it-support-dorchester': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-dorchester/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-dorset': [
  ('hp-c-fix', 'home', 'Every town we cover', 'Find your town across Dorset', 'AREAS COVERED', '/areas-covered/'),
  ('hp-c-care', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-ferndown': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-ferndown/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Local business IT support, near you', 'FROM &pound;24.38', '/business-it-support-ferndown-industrial-estate/'),
 ],
 'it-support-for-architects': [
  ('hp-c-fix', 'briefcase', 'Business plans', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
  ('hp-c-care', 'wrench', 'Something down right now?', 'We connect and sort it while you watch', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'gauge', 'Which plan suits us?', 'A few questions, a clear answer', 'QUICK QUESTIONS', '/plan-finder/'),
  ('hp-c-buy', 'phone', 'Get a recommendation', 'Tell us how you work; we suggest the setup', 'NO OBLIGATION', '/contact/'),
 ],
 'it-support-for-creative-agencies': [
  ('hp-c-fix', 'briefcase', 'Business plans', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
  ('hp-c-care', 'wrench', 'Something down right now?', 'We connect and sort it while you watch', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'gauge', 'Which plan suits us?', 'A few questions, a clear answer', 'QUICK QUESTIONS', '/plan-finder/'),
  ('hp-c-buy', 'phone', 'Get a recommendation', 'Tell us how you work; we suggest the setup', 'NO OBLIGATION', '/contact/'),
 ],
 'it-support-for-opticians': [
  ('hp-c-fix', 'briefcase', 'Business plans', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
  ('hp-c-care', 'wrench', 'Something down right now?', 'We connect and sort it while you watch', 'FROM &pound;20', '/remote-support/'),
  ('hp-c-biz', 'gauge', 'Which plan suits us?', 'A few questions, a clear answer', 'QUICK QUESTIONS', '/plan-finder/'),
  ('hp-c-buy', 'phone', 'Get a recommendation', 'Tell us how you work; we suggest the setup', 'NO OBLIGATION', '/contact/'),
 ],
 'it-support-fordingbridge': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repairs/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-gillingham': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-gillingham/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-hythe': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repairs/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-lyme-regis': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-lyme-regis/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-lymington': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repairs/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-lyndhurst': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repairs/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-new-forest': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repairs/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Local business IT support, near you', 'FROM &pound;24.38', '/business-it-support-new-forest/'),
 ],
 'it-support-new-milton': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repairs/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-poole': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-poole/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-ringwood': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repairs/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-shaftesbury': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-shaftesbury/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-sherborne': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-sherborne/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-southampton': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repairs/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-sturminster-newton': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-sturminster-newton/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-swanage': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-swanage/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-totton': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repairs/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-uk-europe': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'book', 'How does it work?', 'Questions about remote help, answered', 'PLAIN ENGLISH', '#faq'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'phone', 'Call us', '01202 775566, Mon&ndash;Fri 9&ndash;5', 'FASTEST', 'tel:+441202775566'),
 ],
 'it-support-upton': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-upton/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-verwood': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-verwood/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-wareham': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-wareham/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-weymouth': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-weymouth/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'it-support-wimborne': [
  ('hp-c-fix', 'wrench', 'Fix it today, remotely', 'We connect to your Windows PC and sort it', 'FROM &pound;20, AGREED FIRST', '/remote-support/'),
  ('hp-c-care', 'laptop', 'Needs a hands-on repair?', 'Collected, diagnosed and quoted before any work', 'BY COLLECTION', '/computer-repair-wimborne/'),
  ('hp-c-biz', 'calendar', 'Looked after every month', 'A full service every six weeks', '&pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-buy', 'briefcase', 'IT for your business', 'Priority support for your whole team', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
}
