# Choice tiles for the fix and guide pages' first screen (26 Sep 2026 review): (colour, icon, title, line, tag, href).
# Two per page when it has a step helper and closing panel (build_extra adds "Fix it with me" and
# "Fix it for me" in front), four when it has neither.
PAGE_HERO_TILES = {
 'alienware-dell-g-series-repair-bournemouth': [
  ('hp-c-fix', 'gauge', 'Running hot or throttling?', 'A proper thermal service usually sorts it', 'NUMBER ONE COMPLAINT', '#s2'),
  ('hp-c-care', 'alert', 'Swollen battery?', 'Stop using it now: we collect and replace it', 'SAFETY FIRST', '#s4'),
  ('hp-c-biz', 'laptop', 'G15 or G16 fans roaring?', 'Dust and paste, or a BIOS and driver fix', 'DIAGNOSIS FIRST', '#s3'),
  ('hp-c-buy', 'home', 'Free collection, no couriers', 'Honest diagnosis and a quote before any work', 'NO BOXING IT UP', '/book-a-collection/'),
 ],
 'are-dell-latitude-laptops-good': [
  ('hp-c-fix', 'laptop', 'See Latitudes in stock', 'Pick a tested Latitude by budget and job', 'STOCK PICKER', '/dell-hardware/'),
  ('hp-c-care', 'star', 'The honest verdict', 'Short answer: yes, and who they suit', 'READ THIS FIRST', '#s1'),
  ('hp-c-biz', 'gauge', 'Refurb or new budget?', 'Why a used Latitude outlasts a cheap new laptop', 'COMPARE FIRST', '#s3'),
  ('hp-c-buy', 'laptop', 'Refurbished Dell laptops', 'New SSD, licensed Windows, honest A/B/C grade', 'NEW SSD FITTED', '/refurbished-dell-laptops-bournemouth/'),
 ],
 'basic-paye-tools-could-not-access-the-database': [
  ('hp-c-fix', 'shield', 'Copy your data first', 'Find the hidden payroll folder and back it up', 'BEFORE ANYTHING ELSE', '#s3'),
  ('hp-c-care', 'wrench', 'Rebuild and restore', 'Rename the file, then restore your latest backup', 'STEP BY STEP', '#s4'),
  ('hp-c-biz', 'briefcase', 'Shared or network install?', 'Different causes, and safer steps, on a network', 'OFFICE SETUPS', '#s5'),
  ('hp-c-buy', 'clock', 'Deadline today?', 'We can usually join you remotely the same day', 'NO FIX, NO FEE', '/remote-support/'),
 ],
 'broadband-down': [
  ('hp-c-fix', 'wifi', 'Your line or your kit?', 'The first five minutes, in the right order', 'START HERE', '#s1'),
  ('hp-c-care', 'phone', 'Report it properly', 'Three questions that stop you being fobbed off', 'BEFORE YOU RING', '#s2'),
  ('hp-c-biz', 'briefcase', 'Keep trading meanwhile', 'Card machines, phones and a phone hotspot', 'WHILE YOU WAIT', '#s3'),
  ('hp-c-buy', 'wifi', 'Internet brought to you', 'Our van helps when mobile signal is poor', 'OUTAGE RUNNING DAYS?', '/emergency-internet/'),
 ],
 'broadband-to-a-boat-mooring': [
  ('hp-c-fix', 'wifi', 'How the link works', 'Two aerials, clear air, your own broadband', 'PLAIN ENGLISH', '#s1'),
  ('hp-c-care', 'gauge', 'How far can it reach?', 'A few hundred metres, up to about 2km', 'LINE OF SIGHT', '#s2'),
  ('hp-c-biz', 'calendar', 'What the survey checks', 'Sight line, mounting and power at the boat end', 'QUOTED PER SITE', '#s4'),
  ('hp-c-buy', 'power', 'No view of the house?', 'Starlink and off-grid power for the boat end', 'PLAN B', '#s5'),
 ],
 'business-continuity-internet': [
  ('hp-c-fix', 'wifi', 'Get a failover router first', 'Switches to 4G or 5G in seconds, unattended', 'FIRST LINE', '#s1'),
  ('hp-c-care', 'alert', 'What actually breaks?', 'Tills, phones, cards, CCTV: list it and cost it', 'STEP ONE', '#s2'),
  ('hp-c-biz', 'book', 'What the plan contains', 'Triggers, named roles and an escalation ladder', 'WRITTEN PROCEDURE', '#s3'),
  ('hp-c-buy', 'briefcase', 'When failover isn&rsquo;t enough', 'Our off-grid van for long outages and power cuts', 'SECOND LINE', '/emergency-internet/'),
 ],
 'business-hacked-emergency-help': [
  ('hp-c-fix', 'alert', 'First 10 minutes', 'Isolate it, don&rsquo;t switch it off, then call', 'DO THIS NOW', '#s1'),
  ('hp-c-care', 'shield', 'How we contain it', 'Triage, lock the attacker out, restore cleanly', 'SAME-DAY HELP', '#s2'),
  ('hp-c-biz', 'book', 'Who to report it to', 'Report Fraud, your bank, the ICO and insurer', '72-HOUR CLOCK', '#s3'),
  ('hp-c-buy', 'wrench', 'Stop it happening again', 'MFA, tested backups and staff training', 'AFTERWARDS', '/cybersecurity-support/'),
 ],
 'business-it-support-christchurch': [
  ('hp-c-fix', 'briefcase', 'Your outsourced IT team', 'Monitoring, patching, backups and a helpdesk', 'FULLY MANAGED', '#s1'),
  ('hp-c-care', 'home', 'Need someone on site?', 'Minutes from the Christchurch business parks', 'LOCAL AND SAME-DAY', '#s2'),
  ('hp-c-biz', 'calendar', 'How switching works', 'Free review, clear quote, quiet handover', 'NO LOCK-IN', '#s3'),
  ('hp-c-buy', 'star', 'See plans and prices', 'Per-computer cover, rolling monthly', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'business-it-support-ferndown-industrial-estate': [
  ('hp-c-fix', 'briefcase', 'What the plan covers', 'Servers, networks, Microsoft 365 and security', 'FROM &pound;24.38 A PC', '#s1'),
  ('hp-c-care', 'wrench', 'Switching IT provider?', 'Free health check, then a fixed monthly quote', 'NO LOCK-IN', '#s2'),
  ('hp-c-biz', 'star', 'Business plans and prices', 'Simple per-PC pricing, rolling monthly', 'CANCEL ANYTIME', '/business-it-support-plans/'),
  ('hp-c-buy', 'mail', 'Microsoft 365 and email', 'Mailboxes, Teams and security, per user', '&pound;4.85 A USER', '/microsoft-365-support/'),
 ],
 'business-it-support-new-forest': [
  ('hp-c-fix', 'briefcase', 'What we look after', 'Servers, Microsoft 365, security and backups', 'FULLY MANAGED', '#s2'),
  ('hp-c-care', 'user', 'Switching provider?', 'Five clear steps, with the handover handled', 'NO LOCK-IN', '#s3'),
  ('hp-c-biz', 'shield', 'Hit by an attack?', 'Practical response, recovery and hardening', 'EMERGENCY HELP', '/business-hacked-emergency-help/'),
  ('hp-c-buy', 'star', 'Plans and prices', 'Managed IT from &pound;24.38 a month per computer', 'ROLLING MONTHLY', '/business-it-support-plans/'),
 ],
 'business-wifi-installation': [
  ('hp-c-fix', 'wifi', 'Business WiFi vs mesh', 'Six real differences, from VLANs to roaming', 'WHY NOT A THREE-PACK', '#s1'),
  ('hp-c-care', 'alert', 'The licence trap', 'What stops working if you never pay again', 'PLATFORM BY PLATFORM', '#s3'),
  ('hp-c-biz', 'gauge', 'What it really costs', 'Why the cabling costs more than the access points', 'THE SUMS, IN PUBLIC', '#s4'),
  ('hp-c-buy', 'briefcase', 'Get a straight quote', 'Survey first, cabling costed separately', 'DORSET PREMISES', '/contact/'),
 ],
 'cctv-in-detached-garage-connect-to-house': [
  ('hp-c-fix', 'wifi', 'No trench? Use a bridge', 'Two small units act like a cable across the garden', 'OUR SPECIALISM', '#s3'),
  ('hp-c-care', 'wrench', 'Buried armoured cable', 'The most reliable link: picture and power in one', 'GOLD STANDARD', '#s2'),
  ('hp-c-biz', 'alert', 'Tried powerline?', 'Why plug-in adapters often fail to a garage', 'CHEAPER OPTIONS', '#s4'),
  ('hp-c-buy', 'home', 'Book a site visit', 'We look at the run and fit the right link', 'PRICED BEFORE WE COME', '/contact/'),
 ],
 'cctv-not-working-after-changing-broadband': [
  ('hp-c-fix', 'wifi', 'Offline since new router?', 'The four settings that went with the old one', 'START HERE', '#s1'),
  ('hp-c-care', 'monitor', 'Cloud app or old DVR?', 'They fail differently and need different fixes', 'CHECK YOUR SYSTEM', '#s3'),
  ('hp-c-biz', 'wifi', 'Added mesh WiFi too?', 'Double NAT can block viewing when you&rsquo;re out', 'HIDDEN CULPRIT', '#s4'),
  ('hp-c-buy', 'shield', 'Don&rsquo;t reopen old ports', 'Why an internet-facing old DVR is a real risk', 'SECURITY FIRST', '#s5'),
 ],
 'cerbo-gx-gps': [
  ('hp-c-fix', 'alert', 'USB GPS not showing up?', 'Check the port and the baud rate first', 'THE USB GOTCHA', '#s2'),
  ('hp-c-care', 'wifi', 'Boat with NMEA 2000?', 'Use the position your network already carries', 'NO NEW GPS', '#s3'),
  ('hp-c-biz', 'clock', 'Set the log interval', '1 minute, not the 15-minute default', 'ONE SETTING', '#s5'),
  ('hp-c-buy', 'gauge', 'Route-tracker dashboard', 'A live map and a permanent route archive', 'BEYOND VRM', '#s7'),
 ],
 'cerbo-gx-mqtt-dashboard': [
  ('hp-c-fix', 'cloud', 'Local or cloud broker?', 'FlashMQ on the GX, or the VRM cloud broker', 'CHOOSE FIRST', '#s2'),
  ('hp-c-care', 'clock', 'Why REST isn&rsquo;t realtime', 'Polling VRM just returns logged, older numbers', 'THE REST TRAP', '#s3'),
  ('hp-c-biz', 'gauge', 'See ours running live', 'Our off-grid van, streaming right now', 'LIVE DEMO', '#s5'),
  ('hp-c-buy', 'briefcase', 'How we price it', 'What moves the number; every build quoted', 'GET A QUOTE', '#s6'),
 ],
 'computer-help-for-elderly-parents': [
  ('hp-c-fix', 'calendar', 'How it works for you', 'Set it all up by phone, from wherever you live', 'FROM ANYWHERE', '#s3'),
  ('hp-c-care', 'shield', 'Why parents feel safe', 'We always phone first; they watch everything', 'TRUST AND SAFETY', '#s4'),
  ('hp-c-biz', 'home', 'See home plans', '&pound;18.25 a month per computer, no tie-in', 'CANCEL ANYTIME', '/home-it-support-plans/'),
  ('hp-c-buy', 'alert', 'Worried about scams?', 'What to do if a parent is being targeted', 'FAMILY GUIDE', '/worried-about-a-parent-being-scammed/'),
 ],
 'computer-help-for-the-elderly-bournemouth': [
  ('hp-c-fix', 'home', 'Book a home visit', 'Patient help at home, priced before we come', 'SAME FACES EACH TIME', '/contact/'),
  ('hp-c-care', 'shield', 'Worried about scams?', 'Kind, plain-English protection and one golden rule', 'STAYING SAFE', '#s2'),
  ('hp-c-biz', 'book', '1-to-1 lessons at home', 'Learn only what you want, at your own pace', 'LARGE-PRINT NOTES', '#s3'),
  ('hp-c-buy', 'user', 'Helping a parent?', 'We keep you in the loop from a distance', 'FOR FAMILIES', '#s4'),
 ],
 'computer-lessons-for-seniors-bournemouth': [
  ('hp-c-fix', 'calendar', 'Group classes in Kinson', 'Relaxed classes at the Kinson Community Centre', 'CALL FOR TIMETABLE', '#s1'),
  ('hp-c-care', 'user', 'One-to-one lessons', 'At the centre, or online on your own screen', 'YOUR PACE', '#s2'),
  ('hp-c-biz', 'book', 'What you&rsquo;ll learn', 'Email, photos, video calls and spotting scams', 'NO JARGON', '#s3'),
  ('hp-c-buy', 'phone', 'How to get started', 'Four easy steps, starting with one phone call', 'START HERE', '#s4'),
 ],
 'computer-repair-kinson': [
  ('hp-c-fix', 'wrench', 'Book a collection', 'We collect from your door, diagnose, then quote', 'PRICE AGREED FIRST', '/book-a-collection/'),
  ('hp-c-care', 'monitor', 'Software trouble?', 'Slow PC, pop-ups, email: often fixed remotely', 'OFTEN SAME DAY', '/remote-support/'),
  ('hp-c-biz', 'gauge', 'Repair or replace?', 'An honest opinion before you spend', 'HONEST ADVICE', '#s5'),
  ('hp-c-buy', 'star', 'What it costs', 'Quoted before any chargeable work', 'NO SURPRISES', '#s6'),
 ],
 'computer-repair-westbourne': [
  ('hp-c-fix', 'monitor', 'Fix it remotely', 'Software problems sorted while you watch', 'USUALLY SAME DAY', '/remote-support/'),
  ('hp-c-care', 'calendar', 'Book a free collection', 'Hands-on repairs collected from your door', 'NO FIX, NO FEE', '/book-a-collection/'),
  ('hp-c-biz', 'wrench', 'Worth repairing?', 'An honest view before you spend anything', 'HONEST ADVICE', '/worth-repairing-old-laptop/'),
  ('hp-c-buy', 'user', 'Help for an older relative', 'Patient, jargon-free help, arranged with family', 'CALM AND SIMPLE', '/computer-help-for-the-elderly-bournemouth/'),
 ],
 'computer-support-gift-for-parents': [
  ('hp-c-fix', 'calendar', 'How it works', 'Arrange it from anywhere, we introduce ourselves', 'FROM ANYWHERE', '#s2'),
  ('hp-c-care', 'star', 'What they actually get', 'Friendly help that always phones first', 'SAME FACES', '#s3'),
  ('hp-c-biz', 'home', 'See the home plan', '&pound;18.25 a month per computer, cancel anytime', 'ROLLING MONTHLY', '/home-it-support-plans/'),
  ('hp-c-buy', 'laptop', 'Giving a laptop too?', 'Set up ready to use before you wrap it', 'READY TO USE', '/laptop-set-up-for-elderly-parent/'),
 ],
 'customise-victron-vrm-dashboard': [
  ('hp-c-fix', 'alert', 'Can I move the tiles?', 'Short answer: no, the main layout is fixed', 'THE SHORT ANSWER', '#s1'),
  ('hp-c-care', 'gauge', 'What you can change', 'Advanced tab widgets, up to 6 parameters each', 'STOCK VRM', '#s2'),
  ('hp-c-biz', 'wrench', 'Build it yourself', 'Node-RED on the GX, or the official VRM API', 'DIY ROUTE', '#s4'),
  ('hp-c-buy', 'star', 'See a live custom one', 'Our van in two dashboard styles, streaming now', 'LIVE DEMO', '#s6'),
 ],
 'dell-business-support-dorset': [
  ('hp-c-fix', 'gauge', 'What the plan covers', 'Monitoring, patching, health checks, backups', 'PROACTIVE', '#s1'),
  ('hp-c-care', 'phone', 'Remote first, on site too', 'Same-day response from the same small team', 'HOW HELP REACHES YOU', '#s2'),
  ('hp-c-biz', 'laptop', 'Refresh tired machines', 'Refurbished Latitudes and OptiPlexes, phased in', 'FROM &pound;510', '/dell-hardware/'),
  ('hp-c-buy', 'briefcase', 'Per-computer pricing', 'Business plans, no VAT added, no long tie-in', 'FROM &pound;24.38', '#s5'),
 ],
 'dell-caps-lock-light-blinking-wont-turn-on': [
  ('hp-c-fix', 'power', 'Try a full power drain', 'Charger out, hold the power button for 30 seconds', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-care', 'wrench', 'Memory or motherboard?', 'Test one RAM stick at a time to find the fault', 'IF CONFIDENT', '#s3'),
  ('hp-c-biz', 'calendar', 'Book a free collection', 'Diagnosis first, price agreed before any repair', 'NO FIX, NO FEE', '/book-a-collection/'),
  ('hp-c-buy', 'laptop', 'Not worth repairing?', 'Refurbished business-grade Dells, ready to go', 'REFURBISHED DELLS', '/dell-hardware/'),
 ],
 'dell-docking-station-not-working': [
  ('hp-c-fix', 'power', 'Dock completely dead?', 'Prove the socket and adapter, then watch the light', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-care', 'gauge', 'Laptop won&rsquo;t charge?', 'Often the adapter wattage, not a fault', '130W OR 180W?', '#s3'),
  ('hp-c-biz', 'monitor', 'Monitors not detected?', 'Cables, firmware or a bandwidth ceiling', 'THREE SUSPECTS', '#s4'),
  ('hp-c-buy', 'wrench', 'Have us sort it remotely', 'Firmware, BIOS dock settings and drivers, safely', 'FROM &pound;20', '/dell-remote-support/'),
 ],
 'dell-g15-overheating': [
  ('hp-c-biz', 'wrench', 'Five free fixes first', 'Surface, vents, Game Shift, BIOS, thermal profile', 'COSTS NOTHING', '#s1'),
  ('hp-c-buy', 'calendar', 'Book a free collection', 'Diagnosis and a quote before any work starts', 'QUOTE FIRST', '/book-a-collection/'),
 ],
 'dell-inspiron-15-3000-windows-11': [
  ('hp-c-biz', 'gauge', 'Check your processor', 'The generation decides it, not the model name', '30-SECOND CHECK', '#s2'),
  ('hp-c-buy', 'laptop', 'Failed the check?', 'Three honest options, from ESU to a Latitude', 'NOT SCRAP', '#s5'),
 ],
 'dell-inspiron-15-5000-windows-11': [
  ('hp-c-biz', 'book', 'Model-by-model table', 'Every Inspiron 15 5000 from the 5547 to the 5515', 'YES, NO OR DEPENDS', '#s3'),
  ('hp-c-buy', 'laptop', 'Yours can&rsquo;t upgrade?', 'Refurbished Latitudes from &pound;510, data moved across', 'WINDOWS 11 READY', '/dell-hardware/'),
 ],
 'dell-inspiron-desktop-windows-11': [
  ('hp-c-biz', 'monitor', 'Can your tower upgrade?', 'Model by model: 3670 onwards yes, 3668 no', 'THE VERDICT', '#s1'),
  ('hp-c-buy', 'star', 'Replace it like for like', 'Refurbished OptiPlex with Windows 11 set up', 'FROM &pound;545', '/dell-hardware/?kind=desktop'),
 ],
 'dell-inspiron-repair-bournemouth': [
  ('hp-c-fix', 'star', 'Worth repairing?', 'The fault, Windows 11 and age decide it', 'STRAIGHT ANSWER', '#s1'),
  ('hp-c-care', 'gauge', 'Slow Inspiron?', 'An SSD swap usually makes it feel new', 'BEST-VALUE UPGRADE', '#s3'),
  ('hp-c-biz', 'shield', 'Can&rsquo;t run Windows 11?', 'Three honest options, including refurb from &pound;510', 'WINDOWS 10 HAS ENDED', '#s4'),
  ('hp-c-buy', 'home', 'Free collection and quote', 'Diagnosed first, quoted before any work', 'NO SHOP NEEDED', '/book-a-collection/'),
 ],
 'dell-killer-wifi-problems': [
  ('hp-c-biz', 'monitor', 'Is it the Killer card?', 'Check Device Manager in 20 seconds', 'CHECK THIS FIRST', '#s1'),
  ('hp-c-buy', 'wifi', 'Switch to the Intel driver', 'The more permanent answer to the drops', 'MORE PERMANENT', '#s4'),
 ],
 'dell-laptop-battery-replacement-dorset': [
  ('hp-c-fix', 'alert', 'Swollen battery?', 'Stop using it now, and what to do next', 'SAFETY FIRST', '#s1'),
  ('hp-c-care', 'power', 'Plugged in, not charging?', 'It isn&rsquo;t always the battery', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-biz', 'calendar', 'Book a free collection', 'Correct-fit Dell battery, 12-month warranty', 'NO FIX, NO FEE', '/book-a-collection/'),
  ('hp-c-buy', 'laptop', 'Old Dell past saving?', 'A refurbished Latitude may be better value', 'FROM &pound;510', '/refurbished-dell-laptops-bournemouth/'),
 ],
 'dell-laptop-hinge-repair': [
  ('hp-c-fix', 'wrench', 'Free checks first', 'Screws, how you open it, and what has failed', 'BEFORE YOU BOOK', '#s1'),
  ('hp-c-care', 'alert', 'Why waiting costs more', 'A loose hinge chews through the screen cable', 'DON&rsquo;T WAIT', '#s3'),
  ('hp-c-biz', 'laptop', 'Fix it, or replace it?', 'Or a refurbished Latitude from &pound;510', 'HONEST VERDICT', '#s5'),
  ('hp-c-buy', 'home', 'Free collection, quote first', 'Diagnosed, then a fixed price before any work', 'NO POSTING IT AWAY', '/book-a-collection/'),
 ],
 'dell-laptop-repair-bournemouth': [
  ('hp-c-fix', 'wrench', 'Book a collection', 'We collect, diagnose and quote before any work', 'DIAGNOSIS FIRST', '/book-a-collection/'),
  ('hp-c-care', 'gauge', 'Repair or replace?', 'Our honest rule of thumb before you spend', 'HONEST ADVICE', '#s4'),
  ('hp-c-biz', 'power', 'Dell won&rsquo;t turn on?', 'Read the caps-lock blink code before you call', 'BEFORE YOU CALL', '/dell-caps-lock-light-blinking-wont-turn-on/'),
  ('hp-c-buy', 'laptop', 'Refurbished Dell laptops', 'Tested, with a new SSD, when repair isn&rsquo;t worth it', 'REPLACE INSTEAD?', '/refurbished-dell-laptops-bournemouth/'),
 ],
 'dell-laptop-repair-poole': [
  ('hp-c-fix', 'wrench', 'Book a collection', 'We collect across Poole, diagnose, then quote', 'DIAGNOSIS FIRST', '/book-a-collection/'),
  ('hp-c-care', 'gauge', 'Repair or replace?', 'Our honest rule of thumb before you spend', 'HONEST ADVICE', '#s4'),
  ('hp-c-biz', 'power', 'Dell won&rsquo;t turn on?', 'Read the caps-lock blink code before you call', 'BEFORE YOU CALL', '/dell-caps-lock-light-blinking-wont-turn-on/'),
  ('hp-c-buy', 'laptop', 'Refurbished Dell laptops', 'Tested, with a new SSD, when repair isn&rsquo;t worth it', 'REPLACE INSTEAD?', '/refurbished-dell-laptops-bournemouth/'),
 ],
 'dell-laptop-servicing-bournemouth': [
  ('hp-c-fix', 'gauge', 'What a service includes', 'Clean-out, fresh paste, SSD, RAM and battery checks', 'FULL HEALTH CHECK', '#s1'),
  ('hp-c-care', 'star', 'Service or replace?', 'The honest answer for an older Dell', 'HONEST ADVICE', '#s4'),
  ('hp-c-biz', 'book', 'What you can do yourself', 'Safe DIY steps, and what to leave to us', 'DIY OR TECHIES?', '#s3'),
  ('hp-c-buy', 'wrench', 'Book a collection', 'We collect, service and return your Dell', 'COLLECTION SERVICE', '/book-a-collection/'),
 ],
 'dell-latitude-3510-refurbished-worth-it': [
  ('hp-c-fix', 'star', 'Worth it or false economy?', 'Our honest verdict on the 3510', 'THE VERDICT', '#s1'),
  ('hp-c-care', 'alert', 'Where it falls short', 'Plastic build, basic screen, modest graphics', 'EYES OPEN', '#s3'),
  ('hp-c-biz', 'laptop', 'Our tested refurbished Dell', 'New Samsung Pro SSD, securely wiped and graded', 'FROM &pound;510', '#s5'),
  ('hp-c-buy', 'briefcase', 'See Dells in stock', 'Browse new and refurbished Dell laptops', 'STOCK PICKER', '/dell-hardware/'),
 ],
 'dell-latitude-5000-guide': [
  ('hp-c-fix', 'laptop', 'See 5000-series stock', 'Tested, graded and set up, with your data moved', 'FROM &pound;535', '/refurbished-dell-latitude-5000/'),
  ('hp-c-care', 'star', '5420 or 5430?', 'The head-to-head: best value or the big jump', 'COMPARISON', '/dell-latitude-5420-vs-5430-which-to-buy/'),
  ('hp-c-biz', 'book', 'What a refurb includes', 'New SSD, Windows 11 and setup in the price', 'WHAT YOU GET', '#s6'),
  ('hp-c-buy', 'monitor', 'Browse all Dell stock', 'Pick a laptop or desktop from our current stock', 'DELL SINCE 2001', '/dell-hardware/'),
 ],
 'dell-latitude-5300-refurbished-worth-it': [
  ('hp-c-fix', 'star', 'Is it still worth it?', 'Our honest 2026 verdict on the 5300', 'THE VERDICT', '#s1'),
  ('hp-c-care', 'alert', 'Check before you buy', 'Battery, drive, hinges, screen and licence', 'FIVE CHECKS', '#s3'),
  ('hp-c-biz', 'laptop', 'Our tested 5300', 'New Samsung Pro SSD, wiped, tested and graded', 'FROM &pound;510', '#s4'),
  ('hp-c-buy', 'briefcase', 'See Dells in stock', 'Browse new and refurbished Dell laptops', 'STOCK PICKER', '/dell-hardware/'),
 ],
 'dell-latitude-5410-worth-it-2026': [
  ('hp-c-fix', 'star', 'Is the 5410 worth it?', 'Yes, at the right price and in good condition', 'THE VERDICT', '#s1'),
  ('hp-c-care', 'alert', 'Buying a used one?', 'Battery, drive, warranty and locks to check', 'BEFORE YOU BUY', '#s3'),
  ('hp-c-biz', 'laptop', 'Refurbished 5000-series', 'Newer tested Latitudes with a new SSD fitted', 'FROM &pound;535', '/refurbished-dell-latitude-5000/'),
  ('hp-c-buy', 'monitor', 'See Latitudes in stock', 'Pick a tested Latitude by budget and use', 'STOCK PICKER', '/dell-hardware/'),
 ],
 'dell-latitude-5420-vs-5430-which-to-buy': [
  ('hp-c-fix', 'laptop', 'See both in stock', 'Tested 5420s and 5430s, each with a new SSD', 'STOCK PICKER', '/dell-hardware/'),
  ('hp-c-care', 'star', 'The quick verdict', 'Save with the 5420, future-proof with the 5430', 'READ THIS FIRST', '#s1'),
  ('hp-c-biz', 'briefcase', 'Which suits your work?', 'Office and M365, or heavy multitasking', 'PICK BY USE', '#s3'),
  ('hp-c-buy', 'laptop', 'Refurbished Latitude 5000s', 'The whole 14-inch range, tested and graded', 'NEW SSD FITTED', '/refurbished-dell-latitude-5000/'),
 ],
 'dell-latitude-7000-guide': [
  ('hp-c-fix', 'alert', 'The soldered-RAM rule', 'Buy the memory you&rsquo;ll need for life', 'READ BEFORE YOU BUY', '#s2'),
  ('hp-c-care', 'star', 'Is a 7000 right for you?', 'Our verdict: 7000 or 5000, refurbished or new', 'THE VERDICT', '#s6'),
  ('hp-c-biz', 'laptop', 'Refurbished 7000s', 'Tested, wiped, new Samsung SSD fitted', 'GET A QUOTE', '/refurbished-dell-latitude-7000/'),
  ('hp-c-buy', 'briefcase', 'See Dells in stock', 'Browse our new and refurbished Dell laptops', 'STOCK PICKER', '/dell-hardware/'),
 ],
 'dell-latitude-e5540-upgrade': [
  ('hp-c-fix', 'laptop', 'Pick your successor', 'See how much faster a newer Latitude is', 'GET A QUOTE', '/dell-hardware/'),
  ('hp-c-care', 'star', 'Refurbished Latitude 5000', 'The sturdier business series, set up for you', '5000 SERIES', '/refurbished-dell-latitude-5000/'),
  ('hp-c-biz', 'wrench', 'Upgrade or replace?', 'Offline use: an SSD may do. Online: replace it', 'HONEST TRIAGE', '#s4'),
  ('hp-c-buy', 'shield', 'Stay on Windows 10 a while?', 'Extended updates run to 12 October 2027', 'ESU OR UPGRADE', '/windows-10-esu-or-upgrade-your-dell/'),
 ],
 'dell-latitude-e5550-upgrade': [
  ('hp-c-fix', 'alert', 'Why it&rsquo;s time to move on', 'An old drive, tired memory and no Windows 11', 'THE HONEST BIT', '#s2'),
  ('hp-c-care', 'laptop', 'The natural successors', 'Latitude 3520 or 5520: same size, far newer', '15.6-INCH', '#s5'),
  ('hp-c-biz', 'star', 'Pick one online', 'Check stock, compare speed and get a quote', 'STOCK PICKER', '/dell-hardware/'),
  ('hp-c-buy', 'wrench', 'Still worth an SSD?', 'Only for offline or very light use', 'HONEST TRIAGE', '#s4'),
 ],
 'dell-latitude-series-explained-3000-5000-7000': [
  ('hp-c-fix', 'star', 'Which one should I buy?', 'For most people it&rsquo;s the 5000. Here&rsquo;s why', 'THE SHORT ANSWER', '#s1'),
  ('hp-c-care', 'book', 'Match a tier to your use', 'Tight budget, all-rounder or ultralight', 'HOW TO DECIDE', '#s5'),
  ('hp-c-biz', 'laptop', 'Refurbished Latitude 5000s', 'Tested, new SSD fitted, Windows set up for you', 'FROM &pound;535', '/refurbished-dell-latitude-5000/'),
  ('hp-c-buy', 'monitor', 'See Latitudes in stock', 'Pick a tested 3000, 5000 or 7000 by budget', 'STOCK PICKER', '/dell-hardware/'),
 ],
 'dell-monitor-dock-support-dorset': [
  ('hp-c-fix', 'monitor', 'Monitor says no signal?', 'Usually the cable or input, not the screen', 'CHECK THIS FIRST', '#s3'),
  ('hp-c-care', 'laptop', 'Dock playing up?', 'Screens, charging and Ethernet faults decoded', 'WD19, WD22 AND MORE', '#s4'),
  ('hp-c-biz', 'star', 'Worth repairing?', 'The honest answer on monitor repair', 'THE HONEST BIT', '#s2'),
  ('hp-c-buy', 'briefcase', 'Replacing the PC too?', 'Refurbished Latitudes and OptiPlexes, set up', 'FROM &pound;510', '/dell-hardware/'),
 ],
 'dell-optiplex-7020-upgrade': [
  ('hp-c-fix', 'alert', 'Can it run Windows 11?', 'Why the 7020 can&rsquo;t, and what that means', 'THE BIG ONE', '#s2'),
  ('hp-c-care', 'wrench', 'Upgrade or replace?', 'Honest triage: when an SSD still makes sense', 'HONEST TRIAGE', '#s4'),
  ('hp-c-biz', 'star', 'The natural successor', 'Refurbished OptiPlex 3080 or 3090, set up for you', 'GUIDE &pound;545', '#s5'),
  ('hp-c-buy', 'monitor', 'Pick your successor', 'Check stock and compare the speed jump', 'STOCK PICKER', '/dell-hardware/?kind=desktop'),
 ],
 'dell-optiplex-790-upgrade': [
  ('hp-c-fix', 'alert', 'Can it run Windows 11?', 'Why the 790 can&rsquo;t, and what that means', 'THE BIG ONE', '#s2'),
  ('hp-c-care', 'wrench', 'Upgrade or replace?', 'Honest triage: when an SSD still makes sense', 'HONEST TRIAGE', '#s4'),
  ('hp-c-biz', 'star', 'The 790&rsquo;s natural heir', 'A refurbished OptiPlex 3080, set up for you', 'GUIDE &pound;545', '#s5'),
  ('hp-c-buy', 'monitor', 'Pick your successor', 'Check stock and compare the speed jump', 'STOCK PICKER', '/dell-hardware/?kind=desktop'),
 ],
 'dell-optiplex-9020-upgrade': [
  ('hp-c-fix', 'alert', 'Can it run Windows 11?', 'Why the 9020 can&rsquo;t, and what that means', 'THE BIG ONE', '#s2'),
  ('hp-c-care', 'wrench', 'Upgrade or replace?', 'Honest triage: when an SSD still makes sense', 'HONEST TRIAGE', '#s4'),
  ('hp-c-biz', 'star', 'The natural successor', 'Refurbished OptiPlex 3090 or 5090, set up for you', 'GUIDE &pound;550', '#s5'),
  ('hp-c-buy', 'monitor', 'Pick your successor', 'Check stock and compare the speed jump', 'STOCK PICKER', '/dell-hardware/?kind=desktop'),
 ],
 'dell-optiplex-990-upgrade': [
  ('hp-c-fix', 'alert', 'Can it run Windows 11?', 'Why the 990 can&rsquo;t, and what that means', 'THE BIG ONE', '#s2'),
  ('hp-c-care', 'wrench', 'Upgrade or replace?', 'Honest triage: when an SSD still makes sense', 'HONEST TRIAGE', '#s4'),
  ('hp-c-biz', 'star', 'The natural successor', 'Refurbished OptiPlex 3080 or 5080, set up for you', 'GUIDE &pound;545', '#s5'),
  ('hp-c-buy', 'monitor', 'Pick your successor', 'Check stock and compare the speed jump', 'STOCK PICKER', '/dell-hardware/?kind=desktop'),
 ],
 'dell-optiplex-fan-error-f1-fix': [
  ('hp-c-fix', 'wrench', 'Reseat and clean the fan', 'The safe fixes, least invasive first', 'START HERE', '#s2'),
  ('hp-c-care', 'alert', 'Pressing F1 every day?', 'Why that hides a fault that can cook the PC', 'DON&rsquo;T IGNORE IT', '#s3'),
  ('hp-c-biz', 'calendar', 'Book a free collection', 'Correct Dell fan fitted, error cleared, heat-tested', 'NO FIX, NO FEE', '/book-a-collection/'),
  ('hp-c-buy', 'monitor', 'Old on several fronts?', 'A refurbished OptiPlex may be the better buy', 'NEW SSD FITTED', '/refurbished-dell-desktops-dorset/'),
 ],
 'dell-optiplex-micro-sff-tower-which-to-buy': [
  ('hp-c-fix', 'monitor', 'See OptiPlex in stock', 'Pick a tested desktop by budget and size', 'STOCK PICKER', '/dell-hardware/?kind=desktop'),
  ('hp-c-care', 'star', 'The quick verdict', 'Why most offices should buy the SFF', 'READ THIS FIRST', '#s1'),
  ('hp-c-biz', 'book', 'Match the body to the job', 'Three questions: where it sits and what you add', '3 QUESTIONS', '#s5'),
  ('hp-c-buy', 'monitor', 'Refurbished Dell desktops', 'New SSD, licensed Windows, delivered and set up', 'SET UP FOR YOU', '/refurbished-dell-desktops-dorset/'),
 ],
 'dell-optiplex-repair-poole': [
  ('hp-c-fix', 'alert', 'What your symptom means', 'No power, amber light, fan error, no picture', 'PLAIN-ENGLISH TRIAGE', '#s1'),
  ('hp-c-care', 'calendar', 'Book a free collection', 'Collected across Poole, fixed price first', 'NO FIX, NO FEE', '/book-a-collection/'),
  ('hp-c-biz', 'wrench', 'Fan Error or F1 at boot?', 'Usually a dusty or failing fan', 'OPTIPLEX GUIDE', '/dell-optiplex-fan-error-f1-fix/'),
  ('hp-c-buy', 'monitor', 'Time to replace it?', 'Refurbished OptiPlex with a new Samsung SSD', 'FROM &pound;545', '/dell-hardware/?kind=desktop'),
 ],
 'dell-optiplex-vs-inspiron-desktop': [
  ('hp-c-fix', 'book', 'What&rsquo;s actually different?', 'Business-grade OptiPlex vs consumer Inspiron', 'THE SHORT ANSWER', '#s1'),
  ('hp-c-care', 'star', 'Refurb OptiPlex or new?', 'Why a refurb usually beats a bargain Inspiron', 'OUR VERDICT', '#s4'),
  ('hp-c-biz', 'monitor', 'Refurbished Dell desktops', 'Tested, wiped, new SSD and Windows set up', 'WHAT YOU GET', '/refurbished-dell-desktops-dorset/'),
  ('hp-c-buy', 'home', 'See desktops in stock', 'Pick a tested OptiPlex by budget and use', 'FROM &pound;545', '/dell-hardware/?kind=desktop'),
 ],
 'dell-out-of-warranty-repair': [
  ('hp-c-fix', 'wrench', 'Book a collection', 'Diagnosis first, price approved before any work', 'COLLECTION REPAIR', '/book-a-collection/'),
  ('hp-c-care', 'laptop', 'What we repair', 'Screens, batteries, ports, fans, no-boot faults', 'LATITUDE TO INSPIRON', '#s2'),
  ('hp-c-biz', 'star', 'Repair or replace?', 'The honest maths on an older Dell', 'HONEST ADVICE', '#s4'),
  ('hp-c-buy', 'monitor', 'A refurbished Dell instead', 'When a repair isn&rsquo;t worth the money', 'FROM &pound;510', '/dell-hardware/'),
 ],
 'dell-precision-vs-latitude': [
  ('hp-c-fix', 'star', 'The short answer', 'Why most people only need a Latitude', 'THE VERDICT', '#s1'),
  ('hp-c-care', 'gauge', 'Signs you need a Precision', 'CAD, 3D, 4K video: the honest test', 'FIVE SIGNS', '#s3'),
  ('hp-c-biz', 'laptop', 'See Dells in stock', 'Browse new and refurbished Dell laptops', 'STOCK PICKER', '/dell-hardware/'),
  ('hp-c-buy', 'briefcase', 'Refurbished Dell laptops', 'Tested, wiped and fitted with a new SSD', 'BOURNEMOUTH', '/refurbished-dell-laptops-bournemouth/'),
 ],
 'dell-precision-workstation-repair-support-dorset': [
  ('hp-c-fix', 'laptop', 'Precision laptop faults', 'Heat, shutdowns, swollen battery, adapter errors', 'SYMPTOM BY SYMPTOM', '#s2'),
  ('hp-c-care', 'monitor', 'Tower won&rsquo;t POST?', 'Blink codes and ECC memory rules explained', 'AFTER A RAM UPGRADE', '#s3'),
  ('hp-c-biz', 'bug', 'CAD app crashing?', 'Often the graphics driver, not the workstation', 'CHECK THE DRIVER', '#s4'),
  ('hp-c-buy', 'calendar', 'Book a free collection', 'Diagnosis first, and a quote before any work', 'QUOTE FIRST', '/book-a-collection/'),
 ],
 'dell-remote-support': [
  ('hp-c-fix', 'shield', 'How a session works', 'We phone first, and you watch every click', 'SAFE AND SIMPLE', '#s1'),
  ('hp-c-care', 'laptop', 'What we fix remotely', 'Windows, email, drivers, slowness and setup', 'SOFTWARE FAULTS', '#s2'),
  ('hp-c-biz', 'wrench', 'Screen, battery or hinge?', 'Hands-on repairs by collection, diagnosis first', 'COLLECTION REPAIR', '/book-a-collection/'),
  ('hp-c-buy', 'phone', 'Start a remote fix', 'One-off help, price agreed before we start', 'FROM &pound;20', '/remote-support/'),
 ],
 'dell-support-bournemouth': [
  ('hp-c-fix', 'monitor', 'Fix it remotely', 'If your Dell still reaches Windows, no trip needed', 'WE PHONE FIRST', '/dell-remote-support/'),
  ('hp-c-care', 'wrench', 'Hardware fault?', 'Free local collection, diagnosis before any repair', 'NO FIX, NO FEE', '/book-a-collection/'),
  ('hp-c-biz', 'calendar', 'Dell support plans', 'Home from &pound;18.25 a month per computer', 'HOME AND BUSINESS', '/dell-support-plans/'),
  ('hp-c-buy', 'laptop', 'Time to replace it?', 'Refurbished business-grade Dell, tested and set up', 'READY TO GO', '/dell-hardware/'),
 ],
 'dell-support-plans': [
  ('hp-c-fix', 'home', 'Home plan', 'Proactive care for a household Dell or two', 'FROM &pound;18.25 A MONTH', '/home-it-support-plans/'),
  ('hp-c-care', 'briefcase', 'Business plan', 'Several Dells and someone dependable on call', 'FROM &pound;24.38 A MONTH', '/business-it-support-plans/'),
  ('hp-c-biz', 'gauge', 'What&rsquo;s included', 'Health checks, remote help, priority and a report', 'WHAT YOU GET', '#s1'),
  ('hp-c-buy', 'shield', 'Not a Dell warranty', 'Works whether or not Dell&rsquo;s own cover is left', 'THE HONEST BIT', '#s2'),
 ],
 'dell-support-poole': [
  ('hp-c-fix', 'monitor', 'Fixed remotely today', 'Software, email and Windows trouble on a Dell', 'REMOTE FIRST', '#s1'),
  ('hp-c-care', 'wrench', 'Hardware fault?', 'Free collection across Poole, diagnosis first', 'FREE COLLECTION', '/book-a-collection/'),
  ('hp-c-biz', 'shield', 'Dell support plans', 'Home cover &pound;18.25 a month per computer', 'PROACTIVE CARE', '/dell-support-plans/'),
  ('hp-c-buy', 'laptop', 'Time to replace?', 'Refurbished business-grade Dell, set up for you', 'STOCK PICKER', '/dell-hardware/'),
 ],
 'dell-this-pc-cant-run-windows-11': [
  ('hp-c-biz', 'shield', 'Just switched off?', 'TPM, Secure Boot and UEFI are settings, not faults', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-buy', 'laptop', 'Too old to upgrade?', 'A Windows 11-ready refurbished Dell instead', 'FROM &pound;510', '#s5'),
 ],
 'dell-vostro-repair-support-dorset': [
  ('hp-c-fix', 'wrench', 'Common Vostro faults', 'Lifting touchpad, charging, hinges, Wi-Fi drops', 'WHAT WE FIX', '#s3'),
  ('hp-c-care', 'gauge', 'Slow Vostro? Don&rsquo;t bin it', 'An SSD and more memory, files moved across', 'BEST-VALUE JOB', '#s4'),
  ('hp-c-biz', 'briefcase', 'Keep or replace the fleet?', 'Honest triage before the Windows 10 deadline', 'FLEET TRIAGE', '#s6'),
  ('hp-c-buy', 'laptop', 'Replacing some?', 'Refurbished Latitudes from &pound;510, OptiPlex from &pound;545', 'IN STOCK NOW', '/dell-hardware/'),
 ],
 'dell-xps-repair-bournemouth': [
  ('hp-c-fix', 'alert', 'Touchpad lifting?', 'A swollen battery: stop charging, get it replaced', 'SAFETY ISSUE', '#s3'),
  ('hp-c-care', 'wrench', 'What can be upgraded', 'SSD usually yes; XPS 13 memory is soldered', 'CHECK BEFORE BUYING', '#s4'),
  ('hp-c-biz', 'star', 'Worth repairing?', 'Honest keep-or-fix advice on a premium machine', 'DIAGNOSIS FIRST', '#s2'),
  ('hp-c-buy', 'home', 'Free doorstep collection', 'No posting a premium laptop to a mail-in shop', 'WRITTEN QUOTE FIRST', '/book-a-collection/'),
 ],
 'dell-xps-swollen-battery': [
  ('hp-c-biz', 'alert', 'What to do right now', 'Power off, unplug, and stop using it', 'DO THIS NOW', '#s1'),
  ('hp-c-buy', 'laptop', 'Book a free collection', 'Diagnosis first, written quote before any work', 'SAFE REPLACEMENT', '/book-a-collection/'),
 ],
 'desktop-pc-used-as-office-server': [
  ('hp-c-fix', 'gauge', 'When a desktop is fine', 'Few users, real backups, someone patching it', 'CHECK YOUR SET-UP', '#s2'),
  ('hp-c-care', 'alert', 'Where it catches you out', 'The 20-device limit, dead drives and reboots', 'KNOW THE LIMITS', '#s3'),
  ('hp-c-biz', 'cloud', 'NAS, cloud or a server?', 'The real alternatives, at honest prices', 'THREE ROUTES', '#s4'),
  ('hp-c-buy', 'shield', 'Staying put for now?', 'Backup, a UPS and out-of-hours updates', 'CHEAP SAFEGUARDS', '#s5'),
 ],
 'embed-victron-vrm-on-website': [
  ('hp-c-fix', 'book', 'Use VRM&rsquo;s free embed', 'Share your site: the official, free iframe', 'FREE AND OFFICIAL', '#s2'),
  ('hp-c-care', 'alert', 'Why the embed breaks', '15-minute updates, fragile tokens, one site each', 'THE HONEST LIMITS', '#s3'),
  ('hp-c-biz', 'star', 'Free embed or custom?', 'Which route suits the page you&rsquo;re building', 'HONEST GUIDANCE', '#s6'),
  ('hp-c-buy', 'home', 'On your own subdomain', 'A live dashboard at your own web address', 'YOUR BRAND', '#s8'),
 ],
 'emergency-dell-repair-bournemouth': [
  ('hp-c-fix', 'power', 'Dell just died?', 'Safe checks for the first five minutes', 'START HERE', '#s1'),
  ('hp-c-care', 'monitor', 'Still powers on?', 'We can often look remotely within the hour', 'SOFTWARE FAULTS', '/dell-remote-support/'),
  ('hp-c-biz', 'calendar', 'Won&rsquo;t power on at all?', 'Free collection, diagnosis before any repair', 'NO FIX, NO FEE', '/book-a-collection/'),
  ('hp-c-buy', 'laptop', 'Need a stopgap Dell?', 'A refurbished Dell to keep your team trading', 'BUSINESS DOWN', '/dell-hardware/'),
 ],
 'emergency-internet': [
  ('hp-c-fix', 'wifi', 'Van or failover router?', 'Often a failover router is the better answer', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-care', 'clock', 'How long you&rsquo;ll be offline', 'Why a Friday fault can run to Tuesday', 'REAL TIMESCALES', '#s3'),
  ('hp-c-biz', 'home', 'What we need from your site', 'Somewhere to park and a clear view of the sky', 'READ BEFORE ENQUIRING', '#s4'),
  ('hp-c-buy', 'alert', 'Broadband down right now?', 'Work through the checklist, in order', 'START HERE', '/broadband-down/'),
 ],
 'employee-left-dont-know-computer-password': [
  ('hp-c-fix', 'user', 'Which account type is it?', 'Local, Microsoft or 365: it decides everything', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-care', 'alert', 'Asking for a BitLocker key?', 'Find the key before you reset or wipe anything', 'DATA AT RISK', '#s3'),
  ('hp-c-biz', 'briefcase', 'The leaver checklist', 'Mailbox, files, phone and shared passwords', 'FULL OFFBOARDING', '#s4'),
  ('hp-c-buy', 'wrench', 'Have us sort it', 'Reset, mailbox handover and tidy access, remotely', 'NO FIX, NO FEE', '#s6'),
 ],
 'event-wifi-dorset': [
  ('hp-c-fix', 'power', 'No power? No problem', 'A solar van that brings its own electricity', 'OFF-GRID', '#s1'),
  ('hp-c-care', 'monitor', 'Live streaming, honestly', 'What one satellite link can and can&rsquo;t carry', 'READ BEFORE BOOKING', '#s2'),
  ('hp-c-biz', 'calendar', 'What we need from the site', 'Somewhere to park and a clear view of the sky', 'CHECK YOUR SITE', '#s5'),
  ('hp-c-buy', 'phone', 'Booking and cost', 'One van, so dates go early: ask first', 'FIRST COME', '#s6'),
 ],
 'excel-onedrive-sync-conflicts': [
  ('hp-c-biz', 'wrench', 'Find the conflict copy', 'Your edits are usually in a second copy nearby', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-buy', 'clock', 'Rescue with Version History', 'Copy cells back or restore an earlier save', 'SAFETY NET', '#s3'),
 ],
 'excel-spreadsheet-rescue': [
  ('hp-c-fix', 'wrench', 'Try Open and Repair first', 'Excel&rsquo;s own free tool, on a copy of the file', 'FREE FIX FIRST', '#s3'),
  ('hp-c-care', 'alert', '#REF! errors everywhere?', 'The five spreadsheet disasters we rescue', 'COMMON FAULTS', '#s2'),
  ('hp-c-biz', 'monitor', 'Rescued while you watch', 'Remote session, and we phone before we connect', 'REMOTE FIRST', '#s4'),
  ('hp-c-buy', 'star', 'What it costs', 'Remote rescue from &pound;20, bigger jobs quoted', 'FROM &pound;20', '#s6'),
 ],
 'files-missing-from-onedrive': [
  ('hp-c-biz', 'user', 'Wrong Microsoft account?', 'Each Microsoft account has its own OneDrive', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-buy', 'clock', 'Check the recycle bin', 'Restore them before the 30-day clock runs out', 'DO IT TODAY', '#s5'),
 ],
 'former-it-provider-controls-microsoft-365': [
  ('hp-c-fix', 'alert', 'Which lock-out is it?', 'Three routes, depending on what you still hold', 'START HERE', '#s1'),
  ('hp-c-care', 'shield', 'Still have some admin?', 'Lock the door from the inside, in order', 'ROUTE 1', '#s2'),
  ('hp-c-biz', 'mail', 'Who holds your domain?', 'The real master key in every route', 'CHECK THIS FIRST', '#s5'),
  ('hp-c-buy', 'book', 'The leaving checklist', 'What to demand from any outgoing provider', 'FREE TO SHARE', '#s6'),
 ],
 'gaming-pc-slow-wont-load-games': [
  ('hp-c-fix', 'gauge', 'Full drive or old driver?', 'The first two checks, and neither needs a wipe', 'CHECK THIS FIRST', '#s1'),
  ('hp-c-care', 'bug', 'Slow since a free download?', 'Mods and cheat tools can hide adware and miners', 'PARENTS, READ THIS', '#s2'),
  ('hp-c-biz', 'alert', 'Fine, then it stutters?', 'Heat, or a Windows update that never finished', 'FANS ROARING?', '#s3'),
  ('hp-c-buy', 'wrench', 'Remote gaming tune-up', 'We check it all while you watch, nothing wiped', 'FROM &pound;65', '/gaming-pc-tune-up/'),
 ],
 'gaming-pc-tune-up': [
  ('hp-c-fix', 'gauge', 'Why it slowed down', 'Full drive, old drivers, start-up clutter, heat', 'THE USUAL CAUSES', '#s1'),
  ('hp-c-care', 'wrench', 'What the tune-up covers', 'Remote, while you watch, nothing wiped', 'FROM &pound;65', '#s2'),
  ('hp-c-biz', 'bug', 'Games won&rsquo;t load?', 'The causes, in the order to check them', 'DIY GUIDE', '/gaming-pc-slow-wont-load-games/'),
  ('hp-c-buy', 'home', 'Dust, parts or memory?', 'Physical jobs with free collection and return', 'HONEST LIMITS', '#s4'),
 ],
 'gave-a-scammer-remote-access': [
  ('hp-c-fix', 'alert', 'Six steps to take now', 'Disconnect, ring your bank on 159, change passwords', 'DO THIS NOW', '#s2'),
  ('hp-c-care', 'shield', 'How we make it safe', 'Remove what they left and check hidden changes', 'PATIENT LOCAL HELP', '#s3'),
  ('hp-c-biz', 'user', 'Real help vs a scammer', 'How genuine remote support actually works', 'SPOT THE DIFFERENCE', '#s4'),
  ('hp-c-buy', 'phone', 'Talk to a calm human', 'A real local person checks it over with you', 'NEVER A CALL CENTRE', '#fix-help'),
 ],
 'glamping-power-monitoring': [
  ('hp-c-fix', 'monitor', 'Every pod on one screen', 'Battery, solar and alerts at reception', 'THE STRAIGHT ANSWER', '#s1'),
  ('hp-c-care', 'star', 'What VRM already does', 'Alarm rules and an overview, credit where due', 'FREE FROM VICTRON', '#s3'),
  ('hp-c-biz', 'alert', 'What you need first', 'Victron kit with a GX device in each pod', 'THE PREREQUISITE', '#s6'),
  ('hp-c-buy', 'power', 'On a reception TV', 'A big, colour-coded screen for your staff', 'TV KIOSK', '/victron-vrm-tv-kiosk-display/'),
 ],
 'how-we-rebuilt-our-website': [
  ('hp-c-fix', 'book', 'Why we left WordPress', 'Updates, security surface and a speed ceiling', 'THE DECISION', '#s1'),
  ('hp-c-care', 'gauge', 'The numbers, honestly', 'Mobile score from about 65 to the high 80s', 'OUR OWN RUNS', '#s4'),
  ('hp-c-biz', 'bug', 'What broke on the way', 'And what we&rsquo;d do differently next time', 'FULL DISCLOSURE', '#s5'),
  ('hp-c-buy', 'briefcase', 'Would a rebuild help you?', 'We&rsquo;ll tell you straight, and sometimes it won&rsquo;t', 'HONEST ADVICE', '/contact/'),
 ],
 'it-provider-gone-bust': [
  ('hp-c-fix', 'shield', 'Secure access first', 'A calm checklist before anything lapses', 'START HERE', '#s2'),
  ('hp-c-care', 'wrench', 'How we take control back', 'Domain, Microsoft 365, backups, all documented', 'USUALLY SAME DAY', '#s3'),
  ('hp-c-biz', 'user', 'They have all our passwords', 'Make their copies useless, no cooperation needed', 'THE REAL FEARS', '#s4'),
  ('hp-c-buy', 'cloud', 'Old IT firm runs your 365?', 'Get Global Admin back into your own hands', 'MICROSOFT 365', '/former-it-provider-controls-microsoft-365/'),
 ],
 'it-support-for-accountants-dorset': [
  ('hp-c-fix', 'calendar', 'Ready for MTD deadlines?', 'Xero, Sage, IRIS and TaxCalc kept reliable', 'PRACTICE SOFTWARE', '#s2'),
  ('hp-c-care', 'shield', 'Client data kept secure', 'MFA, encryption, tested backups, GDPR in mind', 'SECURITY FIRST', '#s3'),
  ('hp-c-biz', 'briefcase', 'Plans and prices', 'From &pound;24.38 a month per computer', 'PREDICTABLE COST', '#s4'),
  ('hp-c-buy', 'phone', 'Get a practice quote', 'A local family team who phone before connecting', 'SINCE 1995', '/contact/'),
 ],
 'it-support-for-charities-dorset': [
  ('hp-c-fix', 'cloud', 'Free Microsoft 365?', 'Business Basic is free for up to 300 users', 'NONPROFIT GRANT', '#s2'),
  ('hp-c-care', 'shield', 'Cyber Essentials help', 'Protect beneficiary data and reassure funders', 'FOR FUNDERS', '#s3'),
  ('hp-c-biz', 'laptop', 'Volunteer devices', 'Set up fast, and access removed when they leave', 'PER-PC SUPPORT', '#s4'),
  ('hp-c-buy', 'briefcase', 'Plans and prices', 'Business support from &pound;24.38 per computer', 'SIMPLE PRICING', '/business-it-support-plans/'),
 ],
 'it-support-for-construction': [
  ('hp-c-fix', 'wifi', 'Internet on a remote site', '4G/5G in the cabin, Starlink where there&rsquo;s nothing', 'SITE CONNECTIVITY', '#s2'),
  ('hp-c-care', 'briefcase', 'The two-site problem', 'Office and site working from the same files', 'OFFICE AND SITE', '#s1'),
  ('hp-c-biz', 'calendar', 'How we get you set up', 'Five steps, starting with what hurts most', 'NO RIP AND REPLACE', '#s3'),
  ('hp-c-buy', 'star', 'Business plans and prices', 'Per computer, from &pound;24.38 a month', 'ROLLING MONTHLY', '/business-it-support-plans/'),
 ],
 'it-support-for-nurseries-dorset': [
  ('hp-c-fix', 'laptop', 'Tapestry or Famly issues?', 'We look after the PCs and tablets behind them', 'CHILDCARE APPS', '#s2'),
  ('hp-c-care', 'shield', 'Keep children&rsquo;s records safe', 'Tested backups and GDPR-friendly security', 'SAFEGUARDING DATA', '#s3'),
  ('hp-c-biz', 'wifi', 'Wifi out to the garden', 'Wifi, printers, CCTV and door-entry networking', 'WIFI AND PRINTERS', '#s4'),
  ('hp-c-buy', 'briefcase', 'Clear per-computer pricing', 'Business support plans, no call-out fee', 'FROM &pound;24.38', '/business-it-support-plans/'),
 ],
 'landline-switch-off-help': [
  ('hp-c-fix', 'phone', 'What actually changes', 'Same phone, same number, a new socket', 'PLAIN ENGLISH', '#s1'),
  ('hp-c-care', 'book', 'Five simple steps', 'What to do, and when, including alarms', 'STEP BY STEP', '#s2'),
  ('hp-c-biz', 'shield', 'Switch-off scams', 'The calls to hang up on, and who to tell', 'STAY SAFE', '#s3'),
  ('hp-c-buy', 'home', 'Have us set it up', 'A patient home visit, tested before we go', 'AT YOUR PACE', '#s4'),
 ],
 'laptop-clicking-noise-wont-turn-on': [
  ('hp-c-fix', 'power', 'Switch it off now', 'Every restart puts your photos and files at risk', 'READ THIS FIRST', '#s3'),
  ('hp-c-care', 'wrench', 'Drive, fan or charger?', 'Tell the three clicks apart with one safe test', 'ONE SAFE TEST', '#s2'),
  ('hp-c-biz', 'shield', 'Get the data recovered', 'Honest assessment first, you agree before we start', 'NO FIX, NO FEE', '/data-recovery/'),
  ('hp-c-buy', 'calendar', 'Book a collection', 'We collect it gently from across Dorset', 'ACROSS DORSET', '/book-a-collection/'),
 ],
 'laptop-screen-repair-cost-bournemouth': [
  ('hp-c-fix', 'gauge', 'What it usually costs', 'Price bands by screen size and type', 'RANGES FITTED', '#s1'),
  ('hp-c-care', 'monitor', 'What sets the price', 'Size, touch or OLED, parts and hidden damage', 'FIVE FACTORS', '#s2'),
  ('hp-c-biz', 'laptop', 'Repair or replace?', 'Or a refurbished Dell laptop from &pound;510', 'HONEST VERDICT', '#s3'),
  ('hp-c-buy', 'home', 'Free collection and quote', 'Fixed price before any work, 12-month warranty', 'NO FIX, NO FEE', '/book-a-collection/'),
 ],
 'laptop-set-up-for-elderly-parent': [
  ('hp-c-fix', 'user', 'What gets set up', 'Big text, email, video calls, printer, security', 'READY TO USE', '#s1'),
  ('hp-c-care', 'laptop', 'Buy one or send us yours', 'A refurbished Dell, or the laptop you chose', 'FROM &pound;510', '#s2'),
  ('hp-c-biz', 'phone', '30 days of help included', 'Remote support for the first few weeks', 'INCLUDED', '#s4'),
  ('hp-c-buy', 'home', 'Parent lives far away?', 'Set up remotely anywhere in the UK', 'UK-WIDE', '#s5'),
 ],
 'laptop-shuts-down-at-30-percent-battery': [
  ('hp-c-fix', 'gauge', 'Check your battery health', 'One command shows its real capacity', 'ONE COMMAND', '#s3'),
  ('hp-c-care', 'book', 'Why it dies at 30%', 'The gauge is an estimate, not a measurement', 'THE REAL CAUSE', '#s2'),
  ('hp-c-biz', 'alert', 'Swollen battery?', 'The signs, and why to stop using it now', 'SAFETY FIRST', '#s5'),
  ('hp-c-buy', 'laptop', 'Book a battery check', 'Free collection, real capacity checked first', 'HANDS-ON REPAIR', '/book-a-collection/'),
 ],
 'laptop-shuts-off-when-moved': [
  ('hp-c-fix', 'power', 'Mains, battery or both?', 'The one test that narrows it down fast', 'CHECK THIS FIRST', '#s1'),
  ('hp-c-care', 'wrench', 'Is it the charging socket?', 'The wiggle test, and why to try another charger', 'MAINS ONLY', '#s2'),
  ('hp-c-biz', 'alert', 'Protect your files now', 'Sudden power cuts can corrupt your data', 'BACK UP FIRST', '#s5'),
  ('hp-c-buy', 'laptop', 'Book a free collection', 'Diagnosis first, and no fix means no fee', 'HANDS-ON REPAIR', '/book-a-collection/'),
 ],
 'laptop-ssd-upgrade-bournemouth': [
  ('hp-c-fix', 'gauge', 'Why an SSD is the big fix', 'Starts in seconds instead of minutes', 'BIGGEST SPEED BOOST', '#s1'),
  ('hp-c-care', 'shield', 'Keep all your files', 'We clone Windows, programs and files across', 'NOTHING LOST', '#s2'),
  ('hp-c-biz', 'star', 'Upgrade or replace?', 'Our honest steer before we fit anything', 'STRAIGHT TALK', '#s3'),
  ('hp-c-buy', 'calendar', 'Book a free collection', 'Clear price first, 12-month warranty on the work', 'NO CALL-OUT FEE', '/book-a-collection/'),
 ],
 'laptop-stuck-on-logo-wont-boot': [
  ('hp-c-fix', 'power', 'Unplug every USB device', 'A stray USB stick or SD card can block the boot', 'TRY THIS FIRST', '#s2'),
  ('hp-c-care', 'monitor', 'Can the BIOS see the drive?', 'The two-minute check that decides what&rsquo;s next', 'MOST IMPORTANT', '#s3'),
  ('hp-c-biz', 'alert', 'Drive gone or clicking?', 'Stop now to protect your files', 'STOP TRYING', '#s5'),
  ('hp-c-buy', 'calendar', 'Book a free collection', 'We get your files safe first, then repair', 'NO FIX, NO FEE', '/book-a-collection/'),
 ],
 'laptop-turns-off-when-unplugged': [
  ('hp-c-fix', 'power', 'Rule out the charger', 'Two-minute checks before you blame the battery', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-care', 'gauge', 'Read the battery report', 'One command shows how worn it really is', 'BUILT INTO WINDOWS', '#s3'),
  ('hp-c-biz', 'alert', 'Battery or the board?', 'Worn out, not detected, or a charging fault', 'THREE CAUSES', '#s4'),
  ('hp-c-buy', 'wrench', 'Get a new battery fitted', 'We collect it, confirm the fault, then fit one', 'NO FIX, NO FEE', '/book-a-collection/'),
 ],
 'laptop-wont-turn-on-no-lights': [
  ('hp-c-fix', 'power', 'Check the charger first', 'Socket, brick light, cable and a spare charger', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-care', 'clock', 'Force a power drain', 'Unplug, then hold power for 15 to 30 seconds', 'FREE TO TRY', '#s3'),
  ('hp-c-biz', 'shield', 'Worried about your files?', 'A dead laptop rarely means lost photos', 'YOUR FILES', '#s7'),
  ('hp-c-buy', 'wrench', 'Still dead? We collect it', 'Diagnosis first, and a price before any repair', 'COLLECTION REPAIR', '/book-a-collection/'),
 ],
 'locked-out-microsoft-365-admin-account': [
  ('hp-c-fix', 'phone', 'Password OK, no code?', 'It&rsquo;s the MFA, not the password: try these', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-care', 'user', 'Is anyone else an admin?', 'The quickest way back in, if one still works', 'FASTEST ROUTE', '#s3'),
  ('hp-c-biz', 'book', 'The three ways back in', 'Another admin, domain takeover or Microsoft', 'RECOVERY ROUTES', '#s4'),
  ('hp-c-buy', 'briefcase', 'Let us drive the case', 'We triage, build the evidence and chase Microsoft', '&pound;20 INVESTIGATION', '#s6'),
 ],
 'mapped-network-drive-keeps-disconnecting': [
  ('hp-c-fix', 'user', 'Save the drive&rsquo;s login', 'Credential Manager, then reconnect at sign-in', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-care', 'clock', 'Drops after a coffee break?', 'Idle SMB timeouts and reconnecting at logon', 'IDLE TIMEOUTS', '#s3'),
  ('hp-c-biz', 'wifi', 'Only the Wi-Fi PCs?', 'Why a network cable often settles it', 'WIRED BEATS WI-FI', '#s4'),
  ('hp-c-buy', 'wrench', 'Fix it for the office', 'Remote fix, price agreed first, no fix no fee', 'FROM &pound;20', '/remote-support/'),
 ],
 'mesh-wifi-setup-guide': [
  ('hp-c-fix', 'phone', 'Landline on the hub?', 'Bridge mode can stop 999 calls on Digital Voice', 'READ THIS FIRST', '#s1'),
  ('hp-c-care', 'wrench', 'Your provider&rsquo;s settings', 'BT, EE, Sky, Virgin, Plusnet and TalkTalk hubs', 'ISP BY ISP', '#s5'),
  ('hp-c-biz', 'home', 'Where to put the nodes', 'Halfway, not in the dead spot, one at a time', 'STEP 8', '#s9'),
  ('hp-c-buy', 'wifi', 'Which mesh to buy?', 'Compare the systems before you spend', 'BUYING GUIDE', '/mesh-wifi-systems-uk/'),
 ],
 'mesh-wifi-systems-uk': [
  ('hp-c-fix', 'gauge', 'Three free checks first', 'Wired speed test, move the router, test a phone', 'BEFORE YOU SPEND', '#s1'),
  ('hp-c-care', 'wifi', 'Compare the models', 'UK prices and the box&rsquo;s claims, side by side', 'FILTER BY BUDGET', '#s4'),
  ('hp-c-biz', 'home', 'How many units you need', 'Depends on your walls, not your floor area', 'QUICK PLANNER', '#s5'),
  ('hp-c-buy', 'alert', 'When mesh is wrong', 'Six times a cable or a better router wins', 'SAVE YOUR MONEY', '#s9'),
 ],
 'microsoft-office-unlicensed-product-error': [
  ('hp-c-fix', 'user', 'Right account signed in?', 'Check File, then Account: the classic cause', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-care', 'briefcase', 'Licence from your work?', 'Make sure a licence is assigned to your name', 'WORK ACCOUNT?', '#s3'),
  ('hp-c-biz', 'wrench', 'Still says unlicensed?', 'Clear cached sign-ins and reset Office&rsquo;s identity', 'ADVANCED', '#s4'),
  ('hp-c-buy', 'phone', 'Have us sort it remotely', 'You watch while we fix it, price agreed first', 'FROM &pound;20', '#fix-help'),
 ],
 'microsoft-word-wont-open': [
  ('hp-c-fix', 'alert', 'Crashes when Sage opens it?', 'The June 2026 update bug and how to clear it', 'CHECK THIS FIRST', '#s1'),
  ('hp-c-care', 'wrench', 'Try Word in safe mode', 'Two minutes tells you if an add-in is to blame', '2 MINUTES', '#s2'),
  ('hp-c-biz', 'book', 'Crashed while typing?', 'Your document is probably recoverable', 'BEFORE YOU RETYPE', '#s6'),
  ('hp-c-buy', 'phone', 'Have us fix it remotely', 'You watch while we work, price agreed first', 'FROM &pound;20', '#fix-help'),
 ],
 'motorhome-hire-fleet-monitoring': [
  ('hp-c-fix', 'monitor', 'One screen, every van', 'Charge, solar and alerts for the whole fleet', 'THE ONE-SCREEN ANSWER', '#s1'),
  ('hp-c-care', 'power', 'Catch flat batteries early', 'Spot a low van before the keys go out', 'FEWER CALLOUTS', '#s2'),
  ('hp-c-biz', 'book', 'Is free VRM enough?', 'Where a hire desk outgrows the stock portal', 'HONEST COMPARISON', '#s3'),
  ('hp-c-buy', 'calendar', 'What it costs', 'Quote-based, and it scales per vehicle', 'NO OBLIGATION', '#s7'),
 ],
 'new-employee-laptop-setup': [
  ('hp-c-fix', 'laptop', 'Whose laptop is it?', 'Why business-owned beats personal or hand-me-down', 'DECIDE THIS FIRST', '#s1'),
  ('hp-c-care', 'user', 'Accounts in your own tenant', 'Never under someone&rsquo;s personal login', 'BIGGEST MISTAKE', '#s2'),
  ('hp-c-biz', 'shield', 'Day-one access and security', 'What to give, what to hold back, what to switch on', 'BEFORE DAY ONE', '#s3'),
  ('hp-c-buy', 'briefcase', 'Have us set it up', 'Laptop, accounts and access ready for day one', 'WITH A JOINER RECORD', '/contact/'),
 ],
 'new-laptop-set-up-bournemouth': [
  ('hp-c-fix', 'laptop', 'Buy one ready to go', 'A refurbished Dell set up on Windows 11', 'READY TO SWITCH ON', '/dell-hardware/'),
  ('hp-c-care', 'wrench', 'Already bought one?', 'We set up any make, then show you how', 'ANY MAKE', '#s3'),
  ('hp-c-biz', 'cloud', 'Moving your photos across', 'Photos, files and favourites, nothing left behind', 'SAFE TRANSFER', '/transfer-photos-to-a-new-computer-bournemouth/'),
  ('hp-c-buy', 'user', 'Buying for a parent?', 'Simple, safe setup and patient help', 'FAMILY BUYERS', '#s4'),
 ],
 'off-grid-internet': [
  ('hp-c-fix', 'power', 'What off-grid means here', 'Solar, lithium and a Victron system we monitor', 'BRINGS ITS OWN POWER', '#s1'),
  ('hp-c-care', 'cloud', 'Heat, snow and ice', 'How the dish copes with British weather', 'PUBLISHED RATINGS', '#s2'),
  ('hp-c-biz', 'home', 'Where it works', 'Farms, bare sites, filming and harbour-side jobs', 'AND WHERE IT WON&rsquo;T', '#s3'),
  ('hp-c-buy', 'wrench', 'Need it permanently?', 'Buy the kit in your own name and we fit it', 'WE INSTALL', '#s4'),
 ],
 'office-wifi-keeps-dropping-out': [
  ('hp-c-fix', 'wifi', 'Wired PC drops too?', 'Then it&rsquo;s the line or router, not the WiFi', 'CHECK THIS FIRST', '#s4'),
  ('hp-c-care', 'gauge', 'Worse as the office fills?', 'An overworked router or a full address pool', 'SUSPECT ONE', '#s2'),
  ('hp-c-biz', 'alert', 'Random one-minute drops?', 'Dorset&rsquo;s radar quirk on the 5GHz band', 'DFS RADAR', '#s3'),
  ('hp-c-buy', 'clock', 'Free room-by-room survey', 'Run it at your desks and we review it free', 'WRITTEN REPORT', '/wifi-signal-test/'),
 ],
 'onedrive-files-disappeared': [
  ('hp-c-biz', 'cloud', 'Look inside OneDrive first', 'Windows may have moved Desktop and Documents', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-buy', 'clock', 'Deleted? Use the Recycle Bin', 'OneDrive keeps deleted files for 30 days', '30-DAY SAFETY NET', '#s4'),
 ],
 'onedrive-keeps-asking-to-sign-in': [
  ('hp-c-biz', 'wrench', 'Clear the saved sign-in', 'Remove OneDrive&rsquo;s cached credentials, sign in once', 'TRY THIS FIRST', '#s2'),
  ('hp-c-buy', 'briefcase', 'Work account signing out?', 'Often a company security rule, not a fault', 'WORK ACCOUNT?', '#s4'),
 ],
 'onedrive-moved-my-desktop-and-documents': [
  ('hp-c-biz', 'alert', 'Avoid the trap dialog', 'The one option that keeps your files on the PC', 'READ THIS FIRST', '#s3'),
  ('hp-c-buy', 'monitor', 'Desktop still empty?', 'Move the files back out of the OneDrive folder', 'THE HIDDEN STEP', '#s4'),
 ],
 'onedrive-problems': [
  ('hp-c-biz', 'cloud', 'Files moved into OneDrive?', 'Folder Backup moved them: nothing is deleted', 'FILES NOT LOST', '/onedrive-moved-my-desktop-and-documents/'),
  ('hp-c-buy', 'clock', 'OneDrive not syncing?', 'Six checks, and none of them deletes anything', '6 QUICK CHECKS', '#s3'),
 ],
 'outgrown-wix-squarespace': [
  ('hp-c-fix', 'star', 'Should you stay put?', 'The honest stay-or-go checklist', 'CHECK THIS FIRST', '#s1'),
  ('hp-c-care', 'alert', 'What exports when you leave', 'Less than you&rsquo;d think, in Wix&rsquo;s own words', 'READ BEFORE LEAVING', '#s2'),
  ('hp-c-biz', 'gauge', 'Test your site free', 'Google&rsquo;s PageSpeed engine, about a minute', 'NO SIGN-UP', '#s5'),
  ('hp-c-buy', 'shield', 'Keep your Google rankings', 'The SEO-safe migration path if you leave', '301 REDIRECTS', '#s7'),
 ],
 'printer-asking-for-admin-password': [
  ('hp-c-biz', 'user', 'Which password does it want?', 'Not your email or WiFi key: an admin on that PC', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-buy', 'home', 'Forgot the admin password?', 'The safe way back in on a home PC', 'HOME PC', '#s4'),
 ],
 'printer-disappeared-after-windows-update': [
  ('hp-c-biz', 'monitor', 'Is it really gone?', 'Check the classic Devices and Printers list', 'CHECK THIS FIRST', '#s1'),
  ('hp-c-buy', 'clock', 'Restart the print spooler', 'The 30-second first fix, step by step', '30 SECONDS', '#s3'),
 ],
 'printer-prints-but-wont-scan-after-new-router': [
  ('hp-c-biz', 'shield', 'Two hidden blockers', 'Router isolation and a &lsquo;Public&rsquo; network setting', 'NO ERROR MESSAGE', '#s3'),
  ('hp-c-buy', 'wrench', 'The reliable fix', 'Reinstall the maker&rsquo;s full software package', 'ABOUT 10 MINUTES', '#s4'),
 ],
 'printer-says-wifi-password-incorrect': [
  ('hp-c-biz', 'wifi', 'Printer only does 2.4GHz?', 'Give it its own band so it can join', 'THE BAND TRAP', '#s2'),
  ('hp-c-buy', 'shield', 'WPA3 or channel 13?', 'Two router settings that lock printers out', 'UK ROUTERS', '#s3'),
 ],
 'printer-stopped-working-after-changing-wifi-password': [
  ('hp-c-biz', 'alert', 'Prints but won&rsquo;t scan?', 'Scanning is registered separately: re-add it', 'THE GOTCHA', '#s4'),
  ('hp-c-buy', 'shield', 'Changed it after a scam?', 'Do these first: the printer can wait', 'SAFETY FIRST', '#s5'),
 ],
 'printer-wont-connect-after-changing-broadband': [
  ('hp-c-biz', 'alert', 'Connected but won&rsquo;t print?', 'The fixed-IP trap that strands printers', 'THE HIDDEN TRAP', '#s3'),
  ('hp-c-buy', 'wifi', 'New mesh or smart hub?', 'Band steering and guest networks, explained', 'MODERN HUBS', '#s4'),
 ],
 'printer-wont-connect-after-moving-house': [
  ('hp-c-biz', 'wifi', 'Reconnect it by make', 'HP, Epson, Canon and Brother, step by step', 'ON THE PRINTER', '#s3'),
  ('hp-c-buy', 'alert', 'Wizard never finishes?', 'The 2.4GHz band trap on new routers', 'NEW ROUTER?', '#s4'),
 ],
 'printer-wont-connect-to-bt-smart-hub': [
  ('hp-c-biz', 'wifi', 'Switch 5GHz off for a minute', 'Give the printer a clear run at 2.4GHz', 'THE HUB TRICK', '#s4'),
  ('hp-c-buy', 'alert', 'New BT hub just fitted?', 'New name and password: re-enter them on the printer', 'CHECK THIS FIRST', '#s1'),
 ],
 'printer-wont-connect-to-ee-smart-hub': [
  ('hp-c-biz', 'wifi', 'Turn on Compatible WiFi', 'The separate 2.4GHz network printers can join', 'THE RELIABLE FIX', '#s3'),
  ('hp-c-buy', 'alert', 'Says a MAC filter blocks it?', 'Usually a false alarm: check the band and WPA3', 'RED HERRING', '#s4'),
 ],
 'printer-wont-connect-to-mesh-wifi': [
  ('hp-c-biz', 'wifi', 'Printer can&rsquo;t join?', 'Give it a clean 2.4GHz connection first', 'START HERE', '#s3'),
  ('hp-c-buy', 'clock', 'Keeps going offline?', 'Pin its address so every computer finds it', 'DHCP RESERVATION', '#s4'),
 ],
 'printer-wont-scan-to-computer-windows-11': [
  ('hp-c-biz', 'wrench', 'Prints but won&rsquo;t scan?', 'Swap Windows&rsquo; basic driver for the full package', 'USUAL CAUSE', '#s2'),
  ('hp-c-buy', 'monitor', 'Scan from the PC instead', 'The printer&rsquo;s Scan button needs a helper app', 'QUICK TEST', '#s3'),
 ],
 'recover-photos-deceased-relatives-laptop': [
  ('hp-c-fix', 'shield', 'No password? Usually fine', 'The photos sit on the drive, not behind the login', 'THE SHORT ANSWER', '#s1'),
  ('hp-c-care', 'power', 'Laptop won&rsquo;t turn on?', 'The photos are usually still safe on the drive', 'CLICKING? SWITCH OFF', '#s3'),
  ('hp-c-biz', 'alert', 'Asking for a BitLocker key?', 'Where the recovery key is usually found', 'THE ONE EXCEPTION', '#s4'),
  ('hp-c-buy', 'home', 'Hand it over to us', 'Collected, recovered privately, no fix no fee', 'NO RUSH', '/book-a-collection/'),
 ],
 'refurbished-dell-latitude-3000': [
  ('hp-c-fix', 'laptop', 'See Latitudes in stock', 'Pick a tested 3000 by budget and the work you do', 'FROM &pound;510', '/dell-hardware/'),
  ('hp-c-care', 'book', 'Models and prices', '3420, 3520 and 3540 side by side', 'COMPARE MODELS', '#s2'),
  ('hp-c-biz', 'monitor', 'Pick the right screen', 'Why Full HD matters on a budget Latitude', 'READ THIS FIRST', '#s6'),
  ('hp-c-buy', 'star', '3000, 5000 or 7000?', 'Which Latitude tier fits your budget and use', 'SERIES EXPLAINED', '/dell-latitude-series-explained-3000-5000-7000/'),
 ],
 'refurbished-dell-latitude-5000': [
  ('hp-c-fix', 'laptop', 'See Latitudes in stock', 'Pick a tested 5000-series by budget and job', 'STOCK PICKER', '/dell-hardware/'),
  ('hp-c-care', 'star', 'Four models, guide prices', '5520, 5420, 5430 and 5530 from &pound;535 all-in', 'GUIDE PRICES', '#s2'),
  ('hp-c-biz', 'gauge', '11th gen or 12th gen?', 'Honest CPU advice for what you actually do', 'WHICH TO PICK', '#s3'),
  ('hp-c-buy', 'book', '5420 or 5430?', 'Our side-by-side verdict on the two 14-inch models', 'COMPARE', '/dell-latitude-5420-vs-5430-which-to-buy/'),
 ],
 'refurbished-dell-latitude-7000': [
  ('hp-c-fix', 'laptop', 'See Latitudes in stock', 'Pick a tested 7000 by budget and the work you do', 'STOCK PICKER', '/dell-hardware/'),
  ('hp-c-care', 'book', 'Four models, honest prices', '7320, 7420, 7330 and 7430 side by side', 'COMPARE MODELS', '#s2'),
  ('hp-c-biz', 'alert', 'The soldered-RAM rule', 'Get the memory right on day one; it never grows', 'READ THIS FIRST', '#s3'),
  ('hp-c-buy', 'gauge', '12th-gen i5 or 11th-gen i7?', 'Why the newer i5 is the faster laptop', 'OUR STEER', '#s4'),
 ],
 'refurbished-dell-optiplex-3000': [
  ('hp-c-fix', 'monitor', 'Pick from desktops in stock', 'Choose a tested OptiPlex by budget and job', 'STOCK PICKER', '/dell-hardware/?kind=desktop'),
  ('hp-c-care', 'book', '3080, 3090 or 3000?', 'Three model years side by side, honestly priced', 'COMPARE MODELS', '#s2'),
  ('hp-c-biz', 'star', 'Which one to buy', 'Our pick for the longest Windows 11 runway', 'OUR VERDICT', '#s3'),
  ('hp-c-buy', 'monitor', 'Micro, SFF or Tower?', 'Pick the case for where it will sit', 'CASE GUIDE', '#s4'),
 ],
 'refurbished-dell-optiplex-5000': [
  ('hp-c-fix', 'star', '5080, 5090 or 5000?', 'Three years and three guide prices, side by side', 'FROM &pound;615', '#s2'),
  ('hp-c-care', 'monitor', 'Tower, SFF or Micro?', 'Pick the case by what you&rsquo;ll do later', 'CHOOSE YOUR SIZE', '#s4'),
  ('hp-c-biz', 'briefcase', 'Desktops in stock', 'Browse refurbished Dell desktops ready to go', 'STOCK PICKER', '/dell-hardware/?kind=desktop'),
  ('hp-c-buy', 'user', 'Get one matched to you', 'Tell us the job; we confirm the exact CPU first', 'FREE ADVICE', '/contact/'),
 ],
 'refurbished-dell-optiplex-7000': [
  ('hp-c-fix', 'monitor', 'See desktops in stock', 'Pick a tested OptiPlex by budget and job', 'STOCK PICKER', '/dell-hardware/?kind=desktop'),
  ('hp-c-care', 'star', 'Four generations compared', '7080 to 7010, with guide prices from &pound;590', 'GUIDE PRICES', '#s2'),
  ('hp-c-biz', 'gauge', 'Micro, SFF or Tower?', 'Pick the box that fits the job and the desk', 'FORM FACTOR', '#s4'),
  ('hp-c-buy', 'briefcase', 'Only need email and Office?', 'The OptiPlex 3000 tier does it for less', 'CHEAPER OPTION', '/refurbished-dell-optiplex-3000/'),
 ],
 'restrict-staff-access-to-shared-folders-windows-11': [
  ('hp-c-biz', 'user', 'Everyone on one login?', 'Separate logins come first, or nothing works', 'STEP ZERO', '#s2'),
  ('hp-c-buy', 'monitor', 'Opened from other PCs?', 'The share and the Security tab both apply', 'NETWORK SHARE', '#s4'),
 ],
 'room-by-room-wifi-test': [
  ('hp-c-fix', 'wifi', 'Run the free WiFi survey', 'Star-rates every room and makes a PDF', 'FREE, NO SIGN-UP', '/wifi-signal-test/'),
  ('hp-c-care', 'book', 'How to test properly', 'Four rules for a survey that means something', '4 SIMPLE RULES', '#s2'),
  ('hp-c-biz', 'gauge', 'What the numbers mean', 'Why jitter matters more than speed on calls', 'VIDEO CALLS?', '#s3'),
  ('hp-c-buy', 'star', 'Don&rsquo;t buy kit yet', 'Three results that mean spend nothing', 'SAVE YOUR MONEY', '#s5'),
 ],
 'sage-50-multi-user-cannot-connect': [
  ('hp-c-biz', 'power', 'Check the host PC first', 'Is it awake, and is the Sage data service running?', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-buy', 'alert', 'Half the team can&rsquo;t get in?', 'Every PC must run the same Sage 50 version', 'AFTER AN UPDATE?', '#s5'),
 ],
 'sage-50-wont-print-to-pdf-windows-11': [
  ('hp-c-biz', 'alert', 'Only one invoice fails?', 'An oversized logo, not the PDF driver', 'OUT OF MEMORY?', '#s4'),
  ('hp-c-buy', 'mail', 'PDF made, email stuck?', 'That&rsquo;s Outlook, not the Sage PDF driver', 'DIFFERENT FIX', '/sage-50-wont-email-invoices-outlook/'),
 ],
 'sage-instant-accounts-windows-11': [
  ('hp-c-fix', 'shield', 'Rescue the data first', 'A verified copy off the old PC, today', 'DO THIS FIRST', '#s2'),
  ('hp-c-care', 'book', 'Four realistic routes', 'Keep it, contain it, replace it, or both', 'HONEST TRADE-OFFS', '#s3'),
  ('hp-c-biz', 'clock', 'Years of old records', 'Export the reports while the old program runs', 'BEFORE YOU SWITCH', '#s4'),
  ('hp-c-buy', 'calendar', 'Book a free collection', 'We copy and verify it before anything changes', 'NO FIX, NO FEE', '/book-a-collection/'),
 ],
 'scam-pop-up-help-poole': [
  ('hp-c-fix', 'shield', 'Is the warning real?', 'No. Why that virus alert is just a web page', 'READ THIS FIRST', '#s1'),
  ('hp-c-care', 'alert', 'Close the pop-up safely', 'Task Manager, End task, and don&rsquo;t restore it', 'DO THIS NOW', '#s2'),
  ('hp-c-biz', 'phone', 'Already called or paid?', 'Ring your bank on 159, then report it', 'CALM STEPS', '#s5'),
  ('hp-c-buy', 'wrench', 'Get the PC checked', 'We look for hidden remote-access tools', 'USUALLY SAME DAY', '#s4'),
 ],
 'scam-recovery': [
  ('hp-c-fix', 'phone', 'Money gone? The first hour', 'Ring 159, stop contact, change passwords', 'DO THIS FIRST', '#s1'),
  ('hp-c-care', 'shield', 'Make the computer safe', 'What we check and remove, while you watch', 'THE CLEAN-UP', '#s2'),
  ('hp-c-biz', 'book', 'The report for your bank', 'Written in plain English, ready to send', 'BANK REPORT', '#s3'),
  ('hp-c-buy', 'alert', 'Let a scammer onto the PC?', 'The first steps if you let someone in', 'REMOTE ACCESS SCAM', '/gave-a-scammer-remote-access/'),
 ],
 'scan-to-folder-stopped-working-after-windows-update': [
  ('hp-c-biz', 'monitor', 'Check the PC first', 'Password changed? Network flipped to Public?', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-buy', 'user', 'Scanner&rsquo;s own account', 'The fix that won&rsquo;t fall over at the next update', 'THE FIX THAT LASTS', '#s4'),
 ],
 'second-hand-office-computers-poole': [
  ('hp-c-fix', 'monitor', 'Office desktops in stock', 'Refurbished Dell OptiPlex, ready for daily work', 'BUSINESS-GRADE', '/dell-hardware/?kind=desktop'),
  ('hp-c-care', 'laptop', 'Refurbished Dell laptops', 'Latitude laptops, tested, wiped and set up', 'LATITUDE', '/refurbished-dell-laptops-bournemouth/'),
  ('hp-c-biz', 'book', 'What each PC includes', 'New Samsung SSD, licensed Windows, full test', 'WHAT YOU GET', '#s1'),
  ('hp-c-buy', 'briefcase', 'Kitting out a team?', 'Tell us how many and what your team does', 'NO CALL-OUT FEE', '/contact/'),
 ],
 'share-files-small-office-without-server': [
  ('hp-c-fix', 'monitor', 'Share from one PC?', 'Cheapest, but it comes with conditions', 'SMALLEST OFFICES', '#s2'),
  ('hp-c-care', 'briefcase', 'A NAS box', 'An always-on file store for the office', 'LARGE FILES?', '#s3'),
  ('hp-c-biz', 'cloud', 'OneDrive or Google Drive', 'Best when anyone works away from the office', 'WORK FROM HOME?', '#s4'),
  ('hp-c-buy', 'star', 'Which one fits you?', 'Four patterns and four questions to ask first', 'CHOOSE ON PURPOSE', '#s5'),
 ],
 'share-internet-between-two-buildings': [
  ('hp-c-fix', 'wrench', 'Can you dig a trench?', 'Buried Ethernet: the fastest, most reliable link', 'THE GOLD STANDARD', '#s2'),
  ('hp-c-care', 'wifi', 'No trench? Go wireless', 'A point-to-point bridge between the two roofs', 'OUR SPECIALISM', '#s5'),
  ('hp-c-biz', 'home', 'Which option fits?', 'Distance, digging and your electrics decide it', 'THREE QUESTIONS', '#s6'),
  ('hp-c-buy', 'phone', 'Ask us to look at it', 'We check line of sight and quote it first', 'FREE ADVICE', '/contact/'),
 ],
 'shared-folder-read-only-cant-save-windows-11': [
  ('hp-c-biz', 'shield', 'Opens fine, won&rsquo;t save?', 'Share needs Change, Security tab needs Modify', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-buy', 'user', 'Says someone has it open?', 'Find and clear a stale lock safely', 'LOCKED FILE', '#s3'),
 ],
 'shared-folders-not-working-after-windows-11-24h2-update': [
  ('hp-c-biz', 'shield', 'Give the share a login', 'The safe fix: a real username and password', 'THE SAFE FIX', '#s3'),
  ('hp-c-buy', 'monitor', 'Folder on a NAS box?', 'Turn on signing on the NAS itself, not in Windows', 'NAS OWNERS', '#s4'),
 ],
 'slow-wordpress-site-fix-or-rebuild': [
  ('hp-c-fix', 'gauge', 'The 20-minute triage', 'Five checks that tell you which kind of slow', 'START HERE', '#s1'),
  ('hp-c-care', 'wrench', 'Cheap fixes that work', 'Images, plugins, caching, PHP and hosting', 'LITTLE OR NO COST', '#s2'),
  ('hp-c-biz', 'book', 'Keep WordPress or leave?', 'When a rebuild is the wrong move', 'THE HONEST FORK', '#s4'),
  ('hp-c-buy', 'star', 'Get a rebuild quoted', 'Priced per site, no set tiers, no obligation', 'FREE QUOTE', '#s7'),
 ],
 'smart-tv-streaming-setup-help': [
  ('hp-c-fix', 'monitor', 'A patient setup visit', 'Wi-Fi, apps, subtitles and the remote, explained', 'STEP BY STEP', '#s2'),
  ('hp-c-care', 'star', 'Android TV or Fire TV?', 'Home ground for us, and honest about Apple', 'WHAT WE KNOW', '#s3'),
  ('hp-c-biz', 'user', 'Apps signed out again?', 'Someone patient to call, on our home plan', '&pound;18.25 A MONTH', '#s4'),
  ('hp-c-buy', 'phone', 'Get an honest quote', 'We&rsquo;ll say if it needs a visit or just a call', 'CALL OR TEXT', '/contact/'),
 ],
 'smartphone-lessons-for-seniors': [
  ('hp-c-fix', 'user', 'Group sessions or 1-to-1', 'In Kinson, or one-to-one over the phone', 'CALL FOR DATES', '#s2'),
  ('hp-c-care', 'phone', 'What you&rsquo;ll learn', 'WhatsApp, photos, video calls and scam texts', 'ANDROID SPECIALISTS', '#s1'),
  ('hp-c-biz', 'book', 'Free online courses', 'Short lessons and a certificate, no sign-up', 'FREE', '#s3'),
  ('hp-c-buy', 'star', 'Make the text bigger now', 'A quick win you can try right now', 'TRY THIS TODAY', '#s4'),
 ],
 'static-site-vs-wordpress-small-business': [
  ('hp-c-fix', 'star', 'Which should you choose?', 'Our honest steer, by type of business', 'THE VERDICT', '#s7'),
  ('hp-c-care', 'alert', 'When WordPress still wins', 'Shops, logins and sites you edit every week', 'HONEST TRADE-OFF', '#s4'),
  ('hp-c-biz', 'gauge', 'What static did for us', 'Our mobile speed score, before and after', 'OUR OWN NUMBERS', '#s2'),
  ('hp-c-buy', 'book', 'How we rebuilt our site', 'The full story, including what broke', 'CASE STUDY', '/how-we-rebuilt-our-website/'),
 ],
 'stop-using-onedrive-without-losing-files': [
  ('hp-c-biz', 'cloud', 'Make local copies first', 'The one step that makes leaving OneDrive safe', 'DO THIS FIRST', '#s2'),
  ('hp-c-buy', 'monitor', 'Just want Desktop back?', 'Undo Folder Backup without leaving OneDrive', 'SMALLER JOB', '/onedrive-moved-my-desktop-and-documents/'),
 ],
 'stop-word-saving-to-onedrive': [
  ('hp-c-biz', 'cloud', 'Where did my files go?', 'They&rsquo;re in the OneDrive of the signed-in account', 'FIND THEM FIRST', '#s2'),
  ('hp-c-buy', 'shield', 'Before you switch it off', 'What you give up: AutoSave and version history', 'WORTH KNOWING', '#s5'),
 ],
 'teams-keeps-opening-wrong-account': [
  ('hp-c-fix', 'clock', 'Meeting starting now?', 'Quick fixes that get you into today&rsquo;s call', 'TRY THIS FIRST', '#s2'),
  ('hp-c-care', 'user', 'The permanent cure', 'Give your business email to one account only', 'STOPS THE PROMPT', '#s3'),
  ('hp-c-biz', 'briefcase', 'A guest in a client&rsquo;s Teams?', 'Why the fix sits with their admin, not you', 'GUEST ACCESS', '#s4'),
  ('hp-c-buy', 'wrench', 'Untangle it for me', 'Remote help; we phone before we connect', 'FROM &pound;20', '/remote-support/'),
 ],
 'the-set-of-folders-cannot-be-opened': [
  ('hp-c-fix', 'wrench', 'Reset the navigation pane', 'One command rebuilds it; your mail is untouched', 'TRY THIS FIRST', '#s2'),
  ('hp-c-care', 'alert', 'POP or IMAP? Check first', 'The one way this fix can risk your email', 'BEFORE YOU DELETE', '#s3'),
  ('hp-c-biz', 'book', 'What the error means', 'Usually a layout file, not lost email', 'DON&rsquo;T PANIC', '#s1'),
  ('hp-c-buy', 'mail', 'Other Outlook problems', 'Every Outlook fix on our site, in one place', 'OUTLOOK HELP', '/outlook-problems/'),
 ],
 'transfer-photos-to-a-new-computer-bournemouth': [
  ('hp-c-fix', 'cloud', 'What we move across', 'Photos, email, contacts, passwords and programs', 'THE FULL LIST', '#s1'),
  ('hp-c-care', 'shield', 'Backed up first', 'A full copy of the old PC before we start', 'SAFE BY DESIGN', '#s2'),
  ('hp-c-biz', 'laptop', 'Old PC wiped safely', 'Securely wiped, then recycled or handed back', 'DATA PROTECTED', '#s5'),
  ('hp-c-buy', 'monitor', 'Need the new PC too?', 'A refurbished Dell, set up with your files', 'READY TO USE', '/dell-hardware/'),
 ],
 'victron-boat-gps-tracking': [
  ('hp-c-fix', 'wrench', 'Use the GPS already aboard', 'One cable joins your N2K GPS to the Cerbo GX', 'REUSE YOUR KIT', '#s2'),
  ('hp-c-care', 'wifi', 'Internet at sea, tiered', 'Marina wifi, coastal 4G or Starlink, honestly', 'MARINA TO OFFSHORE', '#s3'),
  ('hp-c-biz', 'cloud', 'Out of internet range?', 'Your route backfills when the boat reconnects', 'NOTHING LOST', '#s4'),
  ('hp-c-buy', 'briefcase', 'Charter or hire fleet?', 'Every boat on one branded screen', 'FLEETS', '/white-label-victron-monitoring/'),
 ],
 'victron-gps-tracking': [
  ('hp-c-fix', 'wrench', 'Three ways to add GPS', 'USB dongle, NMEA 2000 or a GX LTE 4G-E', 'HARDWARE OPTIONS', '#s2'),
  ('hp-c-care', 'star', 'What VRM gives you free', 'Fleet map, geofence and route history', 'FREE WITH VRM', '#s3'),
  ('hp-c-biz', 'clock', 'How live is it, really?', 'Fifteen minutes, one minute, or a second or two', 'HONEST NUMBERS', '#s4'),
  ('hp-c-buy', 'gauge', 'Custom route dashboards', 'Smooth routes, drift filtering, a lasting archive', 'WE BUILD IT', '#s5'),
 ],
 'victron-grafana-dashboard-service': [
  ('hp-c-fix', 'wrench', 'Should you run it yourself?', 'When the DIY Grafana box is the right tool', 'HONEST ADVICE', '#s3'),
  ('hp-c-care', 'gauge', 'DIY vs hosted, side by side', 'Data cadence, offline use, upkeep and cost', 'HEAD-TO-HEAD', '#s6'),
  ('hp-c-biz', 'monitor', 'What we build instead', 'Many sites on one branded screen, nothing on-site', 'HOSTED FOR YOU', '#s4'),
  ('hp-c-buy', 'briefcase', 'What it costs', 'Quoted on sites, KPIs and the support you want', 'QUOTED PER JOB', '#s7'),
 ],
 'victron-installer-dorset': [
  ('hp-c-fix', 'power', 'What we fit', 'Solar, lithium, MPPT, inverters and Cerbo GX', 'FULL VICTRON STACK', '#s2'),
  ('hp-c-care', 'gauge', 'Watch our van live', 'A real Victron system, streamed from VRM', 'LIVE, NOT STOCK PHOTOS', '#s3'),
  ('hp-c-biz', 'home', 'Homes, vans and boats', 'Who we design Victron systems for', 'ACROSS DORSET', '#s4'),
  ('hp-c-buy', 'wrench', 'Get a design and quote', 'Sized to your real energy use, quoted clearly', 'QUOTED FIRST', '/contact/'),
 ],
 'victron-vrm-api-dashboard': [
  ('hp-c-fix', 'book', 'The endpoints that matter', 'Token, idSite, stats, diagnostics and widgets', 'WORKED EXAMPLE', '#s2'),
  ('hp-c-care', 'clock', 'Polling or MQTT?', 'The API isn&rsquo;t live; here&rsquo;s the real-time route', 'HOW LIVE?', '#s3'),
  ('hp-c-biz', 'monitor', 'Put it on your website', 'A live, branded panel on your own site', 'EMBED IT', '/embed-victron-vrm-on-website/'),
  ('hp-c-buy', 'wrench', 'Have us build and run it', 'Quote-based, hosted and maintained for you', 'DONE FOR YOU', '#s7'),
 ],
 'victron-vrm-tv-kiosk-display': [
  ('hp-c-fix', 'monitor', 'The free DIY kiosk', 'A Pi, a browser and VRM&rsquo;s own pages', 'DIY ROUTE', '#s3'),
  ('hp-c-care', 'alert', 'Where DIY bites', 'Dropped logins, fixed layout, laggy share links', 'HONEST LIMITS', '#s4'),
  ('hp-c-biz', 'gauge', 'Built for the wall', 'On-brand, live, and no login to babysit', 'HOSTED FOR YOU', '#s5'),
  ('hp-c-buy', 'star', 'See one running live', 'Our own van, streaming through the VRM API', 'LIVE DEMO', '#s6'),
 ],
 'virus-removal-christchurch': [
  ('hp-c-fix', 'alert', 'Real virus or fake pop-up?', 'Spot a scare advert before you call any number', 'CHECK THIS FIRST', '#s1'),
  ('hp-c-care', 'shield', 'Scammer on your screen?', 'Cut them off, then make sure nothing was left', 'ACT NOW', '/gave-a-scammer-remote-access/'),
  ('hp-c-biz', 'clock', 'Same-day clean-up', 'Remote while you watch, or a visit across BH23', 'USUALLY SAME DAY', '#s4'),
  ('hp-c-buy', 'star', 'Keep it clean afterwards', 'Protection, updates and one golden rule', 'STAY PROTECTED', '#s5'),
 ],
 'web-designer-disappeared': [
  ('hp-c-fix', 'alert', 'Save what exists today', 'Screenshots, a Wayback copy and your paperwork', 'DO THIS TODAY', '#s2'),
  ('hp-c-care', 'shield', 'Who holds your domain?', 'The crown jewel: check it with a WHOIS lookup', 'CHECK THIS FIRST', '#s3'),
  ('hp-c-biz', 'clock', 'Site says Account Suspended?', 'Get a backup before the host deletes it', 'TIME-CRITICAL', '#s5'),
  ('hp-c-buy', 'wrench', 'Recover or rebuild?', 'When rehosting beats a fresh start, and when not', 'HONEST ADVICE', '#s6'),
 ],
 'website-hacked-what-to-do': [
  ('hp-c-fix', 'alert', 'The first-hour checklist', 'Offline, change passwords, then scope the damage', 'DO THIS FIRST', '#s2'),
  ('hp-c-care', 'shield', 'Customer data involved?', 'Your ICO duty and the 72-hour clock', '72 HOURS', '#s3'),
  ('hp-c-biz', 'wrench', 'Clean it or rebuild it?', 'The honest fork most guides skip', 'THE HONEST ANSWER', '#s4'),
  ('hp-c-buy', 'phone', 'Want it handled today?', 'A local engineer looks the same day, quoted first', 'SAME-DAY LOOK', '/contact/'),
 ],
 'website-held-hostage': [
  ('hp-c-fix', 'alert', 'Hostage or just gone quiet?', 'Two different problems with two different fixes', 'CHECK THIS FIRST', '#s1'),
  ('hp-c-care', 'shield', 'Get the domain back first', 'The Nominet and ICANN routes, step by step', 'MOST IMPORTANT', '#s3'),
  ('hp-c-biz', 'book', 'Who owns the website?', 'The UK copyright reality, said plainly', 'WORTH KNOWING', '#s4'),
  ('hp-c-buy', 'briefcase', 'The escalation ladder', 'Calmest option first, solicitor last', 'STEP BY STEP', '#s6'),
 ],
 'website-maintenance-cost-uk': [
  ('hp-c-fix', 'gauge', 'What you should pay', 'Attributed 2026 UK market rates, by level', 'MARKET RATES', '#s3'),
  ('hp-c-care', 'shield', 'What maintenance includes', 'Updates, tested backups, monitoring and a log', 'THE MINIMUM', '#s2'),
  ('hp-c-biz', 'alert', 'Paying too much?', 'A five-minute self-audit with free tools', '5-MINUTE CHECK', '#s5'),
  ('hp-c-buy', 'briefcase', 'Get an honest view', 'Send us what you pay and what you get', 'NO PLAN TO SELL', '/contact/'),
 ],
 'websites-for-builders-tradesmen': [
  ('hp-c-fix', 'gauge', 'Ten-minute site check', 'Five checks to run before you pay anyone', 'DO IT YOURSELF', '#s3'),
  ('hp-c-care', 'wrench', 'What a trades site needs', 'Tap-to-call, a page per service, real photos', 'THE ESSENTIALS', '#s2'),
  ('hp-c-biz', 'briefcase', 'Checkatrade or your own?', 'Renting visibility versus owning it', 'STRAIGHT ANSWER', '#s4'),
  ('hp-c-buy', 'star', 'See the builder rebuild', 'A Dorset builder&rsquo;s site, before and after', 'PROOF, NOT PROMISES', '#s1'),
 ],
 'white-label-victron-monitoring': [
  ('hp-c-fix', 'alert', 'Why VRM can&rsquo;t be rebranded', 'No Dealer ID, a fixed layout, a Victron login', 'THE HONEST LIMITS', '#s2'),
  ('hp-c-care', 'wrench', 'What we build instead', 'Your logo and colours, only the figures that matter', 'YOUR BRAND', '#s3'),
  ('hp-c-biz', 'briefcase', 'Resell it under your name', 'One template for every customer you install', 'FOR INSTALLERS', '#s6'),
  ('hp-c-buy', 'home', 'On your own website', 'A branded portal on your own subdomain', 'YOUR DOMAIN', '#s8'),
 ],
 'who-has-a-file-open-on-shared-drive': [
  ('hp-c-fix', 'user', 'See who has it open', 'Open Files on the host PC, in about 30 seconds', 'QUICK ANSWER', '#s1'),
  ('hp-c-care', 'alert', 'Nobody has it open?', 'Find and clear the hidden ~$ lock file', 'PHANTOM LOCKS', '#s4'),
  ('hp-c-biz', 'clock', 'Happens every few days?', 'Why it keeps happening, and the real fix', 'THE BIGGER PICTURE', '#s6'),
  ('hp-c-buy', 'wrench', 'Clear it for me', 'We find the holder and clear locks safely', 'FROM &pound;20', '/remote-support/'),
 ],
 'why-computer-prices-have-gone-up': [
  ('hp-c-fix', 'gauge', 'Why prices really rose', 'The AI memory squeeze in plain English', 'THE SHORT ANSWER', '#s1'),
  ('hp-c-care', 'star', 'What it means for our prices', 'The new SSD is the big moving part, not our margin', 'OUR WORKING SHOWN', '#s4'),
  ('hp-c-biz', 'wrench', 'Six ways to beat the squeeze', 'Right spec first time, upgrade before you replace', 'PRACTICAL', '#s6'),
  ('hp-c-buy', 'laptop', 'See refurbished Dells', 'Tested Latitudes and OptiPlexes with a new 1TB SSD', 'STOCK PICKER', '/dell-hardware/'),
 ],
 'wifi-for-a-shepherds-hut': [
  ('hp-c-fix', 'wifi', 'Can you see the house?', 'A point-to-point link beams your broadband across', 'USUALLY BEST VALUE', '#s2'),
  ('hp-c-care', 'phone', 'A bar of mobile signal?', 'A 4G or 5G router with a proper external antenna', 'OPTION 2', '#s3'),
  ('hp-c-biz', 'cloud', 'Nothing reaches the hut?', 'Starlink for spots with no signal or line-of-sight', 'OPTION 3', '#s4'),
  ('hp-c-buy', 'power', 'No mains at the hut?', 'Run it off-grid with solar and lithium', 'OFF-GRID', '#s5'),
 ],
 'wifi-troubleshooting': [
  ('hp-c-biz', 'gauge', 'Is it the WiFi or the line?', 'One cable test splits the fault in two', 'CHECK THIS FIRST', '#s1'),
  ('hp-c-buy', 'wifi', 'Find your symptom', 'Drop-outs, stuttering calls, smart plugs, one TV', '14 SYMPTOMS', '#s2'),
 ],
 'wifi-uk-buildings-heat': [
  ('hp-c-fix', 'home', 'Your walls, wall by wall', 'Solid brick, stone, party walls and chimney breasts', 'BRITISH HOUSING', '#s3'),
  ('hp-c-care', 'alert', 'Worse after new windows?', 'Foil insulation and coated glass block WiFi', 'THERMAL UPGRADES', '#s4'),
  ('hp-c-biz', 'wifi', 'How many nodes you need', 'By house type, plus garden offices and garages', 'RULES OF THUMB', '#s5'),
  ('hp-c-buy', 'gauge', 'Worse every July?', 'A hot router, not a line fault: what to do', 'HOT WEATHER', '#s6'),
 ],
 'will-a-power-cut-damage-my-computer': [
  ('hp-c-fix', 'power', 'Won&rsquo;t start after a cut?', 'Simple checks before you assume the worst', 'CHECK THIS FIRST', '#s6'),
  ('hp-c-care', 'shield', 'Surge protector or UPS?', 'The honest difference, and which one you need', 'BUYING ADVICE', '#s4'),
  ('hp-c-biz', 'alert', 'The three real risks', 'The surge, the half-written file, the brownouts', 'PLAIN ENGLISH', '#s2'),
  ('hp-c-buy', 'wrench', 'Still dead? We collect it', 'Diagnosis first; you agree the price before work', 'COLLECTION REPAIR', '/computer-repairs/'),
 ],
 'will-i-lose-files-upgrading-to-windows-11': [
  ('hp-c-fix', 'shield', 'Back up first', 'A second copy turns a disaster into a delay', 'THE SAFETY NET', '#s3'),
  ('hp-c-care', 'alert', 'The buttons to avoid', 'The only two ways an upgrade wipes your files', 'READ BEFORE YOU CLICK', '#s4'),
  ('hp-c-biz', 'clock', 'Changed your mind?', 'Go back to Windows 10 within 10 days', '10-DAY WINDOW', '#s5'),
  ('hp-c-buy', 'user', 'Have us do it for you', 'Backed up first, upgraded, checked, handed back', 'NO FIX, NO FEE', '/windows-11-upgrade-service/'),
 ],
 'windows-10-esu-free-enrolment-help': [
  ('hp-c-biz', 'star', 'Two free ways to enrol', 'Microsoft account sync, or 1,000 Rewards points', 'FREE OPTIONS', '#s2'),
  ('hp-c-buy', 'shield', 'What ESU actually covers', 'Security updates only, until 12 October 2027', 'TO 12 OCT 2027', '#s1'),
 ],
 'windows-10-esu-or-upgrade-your-dell': [
  ('hp-c-fix', 'star', 'The 30-second answer', 'ESU, a free upgrade, or a newer Dell?', 'START HERE', '#s1'),
  ('hp-c-care', 'gauge', 'Can your Dell run 11?', 'Check in one click; sometimes it&rsquo;s a BIOS switch', 'CHECK THIS FIRST', '#s5'),
  ('hp-c-biz', 'shield', 'Is ESU worth it?', 'Free or about $30 to stay patched to 2027', 'WHEN IT MAKES SENSE', '#s3'),
  ('hp-c-buy', 'laptop', 'Trade up to a newer Dell', 'Refurbished, Windows 11 ready, set up for you', 'STOCK PICKER', '/dell-hardware/'),
 ],
 'windows-11-cant-access-windows-10-shared-folder': [
  ('hp-c-fix', 'monitor', 'See it but can&rsquo;t open it?', 'A quick test tells you which of two faults it is', 'CHECK THIS FIRST', '#s3'),
  ('hp-c-care', 'user', 'Give it a real login', 'The fix that lasts, set up on the Windows 10 PC', 'THE PROPER FIX', '#s4'),
  ('hp-c-biz', 'shield', 'Told to switch SMB1 on?', 'Why that quick fix costs you security', 'READ BEFORE YOU DO', '#s2'),
  ('hp-c-buy', 'wrench', 'Sort it for me', 'Real accounts and permissions, done remotely', 'FROM &pound;20', '/remote-support/'),
 ],
 'windows-11-network-credentials-shared-folder': [
  ('hp-c-biz', 'user', 'Type the right username', 'Why a bare name gets refused, and what works', 'CHECK THIS FIRST', '#s2'),
  ('hp-c-buy', 'shield', 'Save the login so it sticks', 'Set up Credential Manager once, properly', 'CREDENTIAL MANAGER', '#s3'),
 ],
 'windows-11-upgrade-service': [
  ('hp-c-fix', 'gauge', 'Free compatibility check', 'TPM 2.0, Secure Boot and processor checked', 'FREE CHECK', '#s1'),
  ('hp-c-care', 'wrench', 'Upgrade or clean install?', 'Which route suits your PC, honestly', 'WHICH ROUTE?', '#s2'),
  ('hp-c-biz', 'alert', 'PC can&rsquo;t run 11?', 'ESU to October 2027, or a refurbished Dell', 'STILL GOOD OPTIONS', '#s3'),
  ('hp-c-buy', 'shield', 'Worried about your files?', 'What an upgrade keeps, and why we back up first', 'BACKUP FIRST', '/will-i-lose-files-upgrading-to-windows-11/'),
 ],
 'wipe-deceased-relatives-laptop-pass-on': [
  ('hp-c-fix', 'shield', 'Get the photos off first', 'A wipe can&rsquo;t be undone: copy, then check', 'BEFORE ANYTHING ELSE', '#s1'),
  ('hp-c-care', 'user', 'Don&rsquo;t know the password?', 'For a wipe, often not the barrier you fear', 'OFTEN NOT NEEDED', '#s2'),
  ('hp-c-biz', 'cloud', 'Accounts and the cloud', 'Email and online photos survive a wipe', 'A SEPARATE JOB', '#s4'),
  ('hp-c-buy', 'home', 'We can do it for you', 'Free collection, contents first, then a proper wipe', 'NO RUSH', '/contact/'),
 ],
 'working-from-a-campervan': [
  ('hp-c-fix', 'wifi', '5G first, satellite second', 'How we stay online all day from the van', 'OUR SETUP', '#s2'),
  ('hp-c-care', 'book', 'Advice for van workers', 'Signal first, a second link, budget power', 'LESSONS LEARNED', '#s3'),
  ('hp-c-biz', 'monitor', 'Remote support, anywhere', 'We fix Windows PCs wherever you&rsquo;re parked', 'WINDOWS PCS', '/remote-support/'),
  ('hp-c-buy', 'shield', 'Backup internet for work', 'Two links fail differently; plan for it', 'PLAN AHEAD', '/business-continuity-internet/'),
 ],
 'worried-about-a-parent-being-scammed': [
  ('hp-c-fix', 'alert', 'Signs to look for', 'What a scam leaves behind, even from a distance', 'SPOT THE SIGNS', '#s1'),
  ('hp-c-care', 'user', 'How to raise it kindly', 'Blame the criminals, never your parent', 'NO SHAME', '#s2'),
  ('hp-c-biz', 'clock', 'What to do today', 'Six steps in order, from passwords to reporting', 'ACT TODAY', '#s3'),
  ('hp-c-buy', 'shield', 'Have the computer checked', 'We phone first, and they watch every click', 'ARRANGE FROM AFAR', '#s4'),
 ],
 'worth-repairing-old-laptop': [
  ('hp-c-fix', 'gauge', 'The 50% rule', 'When a repair stops being worth the money', 'QUICK TEST', '#s1'),
  ('hp-c-care', 'wrench', 'Just slow? Cheap wins', 'An SSD or more memory can transform it', 'OFTEN WORTH IT', '#s2'),
  ('hp-c-biz', 'shield', 'Can it run Windows 11?', 'Why the end of Windows 10 tips the balance', 'WINDOWS 10 FACTOR', '#s3'),
  ('hp-c-buy', 'laptop', 'Time to replace?', 'Refurbished business-grade Dell from &pound;510', 'FILES MOVED ACROSS', '/dell-hardware/'),
 ],
}
