#!/usr/bin/env python3
"""Freeze the crowd signal map's area totals for the press page /mobile-signal-check/data/ (17 Sep 2026).

WHY FROZEN. A journalist quotes a number and a reader checks it days later. The live map moves every time someone
tests, so the press page carries figures taken at one stated moment and says so ("frozen at 17:06 UTC on ..."). This
script takes that snapshot from api/signal-check.php?press=1 (totals by council area, counts only - see
api/signal-press-lib.php) and writes signal_press_data.py, which build_pages.write_crowd_press_page() renders.

    py refresh_signal_press.py          # fetch, check, write signal_press_data.py
    py refresh_signal_press.py --show   # print what would be written, write nothing

Then rebuild (py build_pages.py, or the full build). On any failure it leaves the existing snapshot alone.
Refresh deliberately, not on every build: a pitch quotes the frozen figures, and they must still be on the page when
the journalist clicks through. ⚠️ SiteGround's WAF 403s plain scripted requests, hence the browser UA.
"""
import json
import pprint
import sys
import urllib.request

URL = "https://365techies.co.uk/api/signal-check.php?press=1"
OUT = "signal_press_data.py"
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/140.0 Safari/537.36")
AREAS = ("all", "bcp", "bournemouth", "christchurch", "poole")


def fetch():
    req = urllib.request.Request(URL, headers={"User-Agent": UA, "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.loads(r.read().decode("utf-8"))


def check(d):
    """Refuse a snapshot that does not add up - a press page with inconsistent totals is worse than an old one."""
    problems = []
    if not d.get("ok"):
        problems.append("endpoint said ok=false: %r" % d.get("error"))
        return problems
    a = d.get("areas", {})
    for k in AREAS:
        if k not in a:
            problems.append("missing area %s" % k)
    if problems:
        return problems
    for k in AREAS:
        x, s = a[k], a[k]["squares"]
        if x["outdoor"] + x["indoor"] + x["place_unrecorded"] != x["readings"]:
            problems.append("%s: indoor/outdoor do not add up" % k)
        if sum(x["time_of_day"].values()) != x["readings"]:
            problems.append("%s: time of day does not add up" % k)
        if sum(s["verified_by_band"].values()) != s["verified"]:
            problems.append("%s: bands do not add up to verified squares" % k)
        if sum(s["verified_outdoor_by_band"].values()) != s["verified_outdoor"]:
            problems.append("%s: outdoor bands do not add up" % k)
    towns = ("bournemouth", "christchurch", "poole")
    for field in ("readings", "outdoor", "indoor"):
        if sum(a[t][field] for t in towns) != a["bcp"][field]:
            problems.append("towns' %s do not add up to BCP" % field)
    if sum(a[t]["squares"]["started"] for t in towns) != a["bcp"]["squares"]["started"]:
        problems.append("towns' squares do not add up to BCP")
    if a["bcp"]["readings"] <= 0 or a["bcp"]["readings"] > a["all"]["readings"]:
        problems.append("BCP readings out of range")
    return problems


def main():
    try:
        d = fetch()
    except Exception as e:
        print("fetch failed, snapshot unchanged: %s" % e)
        return 1
    problems = check(d)
    if problems:
        print("snapshot refused, unchanged:\n  " + "\n  ".join(problems))
        return 1
    b = d["areas"]["bcp"]
    print("BCP: %d readings (%d outdoor), %d squares, %d verified, %s to %s, frozen %s"
          % (b["readings"], b["outdoor"], b["squares"]["started"], b["squares"]["verified"],
             b["first_day"], b["last_day"], d["generated"]))
    if "--show" in sys.argv:
        pprint.pprint(d, width=120)
        return 0
    body = ('"""Frozen totals of the crowd signal map, for /mobile-signal-check/data/.\n\n'
            "GENERATED by refresh_signal_press.py from api/signal-check.php?press=1 - do not hand-edit.\n"
            "Counts only, by council area; nothing per square, per reading or per network.\n"
            '"""\n\nSIGNAL_PRESS = ' + pprint.pformat(d, width=120, sort_dicts=False) + "\n")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    print("wrote %s" % OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
