#!/usr/bin/env python3
"""Refresh the van signal map's server-rendered summary snapshot.

WHY THIS EXISTS
The ranked "best spots" on /van-signal-map/ are drawn by JavaScript from
api/signal-log.php. GPTBot, ClaudeBot and PerplexityBot do not execute
JavaScript, so to every AI answer engine the page is a brochure ABOUT a map
rather than a map — and the ranked, place-named spots are the one uniquely
owned, quotable thing on it. This bakes a dated snapshot into static HTML so
crawlers and AI retrieval can actually read it.

    py refresh_van_summary.py        # fetch and write van_map_data.py
    py refresh_van_summary.py --show # print what's live, write nothing

Then rebuild the page. Safe to run any time; if the fetch fails it leaves the
existing snapshot alone rather than blanking the page.

⚠️ SiteGround's WAF 403s plain scripted requests, hence the browser UA.
"""
import json
import sys
import urllib.request
from datetime import datetime, timezone

URL = "https://365techies.co.uk/api/signal-log.php?summary=1"
OUT = "van_map_data.py"
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/140.0 Safari/537.36")


def fetch():
    req = urllib.request.Request(URL, headers={"User-Agent": UA, "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode("utf-8", "replace"))


def main():
    try:
        d = fetch()
    except Exception as e:                      # noqa: BLE001 - report and stop
        print("FETCH FAILED: %s" % e)
        print("Existing snapshot left untouched.")
        return 1

    if not d.get("ok"):
        print("Endpoint returned not-ok; leaving snapshot untouched.")
        return 1

    spots = d.get("spots") or []
    print("live summary: %d points, %d speed tests, %d spots total, %d named, %d day(s)"
          % (d.get("points", 0), d.get("tested", 0), d.get("spots_total", 0),
             len(spots), d.get("days", 0)))
    if d.get("area_km"):
        print("             area measured: %s x %s km" % tuple(d["area_km"]))
    for i, s in enumerate(spots, 1):
        print("   %d. %-22s %5.1f Mbps  %s tests" % (i, s.get("name"), s.get("dl"), s.get("tests")))
    if not spots:
        print("   (no NAMED spots yet — every measured spot is still inside the")
        print("    no-name radius around base, or the geocoder found no locality)")

    if "--show" in sys.argv:
        return 0

    d["_refreshed"] = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write('"""Snapshot of the van signal map summary, for server-rendering.\n\n')
        f.write("GENERATED by refresh_van_summary.py — do not hand-edit.\n")
        f.write("Re-run that script and rebuild to update the numbers on the page.\n")
        f.write('"""\n\n')
        f.write("VAN_MAP_SUMMARY = ")
        f.write(repr(d))
        f.write("\n")
    print("wrote %s" % OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
