# -*- coding: utf-8 -*-
r"""Splice the dashboard band into the money pages and the hand-built homepage.

Run once. Idempotent - it refuses to insert a second copy, so re-running after
a partial failure is safe.

    py -X utf8 tools_splice_dashboard.py          # report only
    py -X utf8 tools_splice_dashboard.py --write  # apply

Two different jobs, because the site has two kinds of page:

* The five plan/subscription pages live in build_pages.py as `add(...)` calls
  with a `content="\n".join([...])` list. We insert a
  `dashboard_promo.plan_band(...)` entry into that list, before the FAQ block,
  which is where a feature band belongs on this site.
* index.html is hand-maintained and is NOT regenerated by build_blog.py (a
  build gotcha that has bitten before), so the homepage band is written
  straight into the HTML.

/pricing/ and /join/ are edited in build_extra.py by the same pass.
"""
import io
import os
import re
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
WRITE = "--write" in sys.argv

# (slug, plan_band kind)
PLAN_PAGES = [
    ("monthly-it-support", "both"),
    ("home-it-support-subscriptions", "home"),
    ("business-it-support-subscriptions", "business"),
    ("home-it-support-plans", "home"),
    ("business-it-support-plans", "business"),
]

CONTENT_MARK = 'content="\\n".join(['


def content_span(text, start):
    """Character span of the [...] list belonging to this page's content=."""
    k = text.find(CONTENT_MARK, start)
    if k < 0:
        return None
    j = k + len(CONTENT_MARK) - 1          # sits on the opening [
    depth = 0
    while j < len(text):
        if text[j] == "[":
            depth += 1
        elif text[j] == "]":
            depth -= 1
            if depth == 0:
                return (k, j)
        j += 1
    return None


def splice_build_pages(report):
    path = os.path.join(BASE, "build_pages.py")
    text = io.open(path, encoding="utf-8").read()
    if "dashboard_promo" not in text:
        text = text.replace("from snippets_data import SNIPPETS",
                            "from snippets_data import SNIPPETS\n"
                            "from dashboard_promo import plan_band as _dash_band", 1)

    # Work back-to-front so earlier insertion points stay valid.
    jobs = []
    for slug, kind in PLAN_PAGES:
        i = text.find('slug="%s",' % slug)
        if i < 0:
            report.append("  SKIP %s - slug not found" % slug)
            continue
        span = content_span(text, i)
        if not span:
            report.append("  SKIP %s - no content list" % slug)
            continue
        a, b = span
        region = text[a:b]
        if "_dash_band(" in region:
            report.append("  ALREADY %s" % slug)
            continue
        for anchor in ("\n   faq_html(", "\n   cta("):
            k = region.find(anchor)
            if k >= 0:
                jobs.append((a + k, kind, slug))
                break
        else:
            report.append("  SKIP %s - no faq_html/cta anchor" % slug)
    for pos, kind, slug in sorted(jobs, reverse=True):
        text = text[:pos] + '\n   _dash_band("%s", alt=True),' % kind + text[pos:]
        report.append("  ADDED %-38s plan_band(%s)" % (slug, kind))

    if WRITE and jobs:
        io.open(path, "w", encoding="utf-8", newline="\n").write(text)
    return len(jobs)


def splice_build_extra(report):
    """/pricing/ and /join/ are info_page() calls, not content lists.

    info_page wraps `inner` in _prose(), which cannot hold a full-width
    <section>, so both get the band through the `post=` slot instead - added to
    info_page for exactly this. The kwarg is inserted immediately before the
    call's closing paren, found by bracket matching so a nested ) in the copy
    cannot fool it.
    """
    path = os.path.join(BASE, "build_extra.py")
    text = io.open(path, encoding="utf-8").read()
    n = 0
    if "dashboard_promo" not in text:
        # Two ways to get this wrong, both paid for once:
        #  1. "from services_data import SERVICE_PAGES" is a PREFIX of
        #     "... as _SP", which appears indented inside a function - matching
        #     the substring put the import at that indentation and raised
        #     IndentationError. Anchor on a whole line at column 0.
        #  2. That module-level import sits at line ~17559, but /pricing/ is
        #     built at ~14055, so an import there is too late - NameError.
        # The module header is the only safe home.
        anchor = "import build_local  # registers the 12 local/customer pages on import\n"
        if anchor not in text:
            report.append("  SKIP build_extra.py - module header anchor not found")
            return 0
        text = text.replace(
            anchor,
            anchor + "from dashboard_promo import plan_band as _dash_band, "
                     "join_band as _dash_join\n", 1)

    for slug, kwarg in (("pricing", 'post=_dash_band("both", alt=True),'),
                        ("join", "post=_dash_join(),")):
        i = text.find('slug="%s",' % slug)
        if i < 0:
            report.append("  SKIP /%s/ - slug not found" % slug)
            continue
        # walk back to the info_page( that owns this slug, then forward to its )
        open_paren = text.rfind("(", 0, i)
        depth, j = 0, open_paren
        while j < len(text):
            if text[j] == "(":
                depth += 1
            elif text[j] == ")":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        else:
            report.append("  SKIP /%s/ - unbalanced call" % slug)
            continue
        if "post=" in text[open_paren:j]:
            report.append("  ALREADY /%s/" % slug)
            continue
        text = text[:j] + "\n  " + kwarg + "\n" + text[j:]
        report.append("  ADDED  /%s/%s" % (slug, "" if slug == "pricing" else "  (studio section)"))
        n += 1

    if WRITE and n:
        io.open(path, "w", encoding="utf-8", newline="\n").write(text)
    return n


BAND_RE = re.compile(
    r'\n\s*<section class="section section--alt" aria-label="Your 365 dashboard".*?</style>\n',
    re.S)


def splice_homepage(report):
    """index.html is hand-maintained - write the band straight in.

    Because it is a frozen COPY rather than a build-time call, an edit to
    dashboard_promo.py does NOT reach the homepage. Re-run with --refresh after
    any change to the band, or the homepage silently keeps the old markup and
    CSS. (Learned the hard way: a grid fix landed on all six built pages and not
    on the homepage, which kept rendering the broken 4+1 layout.)
    """
    from dashboard_promo import homepage_band
    path = os.path.join(BASE, "index.html")
    html = io.open(path, encoding="utf-8").read()
    if 'aria-label="Your 365 dashboard"' in html:
        if "--refresh" not in sys.argv:
            report.append("  ALREADY index.html  (pass --refresh to regenerate it "
                          "from dashboard_promo.py)")
            return 0
        m_old = BAND_RE.search(html)
        if not m_old:
            report.append("  SKIP index.html - band present but not matchable for refresh")
            return 0
        html = html[:m_old.start()] + "\n" + homepage_band() + "\n" + html[m_old.end():]
        if WRITE:
            io.open(path, "w", encoding="utf-8", newline="\n").write(html)
        report.append("  REFRESHED index.html from dashboard_promo.py")
        return 1
    # Put it after the reviews/testimonials band if there is one, else before the
    # footer - either way it lands below the fold, above the closing CTA.
    m = None
    for pat in (r'<section[^>]*aria-label="[^"]*[Rr]eview[^"]*"[^>]*>.*?</section>',
                r'<section[^>]*aria-label="[^"]*[Tt]estimonial[^"]*"[^>]*>.*?</section>'):
        m = re.search(pat, html, re.S)
        if m:
            break
    band = "\n" + homepage_band() + "\n"
    # Prefer sitting just BEFORE the page's closing CTA - a feature band that
    # lands after the final call to action reads like an afterthought, and pushes
    # the CTA away from the end of the page where it belongs.
    cta = re.search(r'\n\s*<section[^>]*\bclass="[^"]*\bcta\b[^"]*"[^>]*>', html)
    if cta and cta.start() < html.rfind("</main>"):
        html = html[:cta.start()] + band + html[cta.start():]
        report.append("  ADDED  index.html (before the closing CTA)")
    elif m:
        html = html[:m.end()] + band + html[m.end():]
        report.append("  ADDED  index.html (after the reviews band)")
    else:
        # Anchor on </main>, NOT <footer>. The footer sits AFTER </main>, so
        # anchoring there put the section outside the main landmark - wrong for
        # semantics and screen readers, and outside the page's content flow.
        k = html.rfind("</main>")
        if k < 0:
            report.append("  SKIP index.html - no </main>")
            return 0
        html = html[:k] + band + html[k:]
        report.append("  ADDED  index.html (last section inside <main>)")
    if WRITE:
        io.open(path, "w", encoding="utf-8", newline="\n").write(html)
    return 1


if __name__ == "__main__":
    report = []
    total = splice_build_pages(report) + splice_build_extra(report) + splice_homepage(report)
    print("DRY RUN - pass --write to apply\n" if not WRITE else "APPLIED\n")
    print("\n".join(report))
    print("\n%d insertion(s)" % total)
