# Choice tiles for the tool pages' first screen (26 Sep 2026 review): (colour, icon, title, line, tag, href).
# Hooked in build_pages.add() via _tool_intent_hero; a page without the standard hero is left alone.
TOOL_HERO_TILES = {
 'ai-roi-calculator': [
  ('hp-c-fix', 'gauge', 'What could AI save you?', 'Rough numbers in, hours and money saved out', 'FREE ESTIMATE', '#roicalc'),
  ('hp-c-care', 'user', 'Will AI replace my staff?', 'No: it hands their time back from repetitive work', 'YOU STAY IN CONTROL', '#faq'),
  ('hp-c-biz', 'briefcase', 'How an agent would do it', 'Agentic AI systems, mapped to your process', 'SEE HOW IT WORKS', '/ai/agents/'),
  ('hp-c-buy', 'phone', 'Talk to us about AI', 'Tell us the time-drain; we map a realistic saving', 'NO OBLIGATION', '/contact/'),
 ],
 'broadband-checker': [
  ('hp-c-fix', 'home', 'Who serves your postcode?', 'See which broadband genuinely reaches your area', 'EVERY DORSET PROVIDER', '#bbcheck'),
  ('hp-c-care', 'gauge', 'Getting what you pay for?', 'Test your real download, upload and ping', 'LIVE SPEED TEST', '/broadband-speed-checker/'),
  ('hp-c-biz', 'clock', 'Out of contract?', 'You may well be overpaying: what to check first', 'WORTH A CHECK', '#faq'),
  ('hp-c-buy', 'user', 'Free impartial review', 'We check your postcode and handle the switch', 'NO COMMISSION-CHASING', '/contact/'),
 ],
 'broadband-speed-checker': [
  ('hp-c-fix', 'gauge', 'Test your broadband speed', 'Download, upload and ping, measured live', 'NO SIGN-UP', '#spd'),
  ('hp-c-care', 'user', 'What speed do you need?', 'Three questions give your household a target', '3 QUICK QUESTIONS', '#bb'),
  ('hp-c-biz', 'home', 'How does your area compare?', 'Your result against your postcode district, fairly', 'LIKE WITH LIKE', '#bbcompare'),
  ('hp-c-buy', 'wifi', 'Slower than you pay for?', 'Often it&rsquo;s the Wi-Fi: we fix black-spots and mesh', 'ACROSS DORSET', '/wifi-support/'),
 ],
 'computer-fault-checker': [
  ('hp-c-fix', 'wrench', 'What&rsquo;s playing up?', 'Two taps to the likely cause and the next step', 'ABOUT 20 SECONDS', '#ff'),
  ('hp-c-care', 'monitor', 'Slow, pop-ups or crashing?', 'Often fixed remotely, and checking it is free', 'CHECKING IS FREE', '/remote-support/'),
  ('hp-c-biz', 'laptop', 'Needs a hands-on repair?', 'Free collection, diagnosis first, quote before work', 'NO-FIX-NO-FEE', '/book-a-collection/'),
  ('hp-c-buy', 'star', 'Worth repairing?', 'An honest verdict before you spend a penny', 'HONEST VERDICT', '/worth-repairing-old-laptop/'),
 ],
 'computer-spec-checker': [
  ('hp-c-fix', 'monitor', 'What&rsquo;s inside this PC?', 'Your specs read live in your browser, never sent to us', 'NO DOWNLOAD', '#spc'),
  ('hp-c-care', 'gauge', 'How fast is it, really?', 'Six live tests, one score you can compare', 'ABOUT 20 SECONDS', '#benchtool'),
  ('hp-c-biz', 'laptop', 'Can it run Windows 11?', 'The two deciders, and a route whatever the answer', 'STILL ON WINDOWS 10?', '#windows-11'),
  ('hp-c-buy', 'shield', 'See what a browser can&rsquo;t', 'Exact memory, drive health and battery wear', 'FREE WINDOWS APP', '#beyond-browser'),
 ],
 'cost-calculator': [
  ('hp-c-fix', 'gauge', 'See your monthly cost', 'Slide to your setup and watch the total update', 'REAL PLAN PRICES', '#costcalc'),
  ('hp-c-care', 'home', 'Home plans', '&pound;18.25 a month per computer, no lock-in', 'ROLLING MONTHLY', '/home-it-support-plans/'),
  ('hp-c-biz', 'briefcase', 'Business plans', 'From &pound;24.38 per computer a month', 'TAILORED TO YOUR TEAM', '/business-it-support-plans/'),
  ('hp-c-buy', 'user', 'Get your exact price', 'A friendly techie confirms it, no obligation', 'NO OBLIGATION', '/contact/'),
 ],
 'coverage-checker': [
  ('hp-c-fix', 'home', 'Do we cover your area?', 'Pop in your postcode for an instant answer', 'FIRST PART IS FINE', '#cov'),
  ('hp-c-care', 'monitor', 'Outside our area?', 'Secure remote help for Windows PCs, UK and Europe', 'UK AND EUROPE', '/remote-support/'),
  ('hp-c-biz', 'laptop', 'Needs hands-on repair?', 'Collected from you, diagnosed, quoted before work', 'BY COLLECTION', '/computer-repairs/'),
  ('hp-c-buy', 'calendar', 'Looked after every month', 'A full service every six weeks, from &pound;18.25', 'MONTHLY PLANS', '/home-it-support-plans/'),
 ],
 'custom-pc-builder': [
  ('hp-c-fix', 'wrench', 'Plan your custom PC', 'Your budget split across the parts, like a pro builder', 'FREE BUILD SHEET', '#pcb'),
  ('hp-c-care', 'user', 'Check my basket first', 'Compatibility and balance checked before you buy', 'FREE SANITY CHECK', '/contact/'),
  ('hp-c-biz', 'monitor', 'Under &pound;600 all-in?', 'A refurbished business Dell may beat a budget build', 'REFURBISHED DELL', '/refurbished-dell-desktops-dorset/'),
  ('hp-c-buy', 'gauge', 'Gaming PC gone slow?', 'Remote tune-up, nothing wiped, price agreed first', 'BEFORE YOU BUY NEW', '/gaming-pc-tune-up/'),
 ],
 'dns-lookup': [
  ('hp-c-fix', 'cloud', 'Look up any domain&rsquo;s DNS', 'A, MX, NS and TXT records, read live', 'LIVE AND FREE', '#dns'),
  ('hp-c-care', 'book', 'What do these records mean?', 'Website, email and nameservers in plain English', 'PLAIN ENGLISH', '#faq'),
  ('hp-c-biz', 'shield', 'Can scammers spoof you?', 'SPF, DKIM and DMARC checked in plain English', 'FREE CHECK', '/email-security-checker/'),
  ('hp-c-buy', 'mail', 'Email or website broken?', 'We fix DNS, move sites and sort business email', 'HOMES AND BUSINESSES', '/email-support/'),
 ],
 'email-security-checker': [
  ('hp-c-fix', 'shield', 'Can scammers send as you?', 'SPF, DKIM and DMARC checked on your domain, live', 'NO EMAIL NEEDED', '#esec'),
  ('hp-c-care', 'book', 'What is DMARC, really?', 'The record that tells inboxes what to do with fakes', 'PLAIN ENGLISH', '#faq'),
  ('hp-c-biz', 'mail', 'See a fake, safely', 'One harmless test email, sent only to your own inbox', 'FREE SPOOFING TEST', '/contact/'),
  ('hp-c-buy', 'briefcase', 'Not protected? We&rsquo;ll fix it', 'SPF, DKIM and DMARC set up with no disruption', 'USUALLY WITHIN A DAY', '/cybersecurity-support/'),
 ],
 'email-signature-generator': [
  ('hp-c-fix', 'mail', 'Make your email signature', 'Live preview, then copy into Outlook or Gmail', 'NO WATERMARK', '#sg'),
  ('hp-c-care', 'book', 'How do I add it to Outlook?', 'Steps for Outlook, Gmail and Apple Mail', 'STEP BY STEP', '#faq'),
  ('hp-c-biz', 'shield', 'Can scammers spoof you?', 'SPF, DKIM and DMARC checked in plain English', 'FREE CHECK', '/email-security-checker/'),
  ('hp-c-buy', 'briefcase', 'Signatures for your team?', 'Centrally managed across Microsoft 365', 'NOBODY CAN BREAK THEM', '/microsoft-365-support/'),
 ],
 'free-tools': [
  ('hp-c-fix', 'monitor', 'What&rsquo;s inside my PC?', 'Specs read live in your browser, nothing installed', 'NO DOWNLOAD', '/computer-spec-checker/'),
  ('hp-c-care', 'alert', 'Is it down, or just me?', 'Live status for 30+ services, and your connection', 'LIVE CHECK', '/is-it-down/'),
  ('hp-c-biz', 'wifi', 'Test your WiFi room by room', 'Find the dead spots, with honest advice', 'FREE, SAVES AS YOU GO', '/wifi-signal-test/'),
  ('hp-c-buy', 'user', 'Want it sorted for you?', 'A friendly techie on a plan, &pound;18.25 a month per PC', 'HOME PLANS', '/home-it-support-plans/'),
 ],
 'graphics-card-benchmark': [
  ('hp-c-fix', 'gauge', 'How powerful is your GPU?', 'A live 3D scene, FPS and a graphics score', 'NOTHING TO INSTALL', '#gputool'),
  ('hp-c-care', 'alert', 'Score capped or low?', 'Refresh rate, power mode and other easy fixes', 'OFTEN FIXABLE', '#faq'),
  ('hp-c-biz', 'monitor', 'Where&rsquo;s the real bottleneck?', 'Six tests: processor, memory, storage and graphics', 'FULL PC BENCHMARK', '/pc-benchmark/'),
  ('hp-c-buy', 'wrench', 'Gaming PC gone slow?', 'Tuned up remotely before you spend on new parts', 'REMOTE TUNE-UP', '/gaming-pc-tune-up/'),
 ],
 'is-it-down': [
  ('hp-c-fix', 'wifi', 'Is it down, or just you?', 'Test your connection, then 30+ live services', 'LIVE CHECK', '#iid'),
  ('hp-c-care', 'phone', 'Broadband or mobile down?', 'Every main UK provider&rsquo;s outage checker and number', 'UK PROVIDER NUMBERS', '#iid-isps'),
  ('hp-c-biz', 'wrench', 'Something IS down. Now what?', 'The exact order we&rsquo;d work through it ourselves', 'STEP BY STEP', '#iid-help'),
  ('hp-c-buy', 'home', 'Only down for you?', 'Router, Wi-Fi or computer: we fix the local bit', 'SAME-DAY HELP', '/wifi-support/'),
 ],
 'link-safety-checker': [
  ('hp-c-fix', 'shield', 'Is that link safe to click?', 'We check the address for scam signs, never opening it', 'WE NEVER OPEN IT', '#scam'),
  ('hp-c-care', 'star', 'Could you spot a scam?', 'Six real-looking messages: scam or genuine?', 'FREE QUIZ', '/spot-the-scam/'),
  ('hp-c-biz', 'alert', 'Already clicked or paid?', 'We clean up and write a report for your bank', 'SCAM RECOVERY', '/scam-recovery/'),
  ('hp-c-buy', 'mail', 'Not sure about a message?', 'Send it to us and we&rsquo;ll tell you if it&rsquo;s a scam', 'NO JUDGEMENT', '/contact/'),
 ],
 'password-breach-checker': [
  ('hp-c-fix', 'shield', 'Has your password leaked?', 'Checked privately; your password never leaves the page', 'PRIVATE AND SAFE', '#pwn'),
  ('hp-c-care', 'alert', 'My password was found', 'What to change first, and why it matters everywhere', 'WHAT TO DO NEXT', '#faq'),
  ('hp-c-biz', 'star', 'Make a new one', 'A strong random password or passphrase, in one click', 'FREE GENERATOR', '/password-generator/'),
  ('hp-c-buy', 'user', 'Lock down your accounts', 'Password manager and two-step sign-in set up for you', 'HOMES AND BUSINESSES', '/contact/'),
 ],
 'password-generator': [
  ('hp-c-fix', 'shield', 'Make a strong password', 'Random or memorable, made in your browser', 'NEVER SENT ANYWHERE', '#pg'),
  ('hp-c-care', 'alert', 'Has an old one leaked?', 'Check it against real data breaches, privately', 'FREE CHECK', '/password-breach-checker/'),
  ('hp-c-biz', 'book', 'Random or passphrase?', 'Which to use, and how to keep track of them all', 'PLAIN ENGLISH', '#faq'),
  ('hp-c-buy', 'user', 'Too many to remember?', 'We set up a password manager and show you how', 'HOMES AND BUSINESSES', '/contact/'),
 ],
 'password-strength-checker': [
  ('hp-c-fix', 'shield', 'Is your password strong?', 'Tested in your browser, never sent or saved', '100% IN YOUR BROWSER', '#pw-in'),
  ('hp-c-care', 'star', 'Get one you can remember', 'Three random words, the NCSC method', 'NCSC METHOD', '#pw-gen'),
  ('hp-c-biz', 'alert', 'Has it been leaked?', 'Check privately against real data breaches', 'FREE CHECK', '/password-breach-checker/'),
  ('hp-c-buy', 'user', 'Lock down your accounts', 'Password manager and two-step sign-in, set up with you', 'PATIENTLY, WITH YOU', '/contact/'),
 ],
 'pc-benchmark': [
  ('hp-c-fix', 'gauge', 'How fast is it, really?', 'Six live tests, one score you can compare', 'ABOUT 20 SECONDS', '#bm'),
  ('hp-c-care', 'alert', 'Score lower than hoped?', 'The usual fixable reasons, in plain English', 'OFTEN FIXABLE', '#faq'),
  ('hp-c-biz', 'laptop', 'Still on a hard drive?', 'An SSD upgrade often transforms an older machine', 'BY COLLECTION', '/laptop-ssd-upgrade-bournemouth/'),
  ('hp-c-buy', 'calendar', 'Faster, and kept that way', 'A full service every six weeks, from &pound;18.25 a month', 'ROLLING MONTHLY', '#keep-it'),
 ],
 'plan-finder': [
  ('hp-c-fix', 'star', 'Which plan is right for you?', 'Three quick questions, an honest recommendation', 'ABOUT 30 SECONDS', '#quiz'),
  ('hp-c-care', 'home', 'Home plans', '&pound;18.25 a month per computer', '6-WEEKLY SERVICE', '/home-it-support-plans/'),
  ('hp-c-biz', 'briefcase', 'Business plans', 'From &pound;24.38 per computer a month', 'SOLE TRADERS TO TEAMS', '/business-it-support-plans/'),
  ('hp-c-buy', 'user', 'Still not sure?', 'Tell us your setup and a techie recommends the plan', 'NO PRESSURE', '/contact/'),
 ],
 'qr-code-generator': [
  ('hp-c-fix', 'star', 'Make a QR code', 'Any link, text, email or number, ready to print', 'NO WATERMARK', '#qg'),
  ('hp-c-care', 'wifi', 'Wi-Fi QR for guests', 'They scan once and join, no password read out', 'SCAN TO CONNECT', '/wifi-qr-code-generator/'),
  ('hp-c-biz', 'user', 'More Google reviews?', 'A review code on receipts, counters and cards', 'REVIEW CODES', '#faq'),
  ('hp-c-buy', 'briefcase', 'Want it done for you?', 'We set up review and Wi-Fi codes for your business', 'DORSET BUSINESSES', '/contact/'),
 ],
 'quick-quote': [
  ('hp-c-fix', 'clock', 'Get a quote in a minute', 'Four quick questions, an honest tailored price', 'NO OBLIGATION', '#qq'),
  ('hp-c-care', 'home', 'Home plans', '&pound;18.25 a month per computer', 'HOME AND FAMILY', '/home-it-support-plans/'),
  ('hp-c-biz', 'briefcase', 'Business plans', 'From &pound;24.38 per computer a month', 'SMALL BUSINESSES', '/business-it-support-plans/'),
  ('hp-c-buy', 'phone', 'Rather just talk?', 'Call a friendly local techie, no scripts', 'NO PRESSURE', '/contact/'),
 ],
 'solar-battery-calculator': [
  ('hp-c-fix', 'power', 'Size your battery and solar', 'Tick what you run; get lithium and panel sizes', 'UK SUN FIGURES', '#solc'),
  ('hp-c-care', 'gauge', 'Turn it into a kit list', 'Four questions, a complete Victron parts list', 'FREE BUILDER', '/victron-system-builder/'),
  ('hp-c-biz', 'book', 'Lithium or AGM?', 'Why the AGM size is nearly double, and winter sun', 'HONEST ANSWERS', '#faq'),
  ('hp-c-buy', 'wrench', 'Sized, supplied, fitted', 'Victron installs for vans, boats and cabins in Dorset', 'WE SURVEY FIRST', '/victron-installer-dorset/'),
 ],
 'spot-the-scam': [
  ('hp-c-fix', 'star', 'Could you spot a scam?', 'Six real-looking messages: scam or genuine?', 'ABOUT 2 MINUTES', '#sc'),
  ('hp-c-care', 'shield', 'Got a dodgy-looking link?', 'Check the address without ever opening it', 'FREE CHECK', '/link-safety-checker/'),
  ('hp-c-biz', 'phone', 'Is that caller genuine?', 'Banks and Microsoft don&rsquo;t cold-call about your PC', 'PHONE SCAMS', '#faq'),
  ('hp-c-buy', 'user', 'Someone to check with', 'Ask us before you click, on a home support plan', 'HOME PLANS', '/home-it-support-plans/'),
 ],
 'ssl-checker': [
  ('hp-c-fix', 'shield', 'Is your padlock healthy?', 'Valid or not, who issued it, and when it expires', 'EXPIRY COUNTDOWN', '#sslc'),
  ('hp-c-care', 'clock', 'Expiring soon?', 'What to do, and why auto-renewal needs checking', 'CHECK AUTO-RENEWAL', '#faq'),
  ('hp-c-biz', 'gauge', 'Check the whole site', 'Speed, SEO and security via Google Lighthouse', 'FREE HEALTH CHECK', '/website-checker/'),
  ('hp-c-buy', 'briefcase', 'Hosting that renews itself', 'Certificates, backups and updates quietly handled', 'LOCAL TEAM', '/web-design-hosting/'),
 ],
 'victron-system-builder': [
  ('hp-c-fix', 'power', 'Build your Victron system', 'Four questions, a complete kit list with buy links', 'HONEST UK SIZING', '#vb'),
  ('hp-c-care', 'wrench', 'Cables, lugs and fuses', 'Sized per circuit; the fuse protects the cable', 'PER CIRCUIT', '#vb-wiring'),
  ('hp-c-biz', 'gauge', 'Not sure of your daily use?', 'Tick what you run and work out your Wh per day', 'FREE CALCULATOR', '/solar-battery-calculator/'),
  ('hp-c-buy', 'briefcase', 'Or have us design and fit it', 'The kit our own support van runs on, fitted safely', 'DESIGN, SUPPLY, FIT', '/victron-installer-dorset/'),
 ],
 'website-checker': [
  ('hp-c-fix', 'gauge', 'Check any website', 'Speed, SEO, security and mobile, via Lighthouse', 'FREE, NO SIGN-UP', '#wcheck'),
  ('hp-c-care', 'book', 'What do the scores mean?', 'Green, amber, red, and what to fix first', 'PLAIN ENGLISH', '#faq'),
  ('hp-c-biz', 'wrench', 'Slow WordPress site?', 'Fix it or rebuild it: an honest verdict', 'FIX OR REBUILD', '/slow-wordpress-site-fix-or-rebuild/'),
  ('hp-c-buy', 'briefcase', 'Want these issues fixed?', 'A free fix-it plan from a local web team', 'FREE FIX-IT PLAN', '/contact/'),
 ],
 'what-websites-know': [
  ('hp-c-fix', 'monitor', 'What can websites see?', 'Your device&rsquo;s giveaways, shown only to you', 'NOTHING STORED', '#priv'),
  ('hp-c-care', 'book', 'How do I give away less?', 'Simple settings that make a real difference', 'PLAIN ENGLISH', '#faq'),
  ('hp-c-biz', 'shield', 'Is that link safe?', 'Check the address for scam signs, never opening it', 'FREE CHECK', '/link-safety-checker/'),
  ('hp-c-buy', 'user', 'Take back your privacy', 'Browser settings and a full privacy check-up', 'NO JARGON', '/contact/'),
 ],
 'what-would-you-lose': [
  ('hp-c-fix', 'alert', 'What would you lose today?', 'Two questions: how safe are your photos and files?', 'TAKES 20 SECONDS', '#wl'),
  ('hp-c-care', 'cloud', 'Isn&rsquo;t OneDrive a backup?', 'Why sync alone can copy a deletion everywhere', 'NOT QUITE', '#faq'),
  ('hp-c-biz', 'shield', 'Set up a proper backup', 'Automatic, checked, and kept separate', '3-2-1 RULE', '/backup-support/'),
  ('hp-c-buy', 'wrench', 'Already lost something?', 'Stop using the drive and let us look first', 'DIAGNOSIS FIRST', '/data-recovery/'),
 ],
 'which-microsoft-365-plan': [
  ('hp-c-fix', 'cloud', 'Which Microsoft 365 plan?', 'A few quick questions, the right licence', 'ABOUT 30 SECONDS', '#m365sel'),
  ('hp-c-care', 'home', 'Personal or Family?', 'Family shares with up to six people, 1TB each', 'HOME USERS', '#faq'),
  ('hp-c-biz', 'briefcase', 'Set it up properly', 'Licences, set-up and email moved, nothing lost', 'NOTHING LOST', '/microsoft-365-support/'),
  ('hp-c-buy', 'user', 'Still not sure which?', 'We confirm the best-value option with you, free', 'NO UPSELLING', '/contact/'),
 ],
 'wifi-qr-code-generator': [
  ('hp-c-fix', 'wifi', 'Make a Wi-Fi QR code', 'Guests scan once and join, no password read out', 'PASSWORD STAYS PRIVATE', '#wq'),
  ('hp-c-care', 'gauge', 'Does the Wi-Fi reach them?', 'Walk room by room and see where the signal drops', 'FREE SIGNAL TEST', '/wifi-signal-test/'),
  ('hp-c-biz', 'briefcase', 'Guest Wi-Fi for a business?', 'Kept separate from your business systems', 'SEPARATE AND SECURE', '/business-wifi-installation/'),
  ('hp-c-buy', 'wrench', 'Wi-Fi that just works', 'Black-spots fixed and mesh fitted properly', 'ACROSS DORSET', '/wifi-support/'),
 ],
 'wifi-signal-test': [
  ('hp-c-fix', 'wifi', 'Test your WiFi room by room', 'Walk around; every room gets a score and advice', 'FREE, SAVES AS YOU GO', '#finder'),
  ('hp-c-care', 'gauge', 'What your readings mean', 'Tailored fixes, including when a purchase won&rsquo;t help', 'HONEST ADVICE', '#wf-advice'),
  ('hp-c-biz', 'user', 'Send it to a real person', 'A local techie looks at your rooms and replies', 'FREE, NO OBLIGATION', '#wf-send'),
  ('hp-c-buy', 'wrench', 'Want it just sorted?', 'Black-spots fixed and mesh fitted properly', 'ACROSS DORSET', '/wifi-support/'),
 ],
}
