"""Snapshot of the van signal map summary, for server-rendering.

GENERATED by refresh_van_summary.py — do not hand-edit.
Re-run that script and rebuild to update the numbers on the page.
"""

VAN_MAP_SUMMARY = {'ok': True, 'generated': '2026-08-12T09:27:12+00:00', 'points': 446, 'tested': 263, 'spots_total': 10, 'days': 1, 'first_day': '2026-08-11', 'last_day': '2026-08-11', 'area_km': [5.4, 4.2], 'spots': [{'name': 'Bournemouth', 'dl': 41, 'ms': 50, 'sinr': 2, 'net': '5G', 'tests': 2, 'days': 1}, {'name': 'Bournemouth', 'dl': 39.2, 'ms': 53, 'sinr': 17, 'net': '4G+', 'tests': 34, 'days': 1}, {'name': 'West Parley', 'dl': 29.8, 'ms': 62, 'sinr': 3, 'net': '4G', 'tests': 15, 'days': 1}, {'name': 'Bournemouth', 'dl': 27.9, 'ms': 38, 'sinr': 10, 'net': '5G', 'tests': 11, 'days': 1}, {'name': 'Ferndown Town', 'dl': 20.8, 'ms': 60, 'sinr': 7, 'net': '4G', 'tests': 12, 'days': 1}], '_refreshed': '2026-08-12 09:27 UTC'}
