"""Snapshot of the van signal map summary, for server-rendering.

GENERATED by refresh_van_summary.py — do not hand-edit.
Re-run that script and rebuild to update the numbers on the page.
"""

VAN_MAP_SUMMARY = {'ok': True, 'generated': '2026-08-16T20:36:22+00:00', 'points': 1763, 'tested': 1532, 'spots_total': 74, 'spots_named': 4, 'days': 4, 'first_day': '2026-08-11', 'last_day': '2026-08-16', 'area_km': [12, 15.3], 'spots': [{'name': 'Poole', 'dl': 90.7, 'ms': 38, 'sinr': 9, 'net': '5G', 'tests': 550, 'days': 1}, {'name': 'West Parley', 'dl': 29.8, 'ms': 62, 'sinr': 3, 'net': '4G', 'tests': 15, 'days': 1}, {'name': 'Bournemouth', 'dl': 24.2, 'ms': 58, 'sinr': 12, 'net': '4G+', 'tests': 394, 'days': 3}, {'name': 'Ferndown Town', 'dl': 20.8, 'ms': 60, 'sinr': 7, 'net': '4G', 'tests': 12, 'days': 1}], '_refreshed': '2026-08-16 20:36 UTC'}
