// GLSL EMITTER + UBO PACKER - the other half of "ONE WAVE TABLE".
//
// SPEC section 3: "the JS sampler and the GLSL vertex shader are both generated
// from that same array (GLSL string-templated at load), so they cannot drift
// apart."
//
// The way that promise is actually kept here is worth being explicit about,
// because "generated from the same array" is easy to claim and easy to break:
//
//   * The emitted STRING is invariant to the sea state and to the seed. It
//     depends only on MAX_WAVES / N_VERTEX / N_PHYS. So changing the sea is a
//     bufferSubData, never a recompile - which is what protects the 400 ms
//     restart budget and the "zero shader-compile stutter" rule.
//   * The VALUES travel through packUBO(), reading the very same Float64Arrays
//     that the CPU sampler reads. There is no second array to fall out of sync.
//   * The maths inside seaSurface() is a line-for-line transcription of the CPU
//     accumulators in sea.js. Both produce the same displaced position, the same
//     E/J accumulators and the same normal, so the two surfaces agree to float32
//     across the tier 0/1 band.
//
// Pure string construction. Zero WebGL, zero DOM - node imports this.

import { MAX_WAVES, N_PHYS, N_VERTEX, TWO_PI, INV_TWO_PI } from './sea-state.js';
// The arena's shore field rides in the SAME uniform block as the wave table,
// for the same reason the wave table is there: one upload, one copy, and the
// CPU sampler reads the very array that was uploaded. See sea-shore.js for why
// it is a uniform block and not a GLSL const array (it was priced: ~0.9 ms of
// shader compile per const float) and not a texture (renderer.js has no texture
// path for the water program and is not ours to change).
//
// ⚠️ WITH THE ARENA FLAG OFF, SHORE_ON IS FALSE, SHORE.floats IS 0 AND EVERY
// TEMPLATE BELOW EMITS THE EMPTY STRING. The chunk this file produces is then
// byte-for-byte the one it produced before this work, which is what makes
// Bournemouth's 19 judged views bit-identical by construction rather than by
// inspection.
import { SHORE, SHORE_ON, SHORE_PACK } from './sea-shore.js';

const FLOATS_PER_WAVE = 8;     // wA[i] (4) + wB[i] (4)
const UBO_NAME = 'Waves';
const UBO_BINDING = 0;

// std140 vec4 arrays are tightly packed at 16 bytes each, so the two arrays sit
// back to back: wA at float 0, wB at float MAX_WAVES*4.
const B_OFFSET = MAX_WAVES * 4;

// ---------------------------------------------------------------------------
// THE SHORE FIELD, in GLSL. Emitted ONLY when the arena flag is on; otherwise
// this returns '' and the chunk is unchanged.
//
// shoreFieldAt(p) returns (signed distance offshore, unit gradient x, z) from
// ONE bilinear cell. FOUR uniform-block reads, and the gradient - the direction
// the crest faces - comes out of the same four numbers with no extra taps.
// Bournemouth's shoreline needs two further table reads to difference mhw().
//
// The decode is arithmetically identical to shoreField() in sea-shore.js,
// reading the same quantised values out of the same array. sea-check gates them
// against each other at 4,000 points; they are not allowed to merely look alike.
function shoreChunk() {
  if (!SHORE_ON) return '';
  const f = (v) => { const s = v.toFixed(7); return s.indexOf('.') < 0 ? s + '.0' : s; };
  return `
// ---------------------------------------------------------------------------
// SHORE FIELD - generated by src/sea-shore.js from the EA LIDAR waterline of
// the Old Harry arena. Do not hand-edit; do not duplicate.
//
// ⚠️ THE BED UNDER THIS SHORELINE IS NOT SURVEYED. The LIDAR composite bottoms
// out at -1.2 m ODN over the whole arena (84.5% of its wet nodes read -0.8 to
// -1.0 m: that is the water surface, not a bed). The shoreline SHAPE is
// measured; the DEPTH profile is the model's own shoreface law, which the
// surveyed intertidal run happens to agree with to 15% at the headland.
#define SH_NX ${SHORE.nx}
#define SH_NZ ${SHORE.nz}
const float SH_X0    = ${f(SHORE.x0)};
const float SH_Z0    = ${f(SHORE.z0)};
const float SH_X1    = ${f(SHORE.x1)};
const float SH_Z1    = ${f(SHORE.z1)};
const float SH_IHX   = ${f(1 / SHORE.hx)};
const float SH_IHZ   = ${f(1 / SHORE.hz)};
const float SH_QBITS = ${f(SHORE.qBits)};
const float SH_IQ    = ${f(1 / SHORE.qBits)};
const float SH_SCALE = ${f(SHORE.qScale)};
const float SH_BIAS  = ${f(SHORE.dMin)};

// One node, unpacked. Two 11-bit codes share a float; even i is the high half.
float shNode(int i, int j) {
  int idx = j * SH_NX + i;
  int fi  = idx >> 1;
  float p = shF[fi >> 2][fi & 3];
  float hi = floor(p * SH_IQ);
  return ((idx & 1) == 0 ? hi : p - hi * SH_QBITS) * SH_SCALE + SH_BIAS;
}

vec3 shoreFieldAt(vec2 p) {
  float cx = clamp(p.x, SH_X0, SH_X1);
  float cz = clamp(p.y, SH_Z0, SH_Z1);
  float u  = (cx - SH_X0) * SH_IHX;
  float v  = (cz - SH_Z0) * SH_IHZ;
  int i = int(min(u, float(SH_NX - 2)));
  int j = int(min(v, float(SH_NZ - 2)));
  float fu = u - float(i), fv = v - float(j);
  float a = shNode(i, j),     b = shNode(i + 1, j);
  float c = shNode(i, j + 1), e = shNode(i + 1, j + 1);
  float lo = a + (b - a) * fu, up = c + (e - c) * fu;
  float d = lo + (up - lo) * fv;
  vec2 g = vec2(((b - a) + ((e - c) - (b - a)) * fv) * SH_IHX,
                ((c - a) + ((e - b) - (c - a)) * fu) * SH_IHZ);
  g /= max(length(g), 1e-6);
  // Outside the baked box, continue the field ALONG ITS OWN GRADIENT rather
  // than at unit rate in every direction: where the coast runs off an edge that
  // carries the surf band straight on instead of cutting it off at a line.
  return vec3(d + (p.x - cx) * g.x + (p.y - cz) * g.y, g.x, g.y);
}
`;
}

function buildChunk() {
  return `
// ---------------------------------------------------------------------------
// SEA - generated by src/sea-glsl.js from the SAME component table the CPU
// sampler in src/sea.js reads. Do not hand-edit; do not duplicate.
//
//   wA[i] = (k*dx, k*dz, omega, amplitude)
//   wB[i] = (phase AT THE CURRENT TIME, Q, k, lambda)
//
// TIME NEVER ENTERS THIS SHADER. wB[i].x already carries
// wrap(phase_i - omega_i*t), computed on the CPU in doubles and wrapped to
// [-pi, pi]. A float32 "k*x - omega*t" decays to visible phase noise inside a
// long session; this is the fix and it is not optional.
//
// Tiers, by index, fixed for all time:
//   0 - 7   physics + vertex displacement   (CPU and GPU agree here)
//   8 - 15  vertex displacement only
//   16 - 31 fragment normal only, Q = 0     (never displaced: displacing them
//           would need 0.05 m vertex spacing and would eat the steepness budget)
// ---------------------------------------------------------------------------
#define SEA_N_WAVES  ${MAX_WAVES}
#define SEA_N_VERTEX ${N_VERTEX}
#define SEA_N_PHYS   ${N_PHYS}

layout(std140) uniform ${UBO_NAME} {
  vec4 wA[SEA_N_WAVES];
  vec4 wB[SEA_N_WAVES];${SHORE_ON ? `
  // The arena shore field: ${SHORE.nx} x ${SHORE.nz} signed offshore distances,
  // two 11-bit codes to a float, ${SHORE.vec4s} vec4. std140 pads a bare float[]
  // to 16 bytes an element, which is why this is not float shF[].
  vec4 shF[${SHORE.vec4s}];` : ''}
};
${shoreChunk()}
// Displaced surface for tiers 0+1, with an analytic normal and the horizontal
// Jacobian. jac < 0.35 is a whitecap; jac <= 0 would be a looped (folded)
// surface, which the global steepness clamp on the CPU makes unreachable.
//
// p0 is the UNDISPLACED (Lagrangian) coordinate, in world metres. Do not add a
// large origin offset: float32 mantissa runs out long before the map does.
void seaSurface(vec2 p0, float tide, out vec3 P, out vec3 N, out float jac) {
  vec2  sea_D = vec2(0.0);
  vec2  sea_E = vec2(0.0);
  float sea_H = 0.0;
  float sea_Jxx = 0.0, sea_Jzz = 0.0, sea_Jxz = 0.0;

  for (int i = 0; i < SEA_N_VERTEX; i++) {
    vec4 A = wA[i];
    vec4 B = wB[i];
    float sea_k = B.z;
    float sea_invk = sea_k > 0.0 ? 1.0 / sea_k : 0.0;
    vec2  sea_dir = A.xy * sea_invk;          // unit direction of travel
    float sea_a = A.w;
    float sea_Q = B.y;

    float psi = dot(A.xy, p0) + B.x;
    float S = sin(psi);
    float C = cos(psi);

    float qa  = sea_Q * sea_a;
    float qak = qa * sea_k;

    sea_D   += qa * sea_dir * S;
    sea_H   += sea_a * C;
    sea_E   += sea_a * sea_k * sea_dir * S;
    sea_Jxx += qak * sea_dir.x * sea_dir.x * C;
    sea_Jzz += qak * sea_dir.y * sea_dir.y * C;
    sea_Jxz += qak * sea_dir.x * sea_dir.y * C;
  }

  P = vec3(p0.x - sea_D.x, tide + sea_H, p0.y - sea_D.y);

  float nxp = sea_E.x * (1.0 - sea_Jzz) + sea_E.y * sea_Jxz;
  float nyp = (1.0 - sea_Jxx) * (1.0 - sea_Jzz) - sea_Jxz * sea_Jxz;
  float nzp = sea_E.y * (1.0 - sea_Jxx) + sea_E.x * sea_Jxz;
  jac = nyp;
  N = normalize(vec3(nxp, nyp, nzp));
}

// Tier 2: normal perturbation only, no displacement. This is the 65% of the
// surface slope that the 8-component physics band deliberately does not carry -
// the documented sub-1.5 m tolerance, spent where it belongs (on the eyes).
vec3 seaDetailNormal(vec2 p0) {
  vec2 sea_E = vec2(0.0);
  for (int i = SEA_N_VERTEX; i < SEA_N_WAVES; i++) {
    vec4 A = wA[i];
    vec4 B = wB[i];
    float sea_k = B.z;
    float sea_invk = sea_k > 0.0 ? 1.0 / sea_k : 0.0;
    vec2 sea_dir = A.xy * sea_invk;
    float psi = dot(A.xy, p0) + B.x;
    sea_E += A.w * sea_k * sea_dir * sin(psi);
  }
  return normalize(vec3(sea_E.x, 1.0, sea_E.y));
}
`;
}

const CHUNK = buildChunk();

export const SEA_GLSL = Object.freeze({
  nWaves: MAX_WAVES,
  nVertex: N_VERTEX,
  nPhys: N_PHYS,
  floatsPerWave: FLOATS_PER_WAVE,
  uboName: UBO_NAME,
  uboBinding: UBO_BINDING,
  chunk: CHUNK,
});

// ---------------------------------------------------------------------------
// packUBO: the entire per-frame CPU cost of the wave table. 256 floats, 1 KB.
// No allocation - dst is the renderer's single Float32Array.
//
// A FLAT sea packs amp = 0 and Q = 0 for every component. The shader still runs
// its 32-iteration loop and produces a flat plane. There is deliberately no
// "flat" shader permutation: a permutation is a second program to compile, and
// the first frame after switching to it is exactly the stutter the budget bans.
// ---------------------------------------------------------------------------
export function packWaveUBO(dst, T, t) {
  // The shore field is invariant - it is a property of the arena, not of the
  // sea state - so this is a typed-array memcpy of SHORE.floats floats into
  // the tail of the same buffer, about 15 KB. It is rewritten every frame
  // rather than once because renderer.js owns the buffer's lifetime and uploads
  // the whole array; writing it here keeps this function the ONLY thing that
  // knows the block's layout. With the flag off SHORE_PACK is empty and this
  // line is a no-op on a zero-length array.
  if (SHORE_PACK.length) dst.set(SHORE_PACK, MAX_WAVES * FLOATS_PER_WAVE);
  for (let i = 0; i < MAX_WAVES; i++) {
    const k = T.k[i];
    const o = i * 4;
    dst[o]     = k * T.dx[i];
    dst[o + 1] = k * T.dz[i];
    dst[o + 2] = T.omega[i];
    dst[o + 3] = T.amp[i];

    // Wrapped in JS doubles, then handed to the shader as a small float32.
    let psi = T.phase[i] - T.omega[i] * t;
    psi -= TWO_PI * Math.round(psi * INV_TWO_PI);

    const p = B_OFFSET + i * 4;
    dst[p]     = psi;
    dst[p + 1] = T.Q[i];
    dst[p + 2] = k;
    dst[p + 3] = T.lambda[i];
  }
  return dst;
}

// The block is the wave table plus, when the arena is on, the shore field.
// renderer.js sizes its Float32Array and its gl.bufferData from this one number
// and never needs to know what is in the tail.
export const UBO_FLOATS = MAX_WAVES * FLOATS_PER_WAVE + SHORE.floats;
